--------------------------------------------------------
--  DDL for Type DOO_SO_MAAS_LOT_SERIALS_RT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."DOO_SO_MAAS_LOT_SERIALS_RT" FORCE AS OBJECT
(
    SOURCE_TRANSACTION_LOT_ID        VARCHAR2 (200),
    SOURCE_TRANSACTION_SYSTEM        VARCHAR2 (120),
    SOURCE_TRANSACTION_ID            VARCHAR2 (200),
    SOURCE_TRANSACTION_SCHEDULE_ID   VARCHAR2 (200),
    SOURCE_TRANSACTION_LINE_ID       VARCHAR2 (200),
    LOT_NUMBER                       VARCHAR2 (1280),
    LOAD_REQUEST_ID                  NUMBER,
    LOCATOR_ID                       NUMBER,
    ITEM_REVISION_NUMBER             VARCHAR2 (1280),
    SERIAL_NUMBER_FROM               VARCHAR2 (480),
    SERIAL_NUMBER_TO                 VARCHAR2 (480),
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_LOT_SERIALS_RT" RETURN SELF AS RESULT
);
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "HBG_INTEGRATION"."DOO_SO_MAAS_LOT_SERIALS_RT" 
AS
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_LOT_SERIALS_RT"
        RETURN SELF AS RESULT
    AS
    BEGIN
        RETURN;
    END;
END;

/
