--------------------------------------------------------
--  DDL for Type DOO_SO_MAAS_DOC_REFERENCES_RT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."DOO_SO_MAAS_DOC_REFERENCES_RT" FORCE AS OBJECT
(
    SOURCE_TRANSACTION_LINE_ID       VARCHAR2 (200),
    SOURCE_TRANSACTION_SCHEDULE_ID   VARCHAR2 (200),
    SOURCE_TRANSACTION_ID            VARCHAR2 (200),
    SOURCE_TRANSACTION_SYSTEM        VARCHAR2 (120),
    DOCUMENT_REFERENCE_TYPE          VARCHAR2 (120),
    DOCUMENT_ID                      VARCHAR2 (200),
    DOCUMENT_ADDITIONAL_ID           VARCHAR2 (200),
    DOCUMENT_NUMBER                  VARCHAR2 (600),
    DOCUMENT_ADDITIONAL_NUMBER       VARCHAR2 (600),
    DOCUMENT_LINE_ID                 VARCHAR2 (200),
    DOCUMENT_ADDITIONAL_LINE_ID      VARCHAR2 (200),
    DOCUMENT_LINE_NUMBER             VARCHAR2 (600),
    DOCUMENT_ADDITIONAL_LINE_NO      VARCHAR2 (600),
    DOCUMENT_SUBLINE_ID              VARCHAR2 (200),
    DOCUMENT_ADDITIONAL_SUBLINE_ID   VARCHAR2 (200),
    DOCUMENT_SUBLINE_NUMBER          VARCHAR2 (600),
    DOCUMENT_ADDITIONAL_SUBLINE_NO   VARCHAR2 (600),
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_DOC_REFERENCES_RT" RETURN SELF AS RESULT
);
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "HBG_INTEGRATION"."DOO_SO_MAAS_DOC_REFERENCES_RT" 
AS
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_DOC_REFERENCES_RT"
        RETURN SELF AS RESULT
    AS
    BEGIN
        RETURN;
    END;
END;

/
