--------------------------------------------------------
--  File created - Tuesday-April-18-2023   
--------------------------------------------------------
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_ADDRESSES_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_BATCHES_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_BILLING_PLANS_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_CHARGES_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_CHARGE_COMPS_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_DOC_REFERENCES_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_HDRS_ALL_EFF_B_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_HEADERS_ALL_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_LINES_ALL_EFF_B_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_LINES_ALL_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_LOT_SERIALS_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_SO_MAAS_MANUAL_PRICE_ADJ_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUSTMAINTAIN_TRX_DETAILS_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUSTMAINTAIN_TRX_DETAILS_TT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUSTMAINTAIN_TRX_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUSTMAINTAIN_TRX_TT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUSTMAINTAIN_WRITEOFF_RECS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUSTMAINTAIN_WRITEOFF_REC_TT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOM_RULES_TYPE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOM_RULES_TYPE_ARRAY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_AUTO_HOLDS_TYPE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_AUTO_HOLDS_TYPE_ARRAY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_DIST_TITLE_RIGHTS_ARRAY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_DIST_TITLE_RIGHTS_TYPE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_HOLDS_TYPE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_HOLDS_TYPE_ARRAY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_RELEASE_TYPE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_RELEASE_TYPE_ARRAY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_TT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MAAS_LINES_ALL_EFF_B_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MAAS_LINES_ALL_EFF_B_TT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MAAS_LINES_ALL_RT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MAAS_LINES_ALL_TT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MAPPING_VAL_TYPE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MAPPING_VAL_TYPE_ARRAY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_TBL_DATA.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_TBL_DATA_ARRAY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_PRE_RESERVATION_HDR_CRT_REC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_PRE_RESERVATION_HDR_CRT_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_PRE_RESERVATION_LINE_CRT_REC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_PRE_RESERVATION_LINE_CRT_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SAAS_DATA_SYNC_CONF_REC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SAAS_DATA_SYNC_CONF_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_VARCHAR_TBL_TYPE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\ACC_TYP_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DEPT_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EMP_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ADIST_RIGHTS_COUNTRYGROUP_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ARTRX_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUST_TRX_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_TRXMAINT_TRX_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_TRX_SESSION_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOM_RULES_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_SO_HOLDS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CLIENT_INFO_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUPS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_LINE_ACTIONS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_HEADERS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_LINES_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_HEADERS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_LINES_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DISTRIBUTION_MAINTENANCE_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_STG_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_FC_RPT_GRP_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_HOT_TITLES_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INTEGRATION_CONTROL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_LIFE_PLANNER_ID_S.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INTEGRATION_LOGS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INT_PARAMETERS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_EFF_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_HOLD_ID.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_RELEASE_ID.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHT_DETAILS_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_TRX_HEADER_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\LINE_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\SF_ASSIGN_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\SQ_LOT_NUMBER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\SQ_PAYMENTS_BATCH_ID.sql
@C:\Users\Mohammad Sattar\Desktop\april18\SQ_PAYMENTS_LINE_ID.sql
@C:\Users\Mohammad Sattar\Desktop\april18\SQ_RECEIPT_NUMBER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\TEMPLATE_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DEFAULT_DISTRIBUTION_CHANNEL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DISTRUBUTION_CHANNEL_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILYCODE_FORMAT_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_OWNER_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_CATEGORY2_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_GROUP_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_SUB_FORMAT_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_LOG_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_CRITERIA_UID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RES_RECORD_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SAAS_DATA_SYNC_RUNID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_ASSIGN_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_DIV_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAINTENANCE_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAPPING_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_SALES_REP_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_TERRITORY_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SF_ACCT_TYPE_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_UNASSIGNED_SALES_FORCE_TBL_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_XFACE_RUN_STATUS_ID_SEQ.sql
@C:\Users\Mohammad Sattar\Desktop\april18\ACCOUNTS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_CASH_RECEIPTS_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_INVOICE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_PAYMENT_SCHEDULES_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_PAYMENT_SCHEDULES_ALL_FULLSYNC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_RECEIVABLES_ACTIVITY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_KNOWN_HOSTS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_PRIVATE_KEYS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\CJM_CLAIMS_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\CRP1_ISBN.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DEPT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_FULFILL_LINES_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_FULFILL_LINES_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HEADERS_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HEADERS_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_VL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_INSTANCES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINES_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINES_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINE_STATUSES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_ORDER_ADDRESSES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_ORDER_TOTALS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGO_ITEM_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGP_SYSTEM_ITEMS_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGP_SYSTEM_ITEMS_B_050123.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGP_SYSTEM_ITEMS_B_BCKUP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EMP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_COMMON_LOOKUPS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOCUMENT_CATEGORIES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOCUMENT_ENTITIES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOC_CATEGORIES_TO_ENTITIES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_FLEX_VALUES_VL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_LOOKUP_VALUES_VL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_PROFILE_OPTIONS_VL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_PROFILE_OPTION_VALUES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_TERRITORIES_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ARTRX_ACTIVITY_PROCESS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ARTRX_WRITEOFF_RECORDS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUST_MAINTENANCE_ACTIVITY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_INVOCIE_DTLS_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_ARCHIVE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_HEADER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_LINES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_SCHEDULE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_TRXMAINT_STORE_SELECTION.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_TRXMAINT_TRXCODES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_TRX_MAINT_SESSION.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CODES_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOMER_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOM_RULES_BCKUP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOM_RULES_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_ITEMS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_LOOKUPS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_PROFILES_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_REGIONS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_SO_HOLDS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_SO_INFO_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_VALUE_SETS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CLIENT_INFO_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUPS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUPS_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUP_ASSOC_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUP_ASSOC_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_ATTACHMENTS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_LINE_ACTIONS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_HEADERS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_LINES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_HEADERS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_LINES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CUST_ACCOUNT_TYPE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_COMMON_LOOKUPS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_BISAC_EXTRACT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_BISAC_EXTRACT_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_BISAC_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CATALOGS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CATEGORIES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CATEGORIES_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CNTB_EXTRACT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CNTB_EXTRACT_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CNTB_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_COLLECTIONS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_COL_FAILED_REC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_COL_JSON_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_DISCOUNTS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_EXECUTION_TRACKER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_EXTRACT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_EXTRACT_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_FAILED_REC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_FORMAT_RANKS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_HOLIDAY_ITEMS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INTEGRATION_TRACKER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INVENTORY_EXTRACT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INVENTORY_EXTRACT_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INVENTORY_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INV_FAILED_REC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INV_JSON_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_JSON_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_EXTRACT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_EXTRACT_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_FAILED_REC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_JSON_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRODUCTS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRODUCTS_SKUS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_REPORT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_VALIDATION_RPT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDERS_JOB_TRACKER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_HEADER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_LINE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIGITAL_CONTENT_ITEMS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DISTRIBUTION_MAINTENANCE_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_COUNTRIES_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_COUNTRYGROUP_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_EXT_03042023.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_PREC_LEV_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGO_ITEM_ASSOCIATIONS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGO_ITEM_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGO_ITEM_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGO_ITEM_REVISION_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGO_ITEM_REVISION_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGO_ITEM_SUPPLIER_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGO_ITEM_SUPPLIER_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGO_STYLE_VARIANT_ATTR_VS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGP_ITEM_ATTACHMENTS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGP_ITEM_CATEGORIES_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGP_ITEM_RELATIONSHIPS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGP_ITEM_REVISIONS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGP_SYSTEM_ITEMS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGP_SYSTEM_ITEMS_INTERFACE2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGP_SYSTEM_ITEMS_INTERFACE3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EGP_TRADING_PARTNER_ITEMS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EXPECTED_RECEIPTS_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_FND_FLEX_VALUES_VL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INTEGRATION_CONTROL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_LOT_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_LOT_INT_PARAMETERS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_ONHAND_QUANTITIES_DETAIL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_TRANSACTIONS_ARCHIVE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_TRANSACTIONS_HEADER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_TRANSACTIONS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_TRANSACTIONS_LINES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ITEMS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ITEM_HOT_TITLES_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ORGANIZATION.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_CONVERSION.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_CONVERSION_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_CPM.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_CPM_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_CPM_STG_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INTEGRATION_LOGS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INT_PARAMETERS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PAM.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PAM_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PAM_STG_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PAT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PAT_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PAT_STG_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PBC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PBC_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PBC_STG_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PCA.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PCA_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PCA_STG_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PCC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PCC_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PCC_STG_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PEM.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PEM_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PEM_STG_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PRM.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PRM_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_PRM_STG_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_TEMPLATE_MAPPINGS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ATTACHMENT_JOB_TRACKER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_CHARGES_COMPS_FBDI.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_CHARGES_FBDI.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_COMMENTS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_DEBUG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HDRS_EFF_FBDI.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HEADERS_FBDI.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_EFF_FBDI.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_FBDI.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LOOKUP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_PAYMENT_TKN_FBDI.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_REPORT_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_SUBMIT_BATCHES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDER_SUBMIT_BATCHES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_CUSTOM_RULE_HOLD_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLES_HOLD_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLES_RELEASE_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MASS_UPDATE_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_COMMENT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_COMMENT_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_CONTROL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_CONTROL_TABLE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_DIST.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_DIST_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_GS1_DATA_TAGS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_HEADER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_HEADER_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_JOB_TRACKER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIPTO_SAN.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIP_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_EXT_03042022.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_EXT_05042023.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHT_DETAILS_EXT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHT_DETAILS_EXT_03042022.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHT_DETAILS_EXT_05042023.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHT_DETAILS_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_WMS_INV_TRX_HEADER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_WMS_INV_TRX_LOT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HR_OPERATING_UNITS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HTMLDB_PLAN_TABLE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUSTOMER_PROFILES_F.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCOUNTS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCT_SITES_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_SITE_USES_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_GEOGRAPHIES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_GEOGRAPHY_IDENTIFIERS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_LOCATIONS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_PARTIES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_PARTY_SITES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_LOT_NUMBERS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_ORG_PARAMETERS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_RESERVATIONS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_TRAN.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LISTS_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LIST_CHARGES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LIST_ITEMS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_BATCH_SOURCES_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_CUSTOMER_TRX_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_CUSTOMER_TRX_LINES_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_TERMS_VL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\TASK_TEST.sql
@C:\Users\Mohammad Sattar\Desktop\april18\TEST1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\TEST2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_ADDRESSES_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_BILLING_PLANS_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_CHARGES_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_CHARGE_COMPS_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_DOC_REFERENCES_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HDRS_ALL_EFF_B_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_LINES_ALL_EFF_B_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_LINES_ALL_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_LOT_SERIALS_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_MANUAL_PRICE_ADJ_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_PAYMENTS_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_SALES_CREDITS_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_TXN_ATTRIBUTES_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_PROJECTS_INT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DEFAULT_DISTRIBUTION_CHANNEL_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DISTRUBUTION_CHANNEL_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DIST_CHANNEL_PREC_LEV_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_EDI_PROFILE_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_EGB_SYSTEM_ITEM_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_EGP_ITEM_CATEGORIES_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILYCODE_FORMAT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_OWNER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_CATEGORY1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_CATEGORY2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_GROUP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_SUB_FORMAT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_LOT_NUMBERS_SYNC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_ONHAND_QUANTITIES_DETAIL_SYNC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_ORG_PARAMETERS_SYNC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_RESERVATIONS_SYNC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_TYPE_MAPPING_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_LIFE_PLANNER_ITEM_CATE_STG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_LOGS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_LOGS_CONFIG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_ADD_CRITERIA.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_ADD_CRITERIA_DETAIL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_HEADER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_HEADER_BKP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_HISTORY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_LINES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RESERVATION_LOT_NUM_CREATE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SAAS_DATA_SYNC_CONFIG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SAAS_DATA_SYNC_FILTERS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SAAS_DATA_SYNC_RUN.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_ASSIGN_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_DIV_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAINTENANCE_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAPPING_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_PREC_LEV_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_SALES_REP_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_TERRITORY_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SF_ACCT_TYPE_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SS_RELEASE_TYPE_TEMPLATE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SS_SHIPPING_SCHEDULE_TYPE_TEMPLATE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_UNASSIGNED_SALES_FORCE_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXTEST.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XX_HBG_ACCT_TYPE_HDR_EXT_TBL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\ZZHBG_RA_CUSTOMER_TRX_ALL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_DEBIT_MEMO_LINES_V.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_HEADER_V.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_OM_STATUS_TO_CX_V.sql
@C:\Users\Mohammad Sattar\Desktop\april18\UNIQUE_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK_SYSTEM_ORDER_ID.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_LINE_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CATEGORIES_STG_UK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ITEMS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_COUNTRIES_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_COUNTRYGROUP_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_FND_FLEX_VALUES_VL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ITEM_HOT_TITLES_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_CUSTOM_RULE_HOLD_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_VALUE_SETS_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_PRIVATE_KEYS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_ITEMS_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CODES_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOMER_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HEADERS_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINES_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_FULFILL_LINES_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINE_STATUSES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_VL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_COMMON_LOOKUPS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_FLEX_VALUES_VL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCOUNTS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_PARTY_SITES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_PROFILES_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_SO_HOLDS_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_SO_INFO_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_ORDER_TOTALS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_TERMS_VL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCT_SITES_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOM_RULES_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_REGIONS_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\TASK_TEST_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUPS_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUP_ASSOC_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_LOOKUPS_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK_OWNER.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK_CAT1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK_REPORTING_GRP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_RESERVATIONS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_ORG_PARAMETERS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_ONHAND_QUANTITIES_DETAIL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_LOT_NUMBERS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_PARTIES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGP_SYSTEM_ITEMS_B_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HEADERS_EFF_B_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_INSTANCES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_GEOGRAPHIES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_PROFILE_OPTION_VALUES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_GEOGRAPHY_IDENTIFIERS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_PROFILE_OPTIONS_VL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_ORG_PARAMETERS_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGO_ITEM_EFF_B_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_LOCATIONS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_SITE_USES_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUSTOMER_PROFILES_F_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\BRI_RA_CUSTOMER_TRX_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHT_DETAILS_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_EXT_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\BRI_RA_CUSTOMER_TRX_LINES_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_LOT_INT_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_ONHAND_QUANTITIES_DETAIL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TBL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DEFAULT_DISTRIBUTION_CHANNEL_TBL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK_CAT2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK_PUB.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK_IMPR.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK_INV_TRX_HEADER_ID.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_PAYMENT_SCHEDULES_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINES_EFF_B_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_FULFILL_LINES_EFF_B_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_B_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_TL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_CASH_RECEIPTS_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DOO_ORDER_ADDRESSES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_RESERVATIONS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_LOOKUP_VALUES_VL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LIST_CHARGES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LIST_ITEMS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LISTS_TL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EXPECTED_RECEIPTS_INT_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_SUBMIT_BATCHES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_LOT_INT_PARAMETERS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\CJM_CLAIMS_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INTEGRATION_LOGS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INTEGRATION_CONTROL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INT_PARAMETERS_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_BATCH_SOURCES_ALL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_HEADERS_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_LINES_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_HEADERS_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_LINES_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_LINE_ACTIONS_PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOCUMENT_ENTITIES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOC_CATEGORIES_TO_ENTITIES_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOCUMENT_CATEGORIES_VL_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_LOT_NUMBERS_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_TERRITORIES_B_PK.sql
@C:\Users\Mohammad Sattar\Desktop\april18\P1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\PK1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PEM_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PBC_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PCA_STG_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_REPORT_STG_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_INV_TRAN_LINES_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGO_ITEM_REVISION_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_HEADER_IDX_3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGP_SYSTEM_ITEMS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGP_ITEM_REVISIONS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGO_ITEM_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PRM_STG_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGO_ITEM_ASSOCIATIONS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_BISAC_EXTRACT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGP_ITEM_ATTACHMENTS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_CONTROL_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_FBDI_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HDRS_EFF_FBDI_IDX_3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N6.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_SCHE_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_BISAC_EXTRACT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_LINES_005.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORD_HDRS_ALL_EFF_B_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_EFF_FBDI_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_LINE_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PAM_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PEM_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_FAILED_REC_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCOUNTS_IDX_3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_HOLIDAY_ITEMS_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCOUNTS_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N8.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGP_ITEM_RELATIONSHIPS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGO_ITEM_ASSOCIATIONS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INVENTORY_EXTRACT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INV_JSON_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGP_SYSTEM_ITEMS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PBC_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CNTB_EXTRACT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGO_ITEM_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_HEADER_IDX_5.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_COL_FAILED_REC_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HEADERS_FBDI_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_REPORT_STG_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_PAYMENT_TKN_FBDI_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N7.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_ARCH_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGO_ITEM_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGO_ITEM_REVISION_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PBC_STG_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_TERRITORY_TBL_IDX.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_EFF_FBDI_IDX_4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HEADERS_FBDI_IDX_3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_CHARGES_FBDI_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_COMMENT_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_COL_JSON_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_CONTROL_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N5.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_EFF_FBDI_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_INV_TRANS_ARCHIVE_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HEADERS_FBDI_IDX_5.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_EXTRACT_IDX3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PAT_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI_IDX_4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGO_ITEM_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_DIV_TBL_IDX.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIP_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI_IDX_5.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIP_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIPTO_SAN_IDX_3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HDRS_EFF_FBDI_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_EXTRACT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_PIM_CONV_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_JSON_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_LINES_ALL_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_PIM_CPM_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_REPORT_IDX3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGO_ITEM_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PRM_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PRM_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PCA_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_BISAC_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_JSON_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INVENTORY_REPORT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_REPORT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGP_ITEM_REVISIONS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI_IDX_8.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_EXTRACT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_EXTRACT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGP_ITEM_REVISIONS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCT_SITES_ALL_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_HEADER_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGP_ITEM_ATTACHMENTS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGP_ITEM_RELATIONSHIPS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGP_ITEM_CATEGORIES_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_HEADER_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INV_FAILED_REC_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_HEADER_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_INTEGRATION_CONTROL_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGP_SYSTEM_ITEMS_B_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_REPORT_IDX4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGP_ITEM_CATEGORIES_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CATEGORIES_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_CHARGE_COMPS_INT_N2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_DIST_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PAM_STG_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_CHARGES_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGO_ITEM_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI_IDX_6.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGO_ITEM_REVISION_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_SCHE_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGP_ITEM_REVISIONS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PCC_STG_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGP_SYSTEM_ITEMS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HDRS_EFF_FBDI_IDX_4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PAM_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PRM_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_LINES_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGO_STYLE_VARIANT_ATTR_VS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_FAILED_REC_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_LINES_004.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGO_ITEM_ASSOCIATIONS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_EXTRACT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_INV_TRANS_ARCHIVE_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N10.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_REPORT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\ISBN_IDX.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_INV_TRAN_HEADER_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_VALIDATION_RPT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PAT_STG_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_EFF_FBDI_IDX_3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PBC_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_ADDRESSES_INT_N2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI_IDX_7.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGO_STYLE_VARIANT_ATTR_VS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_PIM_CPM_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_COL_FAILED_REC_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGO_ITEM_REVISION_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_COMMENTS_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_HEADER_IDX_4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_LINES_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PCC_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGO_ITEM_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_CHARGES_FBDI_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INVENTORY_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGP_ITEM_RELATIONSHIPS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_LINES_ALL_EFF_B_INT_N10.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PAT_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_HEADER_STG_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CATEGORIES_STG_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGP_ITEM_ATTACHMENTS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGO_ITEM_REVISION_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_STG_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_HEADER_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_HEADER_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_PAYMENT_TKN_FBDI_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_LINES_FBDI_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HDRS_EFF_FBDI_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_ADDRESSES_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORD_DOC_REFERENCES_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_CHARGES_COMPS_FBDI_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_DIST_STG_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIPTO_SAN_IDX_4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PCA_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_LINES_006.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_CHARGES_INT_N2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_INV_TRAN_HEADER_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRICE_FAILED_REC_IDX4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PEM_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGO_ITEM_REVISION_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_CHARGE_COMPS_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGO_ITEM_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_INV_TRANS_ARCHIVE_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIP_STG_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_INTEGRATION_CONTROL_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PCA_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_SITE_USES_ALL_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGO_ITEM_EFF_B_U1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_VALIDATION_RPT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PCC_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGP_TRADING_PARTNER_ITEMS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGO_ITEM_ASSOCIATIONS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCOUNTS_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCT_SITES_ALL_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGO_ITEM_EFF_B_U2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_INT_PARAMETERS_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INVENTORY_EXTRACT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_COMMENT_STG_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_ADDRESSES_FBDI_IDX_3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_DETAIL_DIST_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_FAILED_REC_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_COMMENTS_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGP_ITEM_RELATIONSHIPS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_BILLING_PLANS_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N9.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PAT_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_LINES_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGO_ITEM_REVISION_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORD_LINES_ALL_EFF_B_INT_N1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_SALES_REP_TBL_IDX.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PEM_STG_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PAM_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_CHARGES_COMPS_FBDI_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGP_SYSTEM_ITEMS_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_HEADER_IDX_3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_BISAC_REPORT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_PIM_CPM_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_HEADERS_ALL_INT_N4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_PARTY_SITES_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX4_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CNTB_EXTRACT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HEADERS_FBDI_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_AR_PAYM_ARCH_002.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_HEADERS_FBDI_IDX_4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXDOO_ORDER_ADDRESSES_INT_N3.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INV_FAILED_REC_IDX4.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX3_HBG_EGP_ITEM_CATEGORIES_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IND_HBG_PIM_CPM_STG_001.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_TL.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX2_HBG_EGO_ITEM_REVISION_INTF_EFF_B.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAINTENANCE_TBL_IDX.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_CONTROL_TABLE_IDX_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CNTB_REPORT_IDX1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_LINE_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX_HBG_PIM_PCC_003.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_SHIPTO_SAN_IDX_2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGP_ITEM_CATEGORIES_INTERFACE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CNTB_REPORT_IDX2.sql
@C:\Users\Mohammad Sattar\Desktop\april18\IDX1_HBG_EGP_ITEM_ATTACHMENTS_INTF.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DEPT_TRG1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EMP_TRG1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOM_RULES_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUPS_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_LINE_ACTIONS_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_HEADERS_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_LINES_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_HEADERS_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_LINES_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DISTRIBUTION_MAINTENANCE_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_STG_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_HOLD_ORDER_TEMP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_HOLD_ID_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_HOT_TITLE_RELEASE_ID_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHT_DETAILS_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DEFAULT_DISTRIBUTION_CHANNEL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DISTRUBUTION_CHANNEL_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_EGP_ITEM_CATEGORIES_INT_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILYCODE_FORMAT_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_OWNER_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_CATEGORY2_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_SUB_FORMAT_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_RES_PRE_RES_RECORD_ID_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_DIV_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAINTENANCE_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAPPING_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_SALES_REP_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_TERRITORY_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SF_ACCT_TYPE_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_UNASSIGNED_SALES_FORCE_TBL_TRG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\GET_EMPLOYEE_DETAILS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_HEADERS_CREATE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_CONVERSION_P.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TEST_TITLE_RIGHTS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\VALIDATE_RELEASE_ITEMS.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_KEYMGMT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_KEYMGMT_SECURITY.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUST_MAINTENANCE.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_TRXMAINT_OBJECT_TYPES.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CUSTOMER_MASTER_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CUSTOM_ORDERS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_FAMILY_CODE_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INVENTORY_TRANSACTIONS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ITEM_HOT_TITLES_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_LIFE_PLANNER_ITEM_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INTEGRATION_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PRE_RESERVATIONS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SALES_CREDIT_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SHIPPING_SCHEDULES_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_AUTO_HOLDS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_DIST_TITLE_RIGHTS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_DIST_TITLE_RIGHTS_PKG_NEW.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MASS_UPDATE_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_LOG_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_PAAS_EXTN_UTILS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_PRE_RESERVATIONS_PKG.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SAAS_DATA_SYNC.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XX_HBG_AR_CUST_MAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\ZZHBG_AR_CUST_MAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_KEYMGMT_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_KEYMGMT_SECURITY_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_CUST_MAINTENANCE_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CUSTOMER_MASTER_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CUSTOM_ORDERS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_FAMILY_CODE_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INVENTORY_TRANSACTIONS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ITEM_HOT_TITLES_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_LIFE_PLANNER_ITEM_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INTEGRATION_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PRE_RESERVATIONS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SALES_CREDIT_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SHIPPING_SCHEDULES_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_AUTO_HOLDS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_DIST_TITLE_RIGHTS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_DIST_TITLE_RIGHTS_PKG_NEW_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_MASS_UPDATE_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_LOG_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_PAAS_EXTN_UTILS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_PRE_RESERVATIONS_PKG_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SAAS_DATA_SYNC_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XX_HBG_AR_CUST_MAINT_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\ZZHBG_AR_CUST_MAINT_1.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_LOT_INT_PARAMETERS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAINTENANCE_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CATEGORIES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_JOB_TRACKER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_PARTY_SITES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_RESERVATIONS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_HEADERS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DEFAULT_DISTRIBUTION_CHANNEL_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_INSTANCES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EMP_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_STERLING_GS1_DATA_TAGS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_VALUE_SETS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGO_ITEM_EFF_B_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_PROFILE_OPTION_VALUES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ITEMS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HEADERS_EFF_B_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_HEADER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_DIV_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_LOOKUP_VALUES_VL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INT_PARAMETERS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCOUNTS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_CATEGORIES_STG_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CODES_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_LOOKUPS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INTEGRATION_CONTROL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOC_CATEGORIES_TO_ENTITIES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ITEM_HOT_TITLES_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_LOT_NUMBERS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_CASH_RECEIPTS_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_UNASSIGNED_SALES_FORCE_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\TASK_TEST_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_TERRITORY_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_PROFILE_OPTIONS_VL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_SITE_USES_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_OWNER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_FULFILL_LINES_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HEADERS_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_INTEGRATION_TRACKER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_ONHAND_QUANTITIES_DETAIL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_TERMS_VL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\CJM_CLAIMS_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_CUSTOMER_TRX_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_VALIDATION_RPT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_BATCH_SOURCES_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUST_ACCT_SITES_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CUST_ACCOUNT_TYPE_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PROCESS_ORDERS_SUBMIT_BATCHES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LIST_CHARGES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHTS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRODUCTS_SKUS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_ORDER_TOTALS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_LINE_ACTIONS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOMER_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_LINE_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_TITLE_RIGHT_DETAILS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_REGIONS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDERS_JOB_TRACKER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_INV_LOT_INT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUP_ASSOC_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOCUMENT_CATEGORIES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_DISTRUBUTION_CHANNEL_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_PRODUCTS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_VL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_RESERVATIONS_SYNC_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_HEADERS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\RA_CUSTOMER_TRX_LINES_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_RECEIVABLES_ACTIVITY_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SF_ACCT_TYPE_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_PARTIES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_ITEMS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_B_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_SO_HOLDS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_CUSTOM_RULES_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_GROUP_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINES_EFF_B_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_ORDER_ADDRESSES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_COLLECTIONS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_ORG_PARAMETERS_SYNC_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILYCODE_FORMAT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_PIM_INTEGRATION_LOGS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_SO_CUSTOM_RULE_HOLD_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_LINES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_INVOCIE_DTLS_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_EXPECTED_RECEIPTS_INT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_REPORTING_CATEGORY2_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_TERRITORIES_B_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINE_STATUSES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_DOCUMENT_ENTITIES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_EXECUTION_TRACKER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_FORMAT_RANKS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_ARTRX_ACTIVITY_PROCESS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ORDER_HEADER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_FLEX_VALUES_VL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AS_SFTP_PRIVATE_KEYS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_WMS_INV_TRX_HEADER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LISTS_TL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AR_PAYMENTS_LINES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_COUNTRY_GROUPS_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_SO_INFO_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_PAYMENT_SCHEDULES_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_SUB_FORMAT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_WMS_INV_TRX_LOT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DEPT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_LOCATIONS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_LOT_NUMBERS_SYNC_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\AR_PAYMENT_SCHEDULES_ALL_FULLSYNC_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_FND_FLEX_VALUES_VL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_COUNTRIES_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_GEOGRAPHY_IDENTIFIERS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_TYPE_MAPPING_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_FULFILL_LINES_EFF_B_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EGP_SYSTEM_ITEMS_B_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_AUTO_HOLD_PROFILES_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_HOLD_CODES_TL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CX_ITEMS_DISCOUNTS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_CUSTOMER_PROFILES_F_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_MAPPING_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_ASSIGN_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_SALES_REP_TBL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_DIST_RIGHTS_COUNTRYGROUP_EXT_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\FND_COMMON_LOOKUPS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_LINES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HZ_GEOGRAPHIES_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_INV_ONHAND_QUANTITIES_DETAIL_SYNC_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\QP_PRICE_LIST_ITEMS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\DOO_LINES_ALL_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\INV_ORG_PARAMETERS_CONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\EMP_REFCONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_LINE_ACTIONS_REFCONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_RULES_LINES_REFCONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\HBG_CO_TEMPLATE_LINES_REFCONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL_REFCONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_DIV_TBL_REFCONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_SALES_REP_TBL_REFCONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SALES_FORCE_TERRITORY_TBL_REFCONSTRAINT.sql
@C:\Users\Mohammad Sattar\Desktop\april18\XXHBG_SF_ACCT_TYPE_TBL_REFCONSTRAINT.sql
