--------------------------------------------------------
--  DDL for Table HBG_CX_ITEMS_HOLIDAY_ITEMS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CX_ITEMS_HOLIDAY_ITEMS" 
   (	"ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"DISPLAY_NAME" VARCHAR2(200 BYTE), 
	"IS_ACTIVE" VARCHAR2(5 BYTE), 
	"EXCLUDE_FROM_SITE_MAP" VARCHAR2(5 BYTE), 
	"ISBN" VARCHAR2(50 BYTE), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_CX_ITEMS_HOLIDAY_ITEMS" TO "RO_HBG_INTEGRATION";
