--------------------------------------------------------
--  DDL for Table HBG_PIM_INT_PARAMETERS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PIM_INT_PARAMETERS" 
   (	"PARAM_ID" NUMBER DEFAULT "HBG_INTEGRATION"."HBG_PIM_INT_PARAMETERS_SEQ"."NEXTVAL", 
	"PARAMETER_NAME" VARCHAR2(50 BYTE), 
	"PARAM_NUMBER1" NUMBER, 
	"PARAM_NUMBER2" NUMBER, 
	"PARAM_CHAR1" VARCHAR2(250 BYTE), 
	"PARAM_CHAR2" VARCHAR2(250 BYTE), 
	"PARAM_DATE1" TIMESTAMP (6), 
	"PARAM_DATE2" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
