--------------------------------------------------------
--  DDL for Table HBG_ORGANIZATION
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_ORGANIZATION" 
   (	"ORGANIZATION" VARCHAR2(200 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(200 BYTE), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(200 BYTE), 
	"DEFAULT_ACCOUNT_TYPE" VARCHAR2(200 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(200 BYTE), 
	"INSTANCEID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"ORGANIZATION_CODE" VARCHAR2(200 BYTE), 
	"ACCOUNT" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_ORGANIZATION" TO "RO_HBG_INTEGRATION";
