--------------------------------------------------------
--  DDL for Table HBG_CLIENT_INFO_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CLIENT_INFO_TBL" 
   (	"CLIENT_INFO_ID" NUMBER, 
	"CUST_OWNER" VARCHAR2(255 BYTE), 
	"OWNER_DESCRIPTION" VARCHAR2(255 BYTE), 
	"ACCOUNT_TYPE" VARCHAR2(255 BYTE), 
	"ACCOUNT_TYPE_DESCRIPTION" VARCHAR2(2000 BYTE), 
	"DISCOUNT" NUMBER, 
	"LOOKUP1" VARCHAR2(255 BYTE), 
	"LOOKUP2" VARCHAR2(255 BYTE), 
	"LOOKUP3" VARCHAR2(255 BYTE), 
	"CUSTOMER_SINCE" DATE, 
	"LAST_ACTIVITY" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"DEFAULT_ACCOUNT_TYPE" VARCHAR2(255 BYTE), 
	"DEFAULT_ACCOUNT_TYPE_OWNERS" VARCHAR2(255 BYTE), 
	"OPERATION_ACCOUNT_TYPE" VARCHAR2(300 BYTE), 
	"REPORTING_GROUP" VARCHAR2(300 BYTE), 
	"REPORTING_GROUP_DESCRIPTION" VARCHAR2(300 BYTE), 
	"CATEGORY1" VARCHAR2(300 BYTE), 
	"CATEGORY1_DESCRIPTION" VARCHAR2(255 BYTE), 
	"CATEGORY2" VARCHAR2(255 BYTE), 
	"CATEGORY2_DESCRIPTION" VARCHAR2(300 BYTE), 
	"CUST_FORMAT" VARCHAR2(255 BYTE), 
	"FORMAT_DESCRIPTION" VARCHAR2(255 BYTE), 
	"SUB_FORMAT" VARCHAR2(255 BYTE), 
	"SUB_FORMAT_DESCRIPTION" VARCHAR2(255 BYTE), 
	"CUSTOMER_ACCOUNT" VARCHAR2(300 BYTE), 
	"CUST_ACCOUNT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_CLIENT_INFO_TBL" TO "RO_HBG_INTEGRATION";
