--------------------------------------------------------
--  DDL for Table HBG_PROCESS_ORDERS_CHARGES_FBDI
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_CHARGES_FBDI" 
   (	"SOURCE_TRANSACTION_ID" VARCHAR2(50 BYTE), 
	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(30 BYTE), 
	"SOURCE_TRANSACTION_LINE_ID" VARCHAR2(50 BYTE), 
	"SOURCE_TRANSACTION_SCHEDULE_ID" VARCHAR2(50 BYTE), 
	"SOURCE_CHARGE_ID" VARCHAR2(120 BYTE), 
	"CHARGE_DEFINITION_CODE" VARCHAR2(30 BYTE), 
	"CHARGE_DEFINITION" VARCHAR2(80 BYTE), 
	"CHARGE_TYPE_CODE" VARCHAR2(30 BYTE), 
	"CHARGE_TYPE" VARCHAR2(80 BYTE), 
	"CHARGE_SUBTYPE_CODE" VARCHAR2(30 BYTE), 
	"CHARGE_SUBTYPE" VARCHAR2(80 BYTE), 
	"SEQUENCE_NUMBER" NUMBER(9,0), 
	"PRICE_TYPE_CODE" VARCHAR2(30 BYTE), 
	"PRICE_TYPE" VARCHAR2(240 BYTE), 
	"PRICED_QUANTITY" NUMBER, 
	"PRICED_QUANTITY_UOM_CODE" VARCHAR2(3 BYTE), 
	"PRICED_QUANTITY_UOM" VARCHAR2(25 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE), 
	"APPLY_TO" VARCHAR2(30 BYTE), 
	"ROLLUP_FLAG" VARCHAR2(1 BYTE), 
	"CHARGE_CURRENCY_CODE" VARCHAR2(1000 BYTE), 
	"CHARGE_CURRENCY_NAME" VARCHAR2(1000 BYTE), 
	"PRICE_PERIODICITY_CODE" VARCHAR2(30 BYTE), 
	"GSA_UNIT_PRICE" NUMBER, 
	"TRANSACTIONAL_CURRENCY_CODE" VARCHAR2(1000 BYTE), 
	"TRANSACTIONAL_UOM_CODE" VARCHAR2(3 BYTE), 
	"AVERAGE_UNIT_SELLING_PRICE" NUMBER, 
	"TIER_APPLIES_TO" VARCHAR2(30 BYTE), 
	"TIER_APPLIES_TO_NAME" VARCHAR2(80 BYTE), 
	"BLOCK_ALLOWANCE" NUMBER, 
	"BLOCK_SIZE" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(360 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(360 BYTE), 
	"STATUS" VARCHAR2(360 BYTE), 
	"ERROR_MSG" VARCHAR2(1000 BYTE), 
	"GIS_ID" NUMBER, 
	"SOURCE_SYSTEM" VARCHAR2(20 BYTE), 
	"SBI_UUID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
