--------------------------------------------------------
--  DDL for Table HBG_PROCESS_ORDERS_HDRS_EFF_FBDI
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_HDRS_EFF_FBDI" 
   (	"SOURCE_TRANSACTION_ID" VARCHAR2(50 BYTE), 
	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(30 BYTE), 
	"CONTEXT_CODE" VARCHAR2(80 BYTE), 
	"ATTRIBUTE_CHAR1" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR2" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR3" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR4" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR5" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR6" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR7" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR8" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR9" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR10" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR11" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR12" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR13" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR14" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR15" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR16" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR17" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR18" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR19" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_CHAR20" VARCHAR2(150 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_DATE1" VARCHAR2(10 BYTE), 
	"ATTRIBUTE_DATE2" VARCHAR2(10 BYTE), 
	"ATTRIBUTE_DATE3" VARCHAR2(10 BYTE), 
	"ATTRIBUTE_DATE4" VARCHAR2(10 BYTE), 
	"ATTRIBUTE_DATE5" VARCHAR2(10 BYTE), 
	"ATTRIBUTE_TIMESTAMP1" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_TIMESTAMP2" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_TIMESTAMP3" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_TIMESTAMP4" VARCHAR2(30 BYTE), 
	"ATTRIBUTE_TIMESTAMP5" VARCHAR2(30 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(360 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(360 BYTE), 
	"STATUS" VARCHAR2(360 BYTE), 
	"ERROR_MSG" VARCHAR2(1000 BYTE), 
	"GIS_ID" NUMBER, 
	"SOURCE_SYSTEM" VARCHAR2(20 BYTE), 
	"SBI_UUID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_HDRS_EFF_FBDI" TO "RO_HBG_INTEGRATION";
