--------------------------------------------------------
--  DDL for Table HBG_INV_TRANSACTIONS_LINES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_INV_TRANSACTIONS_LINES" 
   (	"SOURCE_HEADER_ID" NUMBER, 
	"SOURCE_LINE_ID" NUMBER, 
	"ISBN" VARCHAR2(255 BYTE), 
	"TRANSACTION_QUANTITY" NUMBER, 
	"TRANSACTION_UOM" VARCHAR2(100 BYTE), 
	"TRANSACTION_REFERENCE" VARCHAR2(255 BYTE), 
	"SUBINVENTORY" VARCHAR2(255 BYTE), 
	"TRANSFER_SUBINVENTORY" VARCHAR2(255 BYTE), 
	"REASON_NAME" VARCHAR2(255 BYTE), 
	"LOT_NUMBER" VARCHAR2(255 BYTE), 
	"TRANSACTION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
