--------------------------------------------------------
--  DDL for Table HBG_EGO_STYLE_VARIANT_ATTR_VS_INTF
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_EGO_STYLE_VARIANT_ATTR_VS_INTF" 
   (	"ATTRIBUTE_GROUP_CODE" VARCHAR2(320 BYTE), 
	"ATTRIBUTE_CODE" VARCHAR2(120 BYTE), 
	"VALUE_SET_CODE" VARCHAR2(60 BYTE), 
	"BATCH_ID" NUMBER(18,0), 
	"BATCH_NUMBER" VARCHAR2(40 BYTE), 
	"ITEM_NUMBER" VARCHAR2(300 BYTE), 
	"SOURCE_SYSTEM_CODE" VARCHAR2(30 BYTE), 
	"SOURCE_SYSTEM_REFERENCE" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"ERROR_TEXT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_EGO_STYLE_VARIANT_ATTR_VS_INTF" TO "RO_HBG_INTEGRATION";
