--------------------------------------------------------
--  DDL for Table HBG_CO_TEMPLATE_HEADERS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CO_TEMPLATE_HEADERS" 
   (	"TEMPLATE_ID" NUMBER(*,0) DEFAULT "HBG_INTEGRATION"."TEMPLATE_ID_SEQ"."NEXTVAL", 
	"TEMPLATE_NAME" VARCHAR2(100 BYTE), 
	"TEMPLATE_DESCRIPTION" VARCHAR2(255 BYTE), 
	"CUST_ACCOUNT_ID" NUMBER, 
	"OWNER_CODE" VARCHAR2(25 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ACCOUNT_NUMBER" VARCHAR2(200 BYTE), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(200 BYTE), 
	"OWNER_NAME" VARCHAR2(200 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_DATE" DATE, 
	"ENTERED_BY" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
