--------------------------------------------------------
--  DDL for Table HBG_CO_ATTACHMENTS_EXT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CO_ATTACHMENTS_EXT" 
   (	"ORDER_NUMBER" VARCHAR2(200 BYTE), 
	"SOURCE_ORDER_ID" VARCHAR2(200 BYTE), 
	"SOURCE_LINE_ID" VARCHAR2(200 BYTE), 
	"RULE_ID" NUMBER, 
	"ATTRIBUTE_CHAR1" VARCHAR2(600 BYTE), 
	"DESTINATION_ACCOUNT" VARCHAR2(255 BYTE), 
	"PARTY_SITE_NUMBER" VARCHAR2(120 BYTE), 
	"SEQUENCE" NUMBER, 
	"LINE_ACTION_ID" NUMBER, 
	"TEMPLATE_LEVEL" VARCHAR2(200 BYTE), 
	"HOLD_LEVEL" VARCHAR2(100 BYTE), 
	"HOLD_NAME" VARCHAR2(100 BYTE), 
	"TEMPLATE_NAME" VARCHAR2(100 BYTE), 
	"TEMPLATE_LINE_SEQ" NUMBER, 
	"CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"INSTRUCTIONS_TEXT" VARCHAR2(2000 BYTE), 
	"COMPARE_STRING" VARCHAR2(442 BYTE), 
	"STATUS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
