--------------------------------------------------------
--  DDL for Table HBG_CX_ITEMS_PRODUCTS_SKUS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CX_ITEMS_PRODUCTS_SKUS" 
   (	"PARENTID" VARCHAR2(50 BYTE), 
	"SKU_ID" VARCHAR2(50 BYTE), 
	"ACTIVE" VARCHAR2(5 BYTE), 
	"DISPLAY_NAME" VARCHAR2(2000 BYTE), 
	"LONG_DESCRIPTION" CLOB, 
	"AUTHOR_NAME" VARCHAR2(1000 BYTE), 
	"IMPRINT" VARCHAR2(100 BYTE), 
	"PUBLISHER" VARCHAR2(200 BYTE), 
	"PUBLICATION_DATE" VARCHAR2(100 BYTE), 
	"SERIES" VARCHAR2(200 BYTE), 
	"SERIES_NUMBER" VARCHAR2(30 BYTE), 
	"SUB_PRODUCT" VARCHAR2(100 BYTE), 
	"SUB_TITLE" VARCHAR2(2000 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP" VARCHAR2(200 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(5 BYTE), 
	"RANK_VAL" NUMBER, 
	"AUTHOR_LIST" VARCHAR2(4000 BYTE), 
	"EDITION" VARCHAR2(200 BYTE), 
	"EXTERNAL_IMPRINT" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"PUB_STATUS" VARCHAR2(20 BYTE), 
	"FORMAT" VARCHAR2(200 BYTE), 
	"CUSTOMER_SPECIFIC_CODE" VARCHAR2(20 BYTE), 
	"CUSTOMER_SPECIFIC_DESC" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("LONG_DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_CX_ITEMS_PRODUCTS_SKUS" TO "RO_HBG_INTEGRATION";
