--------------------------------------------------------
--  DDL for Table HBG_PROCESS_ORDERS_COMMENTS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_COMMENTS" 
   (	"SOURCE_TRANSACTION_ID" VARCHAR2(50 BYTE), 
	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(30 BYTE), 
	"DATA_TYPE_CODE" VARCHAR2(20 BYTE), 
	"FILENAME" VARCHAR2(200 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CATEGORY_NAME" VARCHAR2(10 BYTE), 
	"CONTENT_TYPE" VARCHAR2(50 BYTE), 
	"UPLOADED_TEXT" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(360 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(360 BYTE), 
	"STATUS" VARCHAR2(360 BYTE), 
	"ERROR_MSG" VARCHAR2(1000 BYTE), 
	"SOURCE_SYSTEM" VARCHAR2(20 BYTE), 
	"BATCH_ID" VARCHAR2(50 BYTE), 
	"RESPONSE" CLOB, 
	"COMMENT_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("RESPONSE") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
