--------------------------------------------------------
--  Constraints for Table HBG_CO_RULES_HEADERS
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."HBG_CO_RULES_HEADERS" ADD CONSTRAINT "HBG_CO_RULES_HEADERS_PK1" PRIMARY KEY ("RULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
