--------------------------------------------------------
--  DDL for Sequence HBG_PROCESS_ORDERS_ADDRESSES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_ADDRESSES_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 601 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
