--------------------------------------------------------
--  DDL for Sequence HBG_SO_HOT_TITLE_HOLD_ID
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."HBG_SO_HOT_TITLE_HOLD_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 71141 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
