--------------------------------------------------------
--  DDL for Table HBG_AUTO_HOLD_SO_INFO_EXT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AUTO_HOLD_SO_INFO_EXT" 
   (	"SOURCE_ORDER_SYSTEM" VARCHAR2(100 BYTE), 
	"SOURCE_ORDER_ID" VARCHAR2(100 BYTE), 
	"ORDER_NUMBER" VARCHAR2(200 BYTE), 
	"SO_HEADER_STATUS" VARCHAR2(200 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(255 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(255 BYTE), 
	"SOURCE_LINE_ID" VARCHAR2(100 BYTE), 
	"SOURCE_ORDER_LINE_NUM" VARCHAR2(200 BYTE), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(255 BYTE), 
	"INVENTORY_ORGANIZATION_ID" NUMBER, 
	"FULFILLMENT_LINE_NUM" VARCHAR2(255 BYTE), 
	"QUANTITY" NUMBER, 
	"CANCELLED_QTY" NUMBER, 
	"UNIT_LIST_PRICE" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER, 
	"ORDER_LINE_AMOUNT" NUMBER, 
	"SHIP_TO" VARCHAR2(255 BYTE), 
	"SO_LINE_STATUS" VARCHAR2(255 BYTE), 
	"FULFILL_LINE_STATUS" VARCHAR2(255 BYTE), 
	"FULFILL_LINE_ID" NUMBER, 
	"ORDER_AMOUNT" NUMBER, 
	"PAYMENT_TERMS" VARCHAR2(255 BYTE), 
	"CREDIT_REFERENCE_NUM" VARCHAR2(255 BYTE), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"AMT_EXCD_HOLD_FLAG" VARCHAR2(255 BYTE), 
	"OIC_RUN_ID" NUMBER, 
	"STATUS" VARCHAR2(200 BYTE), 
	"STATUS_MESSAGE" CLOB, 
	"ORDERED_DATE" DATE, 
	"ORDER_TYPE" VARCHAR2(255 BYTE), 
	"OPEN_FLAG" VARCHAR2(10 BYTE), 
	"CANCELED_FLAG" VARCHAR2(255 BYTE), 
	"GIFT_REVIEW_HOLD_FLAG" VARCHAR2(255 BYTE), 
	"OPEN_CC_AMT" NUMBER, 
	"ACCOUNT_STATUS" VARCHAR2(255 BYTE), 
	"PREPAID_HOLD_FLAG" VARCHAR2(20 BYTE), 
	"ORGANIZATION_ID" NUMBER, 
	"CUST_ACCOUNT_ID" NUMBER, 
	"CUST_ACCT_SITE_ID" NUMBER, 
	"ONE_TIME_ADDRESS_STATE" VARCHAR2(255 BYTE), 
	"ONE_TIME_ADDRESS_COUNTRY" VARCHAR2(255 BYTE), 
	"FINAL_DESTINATION_COUNTRY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("STATUS_MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_AUTO_HOLD_SO_INFO_EXT" TO "RO_HBG_INTEGRATION";
