--------------------------------------------------------
--  DDL for Index IDX2_HBG_EGO_ITEM_ASSOCIATIONS_INTF
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."IDX2_HBG_EGO_ITEM_ASSOCIATIONS_INTF" ON "HBG_INTEGRATION"."HBG_EGO_ITEM_ASSOCIATIONS_INTF" ("ORGANIZATION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
