--------------------------------------------------------
--  DDL for Table XXDOO_ORDER_CHARGE_COMPS_INT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXDOO_ORDER_CHARGE_COMPS_INT" 
   (	"SOURCE_TRANSACTION_ID" VARCHAR2(200 BYTE), 
	"SOURCE_MPA_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(120 BYTE), 
	"SOURCE_TRANSACTION_LINE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_SCHEDULE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_CHARGE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_CHARGE_COMPONENT_ID" VARCHAR2(200 BYTE), 
	"SEQUENCE_NUMBER" NUMBER, 
	"SOURCE_PARENT_CHARGE_COMP_ID" VARCHAR2(200 BYTE), 
	"CHARGE_CURRENCY_CODE" VARCHAR2(4000 BYTE), 
	"CHARGE_CURRENCY_NAME" VARCHAR2(4000 BYTE), 
	"CHARGE_CURRENCY_EXT_AMOUNT" NUMBER, 
	"CHARGE_CURRENCY_UNIT_PRICE" NUMBER, 
	"HEADER_CURRENCY_CODE" VARCHAR2(4000 BYTE), 
	"HEADER_CURRENCY_NAME" VARCHAR2(4000 BYTE), 
	"HEADER_CURRENCY_EXT_AMOUNT" NUMBER, 
	"HEADER_CURRENCY_UNIT_PRICE" NUMBER, 
	"PRICE_ELEMENT_CODE" VARCHAR2(120 BYTE), 
	"PRICE_ELEMENT" VARCHAR2(960 BYTE), 
	"PRICE_ELEMENT_USAGE_CODE" VARCHAR2(120 BYTE), 
	"PRICE_ELEMENT_USAGE" VARCHAR2(960 BYTE), 
	"ROLLUP_FLAG" VARCHAR2(4 BYTE), 
	"TRANSACTIONAL_CURRENCY_CODE" VARCHAR2(4000 BYTE), 
	"EXPLANATION" VARCHAR2(4000 BYTE), 
	"CHARGE_CURR_DURATION_EXT_AMT" NUMBER, 
	"HEADER_CURR_DURATION_EXT_AMT" NUMBER, 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"LOAD_REQUEST_ID" NUMBER, 
	"BATCH_ID" NUMBER, 
	"VALIDATION_BITSET" NUMBER, 
	"INTERFACE_RUN_ID" NUMBER, 
	"ICS_RUN_ID" NUMBER, 
	"SAAS_PROCESS_ID" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(4000 BYTE), 
	"FILE_NAME" VARCHAR2(240 BYTE), 
	"ICS_BATCH_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXDOO_ORDER_CHARGE_COMPS_INT" TO "RO_HBG_INTEGRATION";
