--------------------------------------------------------
--  DDL for Table XXDOO_ORDER_SALES_CREDITS_INT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXDOO_ORDER_SALES_CREDITS_INT" 
   (	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(120 BYTE), 
	"SOURCE_TRANSACTION_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_LINE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_SCHEDULE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TXN_SALES_CREDIT_ID" VARCHAR2(200 BYTE), 
	"SALES_PERSON_ID" NUMBER, 
	"SALES_PERSON" VARCHAR2(1440 BYTE), 
	"LOAD_REQUEST_ID" NUMBER, 
	"SALES_CREDIT_TYPE_CODE" VARCHAR2(4000 BYTE), 
	"SALES_CREDIT_TYPE_REFERENCE" VARCHAR2(4000 BYTE), 
	"PERCENT" NUMBER, 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"BATCH_ID" NUMBER, 
	"INTERFACE_RUN_ID" NUMBER, 
	"ICS_RUN_ID" NUMBER, 
	"SAAS_PROCESS_ID" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(4000 BYTE), 
	"FILE_NAME" VARCHAR2(240 BYTE), 
	"ICS_BATCH_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXDOO_ORDER_SALES_CREDITS_INT" TO "RO_HBG_INTEGRATION";
