--------------------------------------------------------
--  DDL for Table XXHBG_SS_SHIPPING_SCHEDULE_TYPE_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_SS_SHIPPING_SCHEDULE_TYPE_TEMPLATE" 
   (	"ADD_ITEMS_AUTOMATICALLY" VARCHAR2(20 BYTE), 
	"REMOVE_ITEMS_AUTOMATICALLY" VARCHAR2(20 BYTE), 
	"ON_SALE_DATE_EDITABLE" VARCHAR2(20 BYTE), 
	"ON_SALE_DATE_REQUIRED" VARCHAR2(20 BYTE), 
	"RELEASE_DATE_EDITABLE" VARCHAR2(20 BYTE), 
	"RELEASE_DATE_REQUIRED" VARCHAR2(20 BYTE), 
	"RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CUTOFF_DATE_EDITABLE" VARCHAR2(20 BYTE), 
	"CUTOFF_DATE_REQUIRED" VARCHAR2(20 BYTE), 
	"CUTOFF_DATE_SUBTRACT_FROM_RELEASE_DATE" NUMBER, 
	"CLEANUP_RELEASE_DATE_EDITABLE" VARCHAR2(20 BYTE), 
	"CLEANUP_RELEASE_DATE_REQUIRED" VARCHAR2(20 BYTE), 
	"CLEANUP_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"SHIPPING_SCHEDULE_TYPE" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
