--------------------------------------------------------
--  DDL for Sequence XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
