--------------------------------------------------------
--  DDL for Table XXHBG_FAMILY_CODE_REPORTING_CATEGORY1
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_CATEGORY1" 
   (	"CATEGORY1_ID" NUMBER, 
	"CATEGORY1_CODE" VARCHAR2(20 BYTE), 
	"CATEGORY1_NAME" VARCHAR2(200 BYTE), 
	"CATEGORY1_ABBR" VARCHAR2(200 BYTE), 
	"RETURNABLE_GRACE_DAYS" NUMBER, 
	"ACTIVE_IND" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP_ID" NUMBER, 
	"PUB_ID" NUMBER, 
	"COMPANY_CODE" VARCHAR2(200 BYTE), 
	"OSD_IND" VARCHAR2(10 BYTE), 
	"PARTIAL_SHIP_IND" VARCHAR2(10 BYTE), 
	"PARTIAL_SHIP_THRESHOLD" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_CATEGORY1" TO "RO_HBG_INTEGRATION";
