--------------------------------------------------------
--  Constraints for Table XXHBG_INV_ORG_PARAMETERS_SYNC
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_INV_ORG_PARAMETERS_SYNC" ADD CONSTRAINT "INV_ORG_PARAMETERS_PK" PRIMARY KEY ("ORGANIZATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
