--------------------------------------------------------
--  DDL for Table XXHBG_SS_RELEASE_TYPE_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_SS_RELEASE_TYPE_TEMPLATE" 
   (	"RELEASE_TYPE" VARCHAR2(20 BYTE), 
	"RES_IMMEDIATELY_OR_ACCORDING_TO_DELIVERY_PROFILE_RELEASE_DATES" VARCHAR2(20 BYTE), 
	"MAKE_IP_ON_RELEASE" VARCHAR2(20 BYTE), 
	"OVERRIDE_SMALL_PACK" VARCHAR2(20 BYTE), 
	"RUSH" VARCHAR2(20 BYTE), 
	"CATEGORY_0_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_0_MAB_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_1_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_1_MAB_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_2_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_2_MAB_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_3_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_3_MAB_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_4_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_4_MAB_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_5_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_5_MAB_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_6_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CATEGORY_6_MAB_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
