--------------------------------------------------------
--  DDL for Table XXHBG_RES_PRE_RESERVATION_ADD_CRITERIA_DETAIL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_ADD_CRITERIA_DETAIL" 
   (	"CRITERIA_UID" NUMBER, 
	"ORDER_NUMBER" NUMBER, 
	"RELEASE_DATE" DATE, 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"PURCHASE_ORDER_NUMBER" NUMBER, 
	"WORK_ORDER_NUMBER" NUMBER, 
	"ORGANIZATION_CODE" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(200 BYTE), 
	"ACCOUNT_TYPE" VARCHAR2(20 BYTE), 
	"ACCOUNT_TYPE_NAME" VARCHAR2(200 BYTE), 
	"BILL_TO_CODE" NUMBER, 
	"BILL_TO_NAME" VARCHAR2(200 BYTE), 
	"SHIP_TO_CODE" NUMBER, 
	"SHIP_TO_NAME" VARCHAR2(200 BYTE), 
	"SALE_TYPE" VARCHAR2(200 BYTE), 
	"OFFER_CODE" NUMBER, 
	"OVERRIDE_HOT_TITLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_ADD_CRITERIA_DETAIL" TO "RO_HBG_INTEGRATION";
