--------------------------------------------------------
--  DDL for Sequence XXHBG_UNASSIGNED_SALES_FORCE_TBL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_UNASSIGNED_SALES_FORCE_TBL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
