--------------------------------------------------------
--  DDL for Table XXHBG_INV_TYPE_MAPPING_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_INV_TYPE_MAPPING_TBL" 
   (	"INV_ID" NUMBER(*,0) DEFAULT "HBG_INTEGRATION"."INV_ID_SEQ"."NEXTVAL", 
	"INVENTORY_TYPE" VARCHAR2(255 BYTE), 
	"INVENTORY_TYPE_PREFERENCE" VARCHAR2(255 BYTE), 
	"OWNER" VARCHAR2(255 BYTE), 
	"OWNER_DESCRIPTION" VARCHAR2(255 BYTE), 
	"REPORTING_GROUP" VARCHAR2(255 BYTE), 
	"REPORTING_GROUP_DESCRIPTION" VARCHAR2(255 BYTE), 
	"CATEGORY_1" VARCHAR2(255 BYTE), 
	"CATEGORY_1_DESCRIPTION" VARCHAR2(255 BYTE), 
	"CATEGORY_2" VARCHAR2(255 BYTE), 
	"CATEGORY_2_DESCRIPTION" VARCHAR2(255 BYTE), 
	"FORMAT" VARCHAR2(255 BYTE), 
	"FORMAT_DESCRIPTION" VARCHAR2(255 BYTE), 
	"SUB_FORMAT" VARCHAR2(255 BYTE), 
	"SUB_FORMAT_DESCRIPTION" VARCHAR2(255 BYTE), 
	"NOTES" VARCHAR2(255 BYTE), 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_DATE" DATE, 
	"PARTY_NUMBER" VARCHAR2(200 BYTE), 
	"CUST_ACCOUNT_ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
