--------------------------------------------------------
--  DDL for Table DOO_HOLD_CODES_VL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."DOO_HOLD_CODES_VL" 
   (	"HOLD_CODE_ID" NUMBER, 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"HOLD_CODE" VARCHAR2(120 BYTE), 
	"HOLD_NAME" VARCHAR2(960 BYTE), 
	"HOLD_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"SET_ID" NUMBER, 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"GENERAL_HOLD_FLAG" VARCHAR2(4 BYTE), 
	"SYSTEM_FLAG" VARCHAR2(4 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"ORCHESTRATION_APPLICATION_ID" NUMBER, 
	"APPLY_HOLD_ROLE_ELIGIBILITY" VARCHAR2(4 BYTE), 
	"RELEASE_HOLD_ROLE_ELIGIBILITY" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."DOO_HOLD_CODES_VL" TO "RO_HBG_INTEGRATION";
