--------------------------------------------------------
--  DDL for Type DOO_SO_MAAS_CHARGES_RT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."DOO_SO_MAAS_CHARGES_RT" FORCE AS OBJECT
(
    SOURCE_TRANSACTION_ID            VARCHAR2 (200),
    PRICE_PERIODICITY                VARCHAR2 (100),
    APPLY_TO_NAME                    VARCHAR2 (320),
    SOURCE_TRANSACTION_SYSTEM        VARCHAR2 (120),
    SOURCE_TRANSACTION_LINE_ID       VARCHAR2 (200),
    SOURCE_TRANSACTION_SCHEDULE_ID   VARCHAR2 (200),
    SOURCE_CHARGE_ID                 VARCHAR2 (200),
    CHARGE_DEFINITION_CODE           VARCHAR2 (120),
    CHARGE_DEFINITION                VARCHAR2 (320),
    CHARGE_TYPE_CODE                 VARCHAR2 (120),
    CHARGE_TYPE                      VARCHAR2 (320),
    CHARGE_SUBTYPE_CODE              VARCHAR2 (120),
    CHARGE_SUBTYPE                   VARCHAR2 (320),
    SEQUENCE_NUMBER                  NUMBER,
    PRICE_TYPE_CODE                  VARCHAR2 (120),
    PRICE_TYPE                       VARCHAR2 (960),
    PRICED_QUANTITY                  NUMBER,
    PRICED_QUANTITY_UOM_CODE         VARCHAR2 (12),
    PRICED_QUANTITY_UOM              VARCHAR2 (100),
    PRIMARY_FLAG                     VARCHAR2 (4),
    APPLY_TO                         VARCHAR2 (120),
    ROLLUP_FLAG                      VARCHAR2 (4),
    CHARGE_CURRENCY_CODE             VARCHAR2 (4000),
    CHARGE_CURRENCY_NAME             VARCHAR2 (4000),
    PRICE_PERIODICITY_CODE           VARCHAR2 (120),
    GSA_UNIT_PRICE                   NUMBER,
    TRANSACTIONAL_CURRENCY_CODE      VARCHAR2 (4000),
    TRANSACTIONAL_UOM_CODE           VARCHAR2 (12),
    AVERAGE_UNIT_SELLING_PRICE       NUMBER,
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_CHARGES_RT" RETURN SELF AS RESULT
);
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "HBG_INTEGRATION"."DOO_SO_MAAS_CHARGES_RT" 
AS
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_CHARGES_RT"
        RETURN SELF AS RESULT
    AS
    BEGIN
        RETURN;
    END;
END;

/
