--------------------------------------------------------
--  DDL for Table DOO_HOLD_CODES_B
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."DOO_HOLD_CODES_B" 
   (	"HOLD_CODE_ID" NUMBER, 
	"ORCHESTRATION_APPLICATION_ID" NUMBER, 
	"SET_ID" NUMBER, 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"HOLD_CODE" VARCHAR2(120 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"GENERAL_HOLD_FLAG" VARCHAR2(4 BYTE), 
	"SYSTEM_FLAG" VARCHAR2(4 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR1" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR2" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR3" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR4" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR5" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR6" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR7" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR8" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR9" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR10" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR11" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR12" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR13" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR14" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR15" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR16" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR17" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR18" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR19" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR20" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_TIMESTAMP1" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP2" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP3" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP4" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP5" TIMESTAMP (6), 
	"SEED_DATA_SOURCE" VARCHAR2(2048 BYTE), 
	"APPLY_HOLD_ROLE_ELIGIBILITY" VARCHAR2(4 BYTE), 
	"RELEASE_HOLD_ROLE_ELIGIBILITY" VARCHAR2(4 BYTE), 
	"ORA_SEED_SET1" VARCHAR2(4 BYTE), 
	"ORA_SEED_SET2" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."DOO_HOLD_CODES_B" TO "RO_HBG_INTEGRATION";
