--------------------------------------------------------
--  DDL for Index DOO_LINE_STATUSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBG_INTEGRATION"."DOO_LINE_STATUSES_PK" ON "HBG_INTEGRATION"."DOO_LINE_STATUSES" ("LINE_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
