--------------------------------------------------------
--  DDL for Type DOO_SO_MAAS_BATCHES_RT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."DOO_SO_MAAS_BATCHES_RT" FORCE AS OBJECT
(
    INTERFACE_RUN_ID            NUMBER,
    SOURCE_SYSTEM     VARCHAR2 (240),
	BATCH_NAME        VARCHAR2 (240),
	ICS_BATCH_NO NUMBER,
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_BATCHES_RT" RETURN SELF AS RESULT
);
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "HBG_INTEGRATION"."DOO_SO_MAAS_BATCHES_RT" 
AS
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_BATCHES_RT"
        RETURN SELF AS RESULT
    AS
    BEGIN
        RETURN;
    END;
END;

/
