--------------------------------------------------------
--  DDL for Type DOO_SO_MAAS_HEADERS_ALL_RT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."DOO_SO_MAAS_HEADERS_ALL_RT" FORCE AS OBJECT
(
    SOURCE_TRANSACTION_ID            VARCHAR2 (200),
    AGREEMENT_NUMBER                 VARCHAR2 (600),
    AGREEMENT_HEADER_ID              NUMBER,
    PRE_CREDIT_CHECKED_FLAG          VARCHAR2 (4),
    SOURCE_TRANSACTION_SYSTEM        VARCHAR2 (120),
    SOURCE_TRANSACTION_NUMBER        VARCHAR2 (200),
    SOURCE_TRANSACTION_REVISION_NO   NUMBER,
    BUYING_PARTY_CONTACT_ID          NUMBER,
    BUYING_PARTY_CONTACT_NAME        VARCHAR2 (1440),
    BUYING_PARTY_CONTACT_NUMBER      VARCHAR2 (120),
    BUYING_PARTY_ID                  NUMBER,
    BUYING_PARTY_NAME                VARCHAR2 (1440),
    BUYING_PARTY_NUMBER              VARCHAR2 (120),
    BUYING_PARTY_FIRST_NAME          VARCHAR2 (600),
    BUYING_PARTY_LAST_NAME           VARCHAR2 (600),
    BUYING_PARTY_MIDDLE_NAME         VARCHAR2 (240),
    BUYING_PARTY_NAME_SUFFIX         VARCHAR2 (120),
    BUYING_PARTY_TITLE               VARCHAR2 (240),
    BUYING_CONTACT_FIRST_NAME        VARCHAR2 (600),
    BUYING_CONTACT_LAST_NAME         VARCHAR2 (600),
    BUYING_CONTACT_MIDDLE_NAME       VARCHAR2 (240),
    BUYING_CONTACT_NAME_SUFFIX       VARCHAR2 (120),
    BUYING_CONTACT_TITLE             VARCHAR2 (240),
    BUYING_PARTY_TYPE                VARCHAR2 (120),
    BUYING_PARTY_CONTACT_EMAIL       VARCHAR2 (1280),
    BUYING_PARTY_PERSON_EMAIL        VARCHAR2 (1280),
    BUYING_PARTY_ORG_EMAIL           VARCHAR2 (1280),
    PREF_SOLD_TO_CONTACT_POINT_ID    NUMBER,
    PREF_SOLD_CONT_PT_ORIG_SYS_REF   VARCHAR2 (960),
    CUSTOMER_PO_NUMBER               VARCHAR2 (200),
    TRANSACTIONAL_CURRENCY_CODE      VARCHAR2 (4000),
    TRANSACTIONAL_CURRENCY_NAME      VARCHAR2 (4000),
    TRANSACTION_ON                   VARCHAR2 (64),
    REQUESTING_BUSINESS_UNIT_ID      NUMBER,
    REQUESTING_BUSINESS_UNIT         VARCHAR2 (960),
    TRANSACTION_TYPE_CODE            VARCHAR2 (120),
    TRANSACTION_DOCUMENT_TYPE_CODE   VARCHAR2 (200),
    REQUEST_CANCEL_DATE              TIMESTAMP (6),
    CANCEL_REASON_CODE               VARCHAR2 (4000),
    CANCEL_REASON                    VARCHAR2 (4000),
    COMMENTS                         VARCHAR2 (4000),
    BATCH_NAME                       VARCHAR2 (200),
    SUB_BATCH_NAME                   VARCHAR2 (200),
    REQUESTING_LEGAL_UNIT_ID         NUMBER,
    REQUESTING_LEGAL_UNIT            VARCHAR2 (960),
    ORIG_SYS_DOCUMENT_REFERENCE      VARCHAR2 (200),
    PARTIAL_SHIP_ALLOWED_FLAG        VARCHAR2 (4),
    BUYING_PARTY_ORIG_SYS_REF        VARCHAR2 (1020),
    BUYING_PARTY_CONT_ORIG_SYS_REF   VARCHAR2 (1020),
    CURRENCY_CONVERSION_TYPE         VARCHAR2 (4000),
    CURRENCY_CONVERSION_RATE         NUMBER,
    CURRENCY_CONVERSION_DATE         DATE,
    PRICED_ON                        TIMESTAMP (6),
    FREEZE_PRICING                   VARCHAR2 (4),
    FREEZE_SHIPPING_CHARGE           VARCHAR2 (4),
    FREEZE_TAX                       VARCHAR2 (4),
    OPERATION_MODE                   VARCHAR2 (120),
    CREATE_CUSTOMER_INFO_FLAG        VARCHAR2 (4),
    SUBMIT_FLAG                      VARCHAR2 (4),
    REVISION_SOURCE_TXN_SYSTEM       VARCHAR2 (120),
    SALES_CHANNEL_CODE               VARCHAR2 (120),
    SALES_CHANNEL                    VARCHAR2 (320),
    SALESPERSON_ID                   NUMBER,
    SALESPERSON                      VARCHAR2 (1440),
    HEADER_ID                        NUMBER,
    BATCH_ID                         NUMBER,
    VALIDATION_BITSET                NUMBER,
    CREATION_MODE                    VARCHAR2 (120),
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_HEADERS_ALL_RT" RETURN SELF AS RESULT
);
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "HBG_INTEGRATION"."DOO_SO_MAAS_HEADERS_ALL_RT" 
AS
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_HEADERS_ALL_RT"
        RETURN SELF AS RESULT
    AS
    BEGIN
        RETURN;
    END;
END;

/
