--------------------------------------------------------
--  Constraints for Table FND_COMMON_LOOKUPS
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."FND_COMMON_LOOKUPS" ADD CONSTRAINT "FND_COMMON_LOOKUPS_PK" PRIMARY KEY ("LOOKUP_TYPE", "LOOKUP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
