--------------------------------------------------------
--  DDL for Type HBG_SO_TBL_DATA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."HBG_SO_TBL_DATA" IS OBJECT (
SOURCE_ORDER_ID			VARCHAR2(100)		
,ORDER_NUMBER			VARCHAR2(200)
,SOURCE_ORDER_SYSTEM	VARCHAR2(100)	
,ACCOUNT_NUMBER			VARCHAR2(200)
,SOURCE_ORDER_LINE_ID	VARCHAR2(200)
,SOURCE_ORDER_LINE_NUM	VARCHAR2(100)
,ITEM_NUMBER			VARCHAR2(100)
,QUANTITY				NUMBER
,HOLD_CODE				VARCHAR2(255)
,HOLD_COMMENTS			VARCHAR2(2000)
,RELEASE_CODE			VARCHAR2(255)
,RELEASE_COMMENTS		VARCHAR2(2000)
,OIC_RUN_ID				NUMBER	
,STATUS					VARCHAR2(50)
,STATUS_MESSAGE			CLOB
,CREATED_BY				VARCHAR2(200)
,CREATION_DATE			DATE
,LAST_UPDATED_BY		VARCHAR2(200)
,LAST_UPDATE_DATE		DATE
,SHIP_TO				VARCHAR2(200)
,SO_HEADER_STATUS		VARCHAR2(200)
,SO_LINE_STATUS			VARCHAR2(200)
,FULFILLMENT_LINE_NUM	NUMBER	
,CANCELLED_QTY			NUMBER
,FULFILL_LINE_STATUS	VARCHAR2(200)
,APPLY_HOLD				VARCHAR2(20)
);

/
