--------------------------------------------------------
--  DDL for Table HBG_INV_ONHAND_QUANTITIES_DETAIL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_INV_ONHAND_QUANTITIES_DETAIL" 
   (	"INVENTORY_ITEM_ID" NUMBER, 
	"STANDARD_PACK_UOM" VARCHAR2(12 BYTE), 
	"STANDARD_PACK_QUANTITY" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"DATE_RECEIVED" DATE, 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"PRIMARY_TRANSACTION_QUANTITY" NUMBER, 
	"SUBINVENTORY_CODE" VARCHAR2(40 BYTE), 
	"REVISION" VARCHAR2(72 BYTE), 
	"LOCATOR_ID" NUMBER, 
	"CREATE_TRANSACTION_ID" NUMBER, 
	"UPDATE_TRANSACTION_ID" NUMBER, 
	"LOT_NUMBER" VARCHAR2(320 BYTE), 
	"ORIG_DATE_RECEIVED" DATE, 
	"ONHAND_QUANTITIES_ID" NUMBER, 
	"TRANSACTION_UOM_CODE" VARCHAR2(12 BYTE), 
	"TRANSACTION_QUANTITY" NUMBER, 
	"SECONDARY_UOM_CODE" VARCHAR2(12 BYTE), 
	"SECONDARY_TRANSACTION_QUANTITY" NUMBER, 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"ORIG_SOURCE_TXN_ID" NUMBER, 
	"OWNING_TYPE" VARCHAR2(120 BYTE), 
	"OWNING_ENTITY_ID" NUMBER, 
	"AGING_ONSET_DATE" DATE, 
	"AGING_EXPIRATION_DATE" DATE, 
	"INV_STRIPING_CATEGORY" VARCHAR2(160 BYTE), 
	"PROJECT_ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"COUNTRY_OF_ORIGIN_CODE" VARCHAR2(8 BYTE), 
	"INV_RESERVED_ATTRIBUTE1" VARCHAR2(600 BYTE), 
	"INV_RESERVED_ATTRIBUTE2" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE1" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE2" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE3" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE4" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE5" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE6" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE7" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE8" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE9" VARCHAR2(600 BYTE), 
	"INV_USER_DEF_ATTRIBUTE10" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_INV_ONHAND_QUANTITIES_DETAIL" TO "RO_HBG_INTEGRATION";
