--------------------------------------------------------
--  DDL for Table HBG_PROCESS_ORDERS_REPORT_STG
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_REPORT_STG" 
   (	"BATCH_NAME" VARCHAR2(50 BYTE), 
	"SOURCE_TRANSACTION_ID" VARCHAR2(50 BYTE), 
	"MESSAGE_TEXT" VARCHAR2(4000 BYTE), 
	"LOAD_REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_REPORT_STG" TO "RO_HBG_INTEGRATION";
