--------------------------------------------------------
--  DDL for Table HBG_AR_PAYMENTS_LINES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AR_PAYMENTS_LINES" 
   (	"LINE_ID" NUMBER DEFAULT "HBG_INTEGRATION"."SQ_PAYMENTS_LINE_ID"."NEXTVAL", 
	"BATCH_ID" NUMBER, 
	"BUSINESS_UNIT" VARCHAR2(100 BYTE), 
	"PROCESS_TYPE" VARCHAR2(255 BYTE), 
	"PAYMENT_TYPE" VARCHAR2(100 BYTE), 
	"PAYMENT_DATE" DATE, 
	"ACCOUNT_NUMBER" VARCHAR2(255 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(524 BYTE), 
	"RECEIPT_NUMBER" VARCHAR2(255 BYTE), 
	"INVOICE_NUMBER" VARCHAR2(255 BYTE), 
	"CLAIM_NUMBER" VARCHAR2(255 BYTE), 
	"TRANSACTION_CODE" VARCHAR2(255 BYTE), 
	"AMOUNT" NUMBER, 
	"PAYMENT_METHOD" VARCHAR2(255 BYTE), 
	"CURRENCY" VARCHAR2(32 BYTE), 
	"GL_ACCOUNT" VARCHAR2(255 BYTE), 
	"RECEIPT_ID" NUMBER, 
	"PAYMENT_ID" NUMBER, 
	"CLAIM_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(512 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(512 BYTE), 
	"RETURN_STATUS" VARCHAR2(50 BYTE), 
	"RETURN_MESSAGE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
