--------------------------------------------------------
--  DDL for Package HBG_SALES_CREDIT_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "HBG_INTEGRATION"."HBG_SALES_CREDIT_PKG" IS
    PROCEDURE hbg_sales_credit_div_create (
        p_division_number    IN   VARCHAR2,
        p_division_name      IN   VARCHAR2,
        p_external_checkbox  IN   VARCHAR2,
        p_notes              IN   VARCHAR2,
        p_entered_by         IN   VARCHAR2,
        p_updated_by         IN   VARCHAR2,
        p_start_date         IN   VARCHAR2,
        p_end_date           IN   VARCHAR2,
        p_status             IN   VARCHAR2,
        p_sales_force_id     IN   NUMBER,
        p_return_status      OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_credit_div_update (
        p_sf_div_id          IN   NUMBER,
        p_division_number    IN   VARCHAR2,
        p_division_name      IN   VARCHAR2,
        p_external_checkbox  IN   VARCHAR2,
        p_notes              IN   VARCHAR2,
        p_updated_by         IN   VARCHAR2,
        p_start_date         IN   VARCHAR2,
        p_end_date           IN   VARCHAR2,
        p_status             IN   VARCHAR2,
        p_sales_force_id     IN   NUMBER,
        p_return_status      OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_credit_sf_create (
        p_sales_force_number  IN   VARCHAR2,
        p_sales_force_name    IN   VARCHAR2,
        p_company             IN   VARCHAR2,
        p_edelweiss           IN   VARCHAR2,
        p_external_checkbox   IN   VARCHAR2,
        p_notes               IN   VARCHAR2,
        p_entered_by          IN   VARCHAR2,
        p_updated_by          IN   VARCHAR2,
        p_start_date          IN   VARCHAR2,
        p_end_date            IN   VARCHAR2,
        p_status              IN   VARCHAR2,
        p_return_status       OUT  VARCHAR2,
        p_sales_force_id      OUT  NUMBER
    );

    PROCEDURE hbg_sales_credit_sf_update (
        p_sales_force_id      IN   NUMBER,
        p_sales_force_number  IN   VARCHAR2,
        p_sales_force_name    IN   VARCHAR2,
        p_company             IN   VARCHAR2,
        p_edelweiss           IN   VARCHAR2,
        p_external_checkbox   IN   VARCHAR2,
        p_notes               IN   VARCHAR2,
        p_entered_by          IN   VARCHAR2,
        p_updated_by          IN   VARCHAR2,
        p_start_date          IN   VARCHAR2,
        p_end_date            IN   VARCHAR2,
        p_status              IN   VARCHAR2,
        p_return_status       OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_credit_territory_create (
        p_territory_number     IN   VARCHAR2,
        p_territory_name       IN   VARCHAR2,
        p_external_checkbox    IN   VARCHAR2,
        p_email                IN   VARCHAR2,
        p_edelweiss            IN   VARCHAR2,
        p_wholesale_commision  IN   NUMBER,
        p_retail_commision     IN   NUMBER,
        p_notes                IN   VARCHAR2,
        p_entered_by           IN   VARCHAR2,
        p_updated_by           IN   VARCHAR2,
        p_start_date           IN   VARCHAR2,
        p_end_date             IN   VARCHAR2,
        p_status               IN   VARCHAR2,
        p_sf_div_id            IN   NUMBER,
        p_sales_force_id            IN   NUMBER,
        p_return_status        OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_credit_dist_channel_create (
        p_distribution_channel         IN   VARCHAR2,
        p_dist_channel_description     IN   VARCHAR2,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_reporting_group_description  IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_credit_dist_channel_update (
        p_dist_channel_id              IN   NUMBER,
        p_distribution_channel         IN   VARCHAR2,
        p_dist_channel_description     IN   VARCHAR2,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_reporting_group_description  IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_rep_create (
        p_sales_rep_number               IN   VARCHAR2,
        p_sales_rep_name                 IN   VARCHAR2,
        p_external_sales_rep_identifier  IN   NUMBER,
        p_address                        IN   VARCHAR2,
        p_city                           IN   VARCHAR2,
        p_state                          IN   VARCHAR2,
        p_postal_code                    IN   VARCHAR2,
        p_country                        IN   VARCHAR2,
        p_phone_number                   IN   VARCHAR2,
        p_email                          IN   VARCHAR2,
        p_company                        IN   VARCHAR2,
        p_company_description            IN   VARCHAR2,
        p_external_checkbox              IN   VARCHAR2,
        p_wholesale_commision            IN   NUMBER,
        p_retail_commision               IN   NUMBER,
        p_edelweiss                      IN   VARCHAR2,
        p_notes                          IN   VARCHAR2,
        p_entered_by                     IN   VARCHAR2,
        p_updated_by                     IN   VARCHAR2,
        p_start_date                     IN   VARCHAR2,
        p_end_date                       IN   VARCHAR2,
        p_status                         IN   VARCHAR2,
        p_sf_territory_id                IN   NUMBER,
        p_sales_force_id                 IN   NUMBER,
        p_division_id                    IN   NUMBER,
        p_return_status                  OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_rep_update (
        p_sf_sales_rep_id                IN   NUMBER,
        p_sales_rep_number               IN   VARCHAR2,
        p_sales_rep_name                 IN   VARCHAR2,
        p_external_sales_rep_identifier  IN   NUMBER,
        p_address                        IN   VARCHAR2,
        p_city                           IN   VARCHAR2,
        p_state                          IN   VARCHAR2,
        p_postal_code                    IN   VARCHAR2,
        p_country                        IN   VARCHAR2,
        p_phone_number                   IN   VARCHAR2,
        p_email                          IN   VARCHAR2,
        p_company                        IN   VARCHAR2,
        p_company_description            IN   VARCHAR2,
        p_external_checkbox              IN   VARCHAR2,
        p_wholesale_commision            IN   NUMBER,
        p_retail_commision               IN   NUMBER,
        p_edelweiss                      IN   VARCHAR2,
        p_notes                          IN   VARCHAR2,
        p_entered_by                     IN   VARCHAR2,
        p_updated_by                     IN   VARCHAR2,
        p_start_date                     IN   VARCHAR2,
        p_end_date                       IN   VARCHAR2,
        p_status                         IN   VARCHAR2,
        p_sf_territory_id                IN   NUMBER,
        p_sales_force_id                 IN   NUMBER,
        p_division_id                    IN   NUMBER,
        p_return_status                  OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_mapping_create (
        p_isbn                         IN   VARCHAR2,
        p_sales_force                  IN   VARCHAR2,
        p_sales_force_name             IN   VARCHAR2,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_reporting_group_description  IN   VARCHAR2,
        p_category_1                   IN   VARCHAR2,
        p_category_1_description       IN   VARCHAR2,
        p_category_2                   IN   VARCHAR2,
        p_category_2_description       IN   VARCHAR2,
        p_format                       IN   VARCHAR2,
        p_format_description           IN   VARCHAR2,
        p_sub_format                   IN   VARCHAR2,
        p_sub_format_description       IN   VARCHAR2,
        p_bisac                        IN   VARCHAR2,
        p_bisac_description            IN   VARCHAR2,
        p_account_type                 IN   VARCHAR2,
        p_account_type_description     IN   VARCHAR2,
        p_priority                     IN   NUMBER,
        p_notes                        IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_status                       IN   VARCHAR2,
        p_sales_force_id               IN   NUMBER,
        p_sf_acct_type_id              IN   NUMBER,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_mapping_update (
        p_sf_mapping_id                IN   NUMBER,
        p_isbn                         IN   VARCHAR2,
        p_sales_force                  IN   VARCHAR2,
        p_sales_force_name             IN   VARCHAR2,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_reporting_group_description  IN   VARCHAR2,
        p_category_1                   IN   VARCHAR2,
        p_category_1_description       IN   VARCHAR2,
        p_category_2                   IN   VARCHAR2,
        p_category_2_description       IN   VARCHAR2,
        p_format                       IN   VARCHAR2,
        p_format_description           IN   VARCHAR2,
        p_sub_format                   IN   VARCHAR2,
        p_sub_format_description       IN   VARCHAR2,
        p_bisac                        IN   VARCHAR2,
        p_bisac_description            IN   VARCHAR2,
        p_account_type                 IN   VARCHAR2,
        p_account_type_description     IN   VARCHAR2,
        p_priority                     IN   NUMBER,
        p_notes                        IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_status                       IN   VARCHAR2,
        p_sales_force_id               IN   NUMBER,
        p_sf_acct_type_id              IN   NUMBER,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_teritory_create (
        p_territory_number     IN   VARCHAR2,
        p_territory_name       IN   VARCHAR2,
        p_external_checkbox    IN   VARCHAR2,
        p_email                IN   VARCHAR2,
        p_edelweiss            IN   VARCHAR2,
        p_wholesale_commision  IN   NUMBER,
        p_retail_commision     IN   NUMBER,
        p_notes                IN   VARCHAR2,
        p_entered_by           IN   VARCHAR2,
        p_updated_by           IN   VARCHAR2,
        p_updated_date         IN   DATE,
        p_start_date           IN   VARCHAR2,
        p_end_date             IN   VARCHAR2,
        p_status               IN   VARCHAR2,
        p_sf_div_id            IN   NUMBER,
        p_return_status        OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_credit_territory_update (
        p_sf_territory_id      IN   NUMBER,
        p_territory_number     IN   VARCHAR2,
        p_territory_name       IN   VARCHAR2,
        p_external_checkbox    IN   VARCHAR2,
        p_email                IN   VARCHAR2,
        p_edelweiss            IN   VARCHAR2,
        p_wholesale_commision  IN   NUMBER,
        p_retail_commision     IN   NUMBER,
        p_notes                IN   VARCHAR2,
        p_entered_by           IN   VARCHAR2,
        p_updated_by           IN   VARCHAR2,
        p_start_date           IN   VARCHAR2,
        p_end_date             IN   VARCHAR2,
        p_status               IN   VARCHAR2,
        p_sf_div_id            IN   NUMBER,
        p_sales_force_id            IN   NUMBER,
        p_return_status        OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_distribution_channel_create (
        p_distribution_channel         IN   VARCHAR2,
        p_dist_channel_description     IN   VARCHAR2,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   NUMBER,
        p_reporting_group_description  IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_updated_date                 IN   DATE,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_assign_distribution_create (
        p_account_number            IN   VARCHAR2,
        p_account_name              IN   VARCHAR2,
        p_sales_force_number        IN   VARCHAR2,
        p_sales_force_name          IN   VARCHAR2,
        p_owner                     IN   VARCHAR2,
        p_reporting_group           IN   VARCHAR2,
        p_category_1                IN   VARCHAR2,
        p_category_2                IN   VARCHAR2,
        p_bisac                     IN   VARCHAR2,
        p_bisac_description         IN   VARCHAR2,
        p_distribution_channel      IN   VARCHAR2,
        p_dist_channel_description  IN   VARCHAR2,
        p_notes                     IN   VARCHAR2,
        p_entered_by                IN   VARCHAR2,
        p_updated_by                IN   VARCHAR2,
        p_start_date                IN   VARCHAR2,
        p_end_date                  IN   VARCHAR2,
        p_dist_channel_id           IN   NUMBER,
        p_return_status             OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_assign_distribution_update (
        p_dist_chnl_assign_id       IN   NUMBER,
        p_account_number            IN   VARCHAR2,
        p_account_name              IN   VARCHAR2,
        p_sales_force_number        IN   VARCHAR2,
        p_sales_force_name          IN   VARCHAR2,
        p_owner                     IN   VARCHAR2,
        p_reporting_group           IN   VARCHAR2,
        p_category_1                IN   VARCHAR2,
        p_category_2                IN   VARCHAR2,
        p_bisac                     IN   VARCHAR2,
        p_bisac_description         IN   VARCHAR2,
        p_distribution_channel      IN   VARCHAR2,
        p_dist_channel_description  IN   VARCHAR2,
        p_notes                     IN   VARCHAR2,
        p_entered_by                IN   VARCHAR2,
        p_updated_by                IN   VARCHAR2,
        p_start_date                IN   VARCHAR2,
        p_end_date                  IN   VARCHAR2,
        p_dist_channel_id           IN   NUMBER,
        p_return_status             OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_force_create (
        p_sales_force_id           IN   NUMBER,
        p_om_destination_account   IN   NUMBER,
        p_om_sales_force_code      IN   NUMBER,
        p_om_division              IN   NUMBER,
        p_om_territory             IN   NUMBER,
        p_om_sales_rep             IN   NUMBER,
        p_om_distribution_channel  IN   VARCHAR2,
        p_ar_sales_force_code      IN   NUMBER,
        p_ar_division              IN   NUMBER,
        p_ar_territory             IN   NUMBER,
        p_ar_sales_rep             IN   NUMBER,
        p_ar_distribution_channel  IN   VARCHAR2,
        p_created_by               IN   VARCHAR2,
        p_created_date             IN   DATE,
        p_last_updated_by          IN   VARCHAR2,
        p_last_updated_date        IN   DATE,
        p_return_status            OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_force_assign_create (
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_reporting_group_description  IN   VARCHAR2,
        p_category_1                   IN   VARCHAR2,
        p_category_1_description       IN   VARCHAR2,
        p_category_2                   IN   VARCHAR2,
        p_category_2_description       IN   VARCHAR2,
        p_format                       IN   VARCHAR2,
        p_format_description           IN   VARCHAR2,
        p_sub_format                   IN   VARCHAR2,
        p_sub_format_description       IN   VARCHAR2,
        p_bisac                        IN   VARCHAR2,
        p_bisac_description            IN   VARCHAR2,
        p_customer_org_number          IN   NUMBER,
        p_organization_name            IN   VARCHAR2,
        p_customer_account_number      IN   VARCHAR2,
        p_account_name                 IN   VARCHAR2,
        p_account_type                 IN   VARCHAR2,
        p_bill_to_                     IN   VARCHAR2,
        p_state_province               IN   VARCHAR2,
        p_bill_to_country              IN   VARCHAR2,
        p_alt_sales_country            IN   VARCHAR2,
        p_ship_to_number               IN   VARCHAR2,
        p_ship_to_name                 IN   VARCHAR2,
        p_ship_to_state                IN   VARCHAR2,
        p_ship_to_country              IN   VARCHAR2,
        p_final_destination_country    IN   VARCHAR2,
        p_sales_force                  IN   VARCHAR2,
        p_sales_force_name             IN   VARCHAR2,
        p_division                     IN   VARCHAR2,
        p_division_name                IN   VARCHAR2,
        p_territory                    IN   VARCHAR2,
        p_territory_name               IN   VARCHAR2,
        p_sales_rep                    IN   VARCHAR2,
        p_sales_rep_name               IN   VARCHAR2,
        p_override                     IN   VARCHAR2,
        p_account_override_start_date  IN   VARCHAR2,
        p_account_override_end_date    IN   VARCHAR2,
        p_notes                        IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_status                       IN   VARCHAR2,
        p_sales_force_id               IN   NUMBER,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE hbg_sales_force_assign_update (
        p_sf_assign_id                 IN   NUMBER,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_reporting_group_description  IN   VARCHAR2,
        p_category_1                   IN   VARCHAR2,
        p_category_1_description       IN   VARCHAR2,
        p_category_2                   IN   VARCHAR2,
        p_category_2_description       IN   VARCHAR2,
        p_format                       IN   VARCHAR2,
        p_format_description           IN   VARCHAR2,
        p_sub_format                   IN   VARCHAR2,
        p_sub_format_description       IN   VARCHAR2,
        p_bisac                        IN   VARCHAR2,
        p_bisac_description            IN   VARCHAR2,
        p_customer_org_number          IN   NUMBER,
        p_organization_name            IN   VARCHAR2,
        p_customer_account_number      IN   VARCHAR2,
        p_account_name                 IN   VARCHAR2,
        p_account_type                 IN   VARCHAR2,
        p_bill_to_                     IN   VARCHAR2,
        p_state_province               IN   VARCHAR2,
        p_bill_to_country              IN   VARCHAR2,
        p_alt_sales_country            IN   VARCHAR2,
        p_ship_to_number               IN   VARCHAR2,
        p_ship_to_name                 IN   VARCHAR2,
        p_ship_to_state                IN   VARCHAR2,
        p_ship_to_country              IN   VARCHAR2,
        p_final_destination_country    IN   VARCHAR2,
        p_sales_force                  IN   VARCHAR2,
        p_sales_force_name             IN   VARCHAR2,
        p_division                     IN   VARCHAR2,
        p_division_name                IN   VARCHAR2,
        p_territory                    IN   VARCHAR2,
        p_territory_name               IN   VARCHAR2,
        p_sales_rep                    IN   VARCHAR2,
        p_sales_rep_name               IN   VARCHAR2,
        p_override                     IN   VARCHAR2,
        p_account_override_start_date  IN   VARCHAR2,
        p_account_override_end_date    IN   VARCHAR2,
        p_notes                        IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_status                       IN   VARCHAR2,
        p_sales_force_id               IN   NUMBER,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE assign_account_type_to_sales_force_create (
        p_sales_force        IN   VARCHAR2,
        p_sales_force_name   IN   VARCHAR2,
        p_sf_owner           IN   VARCHAR2,
        p_owner_name         IN   VARCHAR2,
        p_account_type       IN   VARCHAR2,
        p_account_type_name  IN   VARCHAR2,
        p_notes              IN   VARCHAR2,
        p_entered_by         IN   VARCHAR2,
        p_updated_by         IN   VARCHAR2,
        p_start_date         IN   VARCHAR2,
        p_end_date           IN   VARCHAR2,
        p_status             IN   VARCHAR2,
        p_return_status      OUT  VARCHAR2
    );

    PROCEDURE assign_account_type_to_sales_force_update (
        p_sf_account_id      IN   NUMBER,
        p_sales_force        IN   VARCHAR2,
        p_sales_force_name   IN   VARCHAR2,
        p_sf_owner           IN   VARCHAR2,
        p_owner_name         IN   VARCHAR2,
        p_account_type       IN   VARCHAR2,
        p_account_type_name  IN   VARCHAR2,
        p_notes              IN   VARCHAR2,
        p_entered_by         IN   VARCHAR2,
        p_updated_by         IN   VARCHAR2,
        p_start_date         IN   VARCHAR2,
        p_end_date           IN   VARCHAR2,
        p_status             IN   VARCHAR2,
        p_return_status      OUT  VARCHAR2
    );

    PROCEDURE default_distribution_channel_create (
        p_organization_number        IN   NUMBER,
        p_organization_name          IN   VARCHAR2,
        p_account_number             IN   VARCHAR2,
        p_account_name               IN   VARCHAR2,
        p_account_type               IN   VARCHAR2,
        p_description                IN   VARCHAR2,
        p_bill_to_country            IN   VARCHAR2,
        p_bill_to_state              IN   VARCHAR2,
        p_ship_to_country            IN   VARCHAR2,
        p_ship_to_state              IN   VARCHAR2,
        p_final_destination_country  IN   VARCHAR2,
        p_sales_force                IN   VARCHAR2,
        p_sales_force_name           IN   VARCHAR2,
        p_division                   IN   VARCHAR2,
        p_division_name              IN   VARCHAR2,
        p_territory                  IN   VARCHAR2,
        p_territory_name             IN   VARCHAR2,
        p_sales_rep                  IN   VARCHAR2,
        p_sales_rep_name             IN   VARCHAR2,
        p_distribution_channel       IN   VARCHAR2,
        p_notes                      IN   VARCHAR2,
        p_entered_by                 IN   VARCHAR2,
        p_updated_by                 IN   VARCHAR2,
        p_start_date                 IN   VARCHAR2,
        p_end_date                   IN   VARCHAR2,
        p_status                     IN   VARCHAR2,
        p_return_status              OUT  VARCHAR2
    );

    PROCEDURE default_distribution_channel_update (
        p_df_distribution_id         IN   NUMBER,
        p_organization_number        IN   NUMBER,
        p_organization_name          IN   VARCHAR2,
        p_account_number             IN   VARCHAR2,
        p_account_name               IN   VARCHAR2,
        p_account_type               IN   VARCHAR2,
        p_description                IN   VARCHAR2,
        p_bill_to_country            IN   VARCHAR2,
        p_bill_to_state              IN   VARCHAR2,
        p_ship_to_country            IN   VARCHAR2,
        p_ship_to_state              IN   VARCHAR2,
        p_final_destination_country  IN   VARCHAR2,
        p_sales_force                IN   VARCHAR2,
        p_sales_force_name           IN   VARCHAR2,
        p_division                   IN   VARCHAR2,
        p_division_name              IN   VARCHAR2,
        p_territory                  IN   VARCHAR2,
        p_territory_name             IN   VARCHAR2,
        p_sales_rep                  IN   VARCHAR2,
        p_sales_rep_name             IN   VARCHAR2,
        p_distribution_channel       IN   VARCHAR2,
        p_notes                      IN   VARCHAR2,
        p_entered_by                 IN   VARCHAR2,
        p_updated_by                 IN   VARCHAR2,
        p_start_date                 IN   VARCHAR2,
        p_end_date                   IN   VARCHAR2,
        p_status                     IN   VARCHAR2,
        p_return_status              OUT  VARCHAR2
    );

    PROCEDURE unassigned_sales_force_create (
        p_type                         IN   VARCHAR2,
          p_organization_number        IN   NUMBER,
        p_organization_name          IN   VARCHAR2,
        p_account_number               IN   VARCHAR2,
        p_account_name                 IN   VARCHAR2,
        p_account_type                 IN   VARCHAR2,
        p_description                  IN   VARCHAR2,
        p_account_prefix               IN   VARCHAR2,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_reporting_group_description  IN   VARCHAR2,
        p_bill_to_country              IN   VARCHAR2,
        p_bill_to_state                IN   VARCHAR2,
        p_ship_to_country              IN   VARCHAR2,
        p_ship_to_state                IN   VARCHAR2,
        p_final_destination_country    IN   VARCHAR2,
        p_sales_force_number           IN   VARCHAR2,
        p_sales_force_name             IN   VARCHAR2,
        p_division                     IN   VARCHAR2,
        p_division_name                IN   VARCHAR2,
        p_territory                    IN   VARCHAR2,
        p_territory_name               IN   VARCHAR2,
        p_sales_rep                    IN   VARCHAR2,
        p_sales_rep_name               IN   VARCHAR2,
        p_notes                        IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_updated_date                 IN   DATE,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_status                       IN   VARCHAR2,
        p_sf_assign_id                 IN   NUMBER,
        p_sales_force_id               IN   NUMBER,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE unassigned_sales_force_update (
        p_sf_unassigned_id             IN   NUMBER,
        p_type                         IN   VARCHAR2,
        p_organization_number        IN   NUMBER,
        p_organization_name          IN   VARCHAR2,
        p_account_number               IN   VARCHAR2,
        p_account_name                 IN   VARCHAR2,
        p_account_type                 IN   VARCHAR2,
        p_description                  IN   VARCHAR2,
        p_account_prefix               IN   VARCHAR2,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_reporting_group_description  IN   VARCHAR2,
        p_bill_to_country              IN   VARCHAR2,
        p_bill_to_state                IN   VARCHAR2,
        p_ship_to_country              IN   VARCHAR2,
        p_ship_to_state                IN   VARCHAR2,
        p_final_destination_country    IN   VARCHAR2,
        p_sales_force_number           IN   VARCHAR2,
        p_sales_force_name             IN   VARCHAR2,
        p_division                     IN   VARCHAR2,
        p_division_name                IN   VARCHAR2,
        p_territory                    IN   VARCHAR2,
        p_territory_name               IN   VARCHAR2,
        p_sales_rep                    IN   VARCHAR2,
        p_sales_rep_name               IN   VARCHAR2,
        p_notes                        IN   VARCHAR2,
        p_entered_by                   IN   VARCHAR2,
        p_updated_by                   IN   VARCHAR2,
        p_updated_date                 IN   DATE,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_status                       IN   VARCHAR2,
        p_sf_assign_id                 IN   NUMBER,
        p_sales_force_id               IN   NUMBER,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE distribution_maintenance_create (
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_creation_date                IN   DATE,
        p_created_by                   IN   VARCHAR2,
        p_last_updated_by              IN   VARCHAR2,
        p_last_update_date             IN   DATE,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_dist_channel_id              IN   NUMBER,
        p_reporting_group_description  IN   VARCHAR2,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE distribution_maintenance_update (
        p_dist_mainten_stg_id          IN   NUMBER,
        p_owner                        IN   VARCHAR2,
        p_owner_description            IN   VARCHAR2,
        p_reporting_group              IN   VARCHAR2,
        p_creation_date                IN   DATE,
        p_created_by                   IN   VARCHAR2,
        p_last_updated_by              IN   VARCHAR2,
        p_last_update_date             IN   DATE,
        p_start_date                   IN   VARCHAR2,
        p_end_date                     IN   VARCHAR2,
        p_dist_channel_id              IN   NUMBER,
        p_reporting_group_description  IN   VARCHAR2,
        p_return_status                OUT  VARCHAR2
    );

    PROCEDURE sales_force_validation (
        p_source_line_id             IN   VARCHAR2,
        p_batch_id                   IN   VARCHAR2,
        return_status                OUT  VARCHAR2,
        p_so_mapping_val_type_array  OUT  hbg_so_mapping_val_type_array
    );

    PROCEDURE dist_channel_validation (
        p_source_line_id             IN   VARCHAR2,
        p_batch_id                   IN   VARCHAR2,
        return_status                OUT  VARCHAR2,
        p_so_mapping_val_type_array  OUT  hbg_so_mapping_val_type_array
    );

    PROCEDURE unassigndefault_sales_force_create (
        p_account_number IN VARCHAR2
    );
    PROCEDURE assigndefault_dist_channel_create (
        p_account_number IN VARCHAR2,
        p_status out varchar2
    );

END hbg_sales_credit_pkg;

/
