--------------------------------------------------------
--  DDL for Table HBG_SO_MASS_UPDATE_STG
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_SO_MASS_UPDATE_STG" 
   (	"INV_ORGANIZATION_ID" VARCHAR2(200 BYTE), 
	"INV_ORGANIZATION_CODE" VARCHAR2(200 BYTE), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"ACCOUNT_NUMBER" VARCHAR2(200 BYTE), 
	"HEADER_ORDER_STATUS" VARCHAR2(200 BYTE), 
	"REQUEST_CANCEL_DATE" VARCHAR2(200 BYTE), 
	"FREIGHT_TERMS_CODE" VARCHAR2(200 BYTE), 
	"ACTUAL_SHIP_DATE" VARCHAR2(200 BYTE), 
	"REQUEST_ARRIVAL_DATE" VARCHAR2(200 BYTE), 
	"ORDERED_QTY" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(200 BYTE), 
	"CUSTOMER_PO_NUMBER" VARCHAR2(200 BYTE), 
	"SOURCE_LINE_ID" VARCHAR2(200 BYTE), 
	"APPLY_RESON_CODE" VARCHAR2(200 BYTE), 
	"APPLY_RESON_COMMENTS" VARCHAR2(1000 BYTE), 
	"RELEASE_RESON_CODE" VARCHAR2(200 BYTE), 
	"RELEASE_RESON_COMMENTS" VARCHAR2(1000 BYTE), 
	"LINE_STATUS_CODE" VARCHAR2(200 BYTE), 
	"ORDER_NUMBER" VARCHAR2(200 BYTE), 
	"OIC_RUN_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"NEW_APPLY_RESON_CODE" VARCHAR2(200 BYTE), 
	"NEW_APPLY_RESON_COMMENTS" VARCHAR2(1000 BYTE), 
	"NEW_RELEASE_RESON_CODE" VARCHAR2(200 BYTE), 
	"NEW_RELEASE_RESON_COMMENTS" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(200 BYTE), 
	"SOURCE_ORDER_SYSTEM" VARCHAR2(200 BYTE), 
	"SOURCE_ORDER_ID" VARCHAR2(200 BYTE), 
	"BATCH_ID" VARCHAR2(200 BYTE), 
	"HOLD_ACTION" VARCHAR2(200 BYTE), 
	"CUST_ACCOUNT_ID" NUMBER, 
	"PARTY_SITE_ID" NUMBER, 
	"OWNER_CODE" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP" VARCHAR2(200 BYTE), 
	"CATEGORY1" VARCHAR2(200 BYTE), 
	"CATEGORY2" VARCHAR2(200 BYTE), 
	"OFFER_CODE" VARCHAR2(200 BYTE), 
	"PARTY_NAME" VARCHAR2(300 BYTE), 
	"LINE_NUMBER" VARCHAR2(200 BYTE), 
	"ORDERED_NET_QTY" NUMBER, 
	"LINE_STATUS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_SO_MASS_UPDATE_STG" TO "RO_HBG_INTEGRATION";
