--------------------------------------------------------
--  DDL for Table HBG_CO_RULES_LINES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CO_RULES_LINES" 
   (	"RULE_ID" NUMBER, 
	"RULE_LINE_ID" NUMBER, 
	"SEQUENCE" NUMBER, 
	"SHIP_TO_NUMBER" VARCHAR2(255 BYTE), 
	"OWNER_CODE" VARCHAR2(100 BYTE), 
	"REPORTING_GROUP" VARCHAR2(100 BYTE), 
	"PUBLISHER" VARCHAR2(100 BYTE), 
	"IMPRINT" VARCHAR2(100 BYTE), 
	"FORMAT" VARCHAR2(100 BYTE), 
	"SUB_FORMAT" VARCHAR2(100 BYTE), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"PRICE_ON_BOOK" VARCHAR2(5 BYTE), 
	"SHRINK_WRAP" VARCHAR2(5 BYTE), 
	"MASTER_PACK" VARCHAR2(5 BYTE), 
	"INNER_PACK" VARCHAR2(5 BYTE), 
	"NEW_PACK_QUANTITY" VARCHAR2(5 BYTE), 
	"SHIP_TO_NAME" VARCHAR2(200 BYTE), 
	"OWNER_NAME" VARCHAR2(200 BYTE), 
	"ITEM" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP_DESCRIPTION" VARCHAR2(200 BYTE), 
	"PUBLISHER_NAME" VARCHAR2(200 BYTE), 
	"IMPRINT_NAME" VARCHAR2(200 BYTE), 
	"FORMAT_NAME" VARCHAR2(200 BYTE), 
	"SUB_FORMAT_NAME" VARCHAR2(200 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_BY" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
