--------------------------------------------------------
--  DDL for Table HBG_AR_PAYMENTS_HEADER
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AR_PAYMENTS_HEADER" 
   (	"BATCH_ID" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(512 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
