--------------------------------------------------------
--  DDL for Table HBG_SO_HOT_TITLES_HOLD_EXT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_SO_HOT_TITLES_HOLD_EXT" 
   (	"SOURCE_ORDER_SYSTEM" VARCHAR2(100 BYTE), 
	"SOURCE_ORDER_ID" VARCHAR2(200 BYTE), 
	"ORDER_NUMBER" VARCHAR2(100 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(200 BYTE), 
	"SOURCE_ORDER_LINE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_ORDER_LINE_NUM" VARCHAR2(100 BYTE), 
	"ITEM_NUMBER" VARCHAR2(100 BYTE), 
	"QUANTITY" NUMBER, 
	"HOLD_CODE" VARCHAR2(255 BYTE), 
	"HOLD_COMMENTS" VARCHAR2(2000 BYTE), 
	"RELEASE_CODE" VARCHAR2(255 BYTE), 
	"RELEASE_COMMENTS" VARCHAR2(2000 BYTE), 
	"OIC_RUN_ID" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"STATUS_MESSAGE" CLOB, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"SHIP_TO" VARCHAR2(200 BYTE), 
	"SO_HEADER_STATUS" VARCHAR2(200 BYTE), 
	"SO_LINE_STATUS" VARCHAR2(200 BYTE), 
	"FULFILLMENT_LINE_NUM" NUMBER, 
	"CANCELLED_QTY" NUMBER, 
	"FULFILL_LINE_STATUS" VARCHAR2(200 BYTE), 
	"APPLY_HOLD" VARCHAR2(20 BYTE), 
	"FULFILL_LINE_ID" NUMBER, 
	"RELEASE_HOLD_FLAG" VARCHAR2(20 BYTE), 
	"HOLD_REASON" VARCHAR2(1000 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"STAGE_ID" NUMBER, 
	"ACCOUNT_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("STATUS_MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_SO_HOT_TITLES_HOLD_EXT" TO "RO_HBG_INTEGRATION";
