--------------------------------------------------------
--  DDL for Table HBG_AUTO_HOLD_ITEMS_EXT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AUTO_HOLD_ITEMS_EXT" 
   (	"INVENTORY_ITEM_ID" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(200 BYTE), 
	"ORGANIZATION_CODE" VARCHAR2(200 BYTE), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"SHORT_TITLE" VARCHAR2(200 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"OIC_RUN_ID" NUMBER, 
	"STATUS" VARCHAR2(200 BYTE), 
	"STATUS_MESSAGE" CLOB, 
	"OWNER" VARCHAR2(255 BYTE), 
	"REPORTING_GROUP" VARCHAR2(255 BYTE), 
	"CATEGORY_1" VARCHAR2(255 BYTE), 
	"CATEGORY_2" VARCHAR2(255 BYTE), 
	"FORMAT" VARCHAR2(255 BYTE), 
	"ITEM_TYPE" VARCHAR2(255 BYTE), 
	"SUB_FORMAT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("STATUS_MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_AUTO_HOLD_ITEMS_EXT" TO "RO_HBG_INTEGRATION";
