--------------------------------------------------------
--  DDL for Table HBG_INV_TRANSACTIONS_ARCHIVE
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_INV_TRANSACTIONS_ARCHIVE" 
   (	"OIC_INSTANCE_ID" VARCHAR2(2000 BYTE), 
	"WMS_PROCESS_ID" VARCHAR2(2000 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"SOURCE_HEADER_ID" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(960 BYTE), 
	"SOURCE_LINE_ID" VARCHAR2(100 BYTE), 
	"ISBN" VARCHAR2(255 BYTE), 
	"TRANSACTION_QUANTITY" NUMBER, 
	"TRANSACTION_UOM" VARCHAR2(100 BYTE), 
	"TRANSACTION_REFERENCE" VARCHAR2(255 BYTE), 
	"SUBINVENTORY" VARCHAR2(255 BYTE), 
	"TRANSFER_SUBINVENTORY" VARCHAR2(255 BYTE), 
	"REASON_NAME" VARCHAR2(255 BYTE), 
	"LOT_NUMBER" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"RETURN_MESSAGE" VARCHAR2(2000 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_INV_TRANSACTIONS_ARCHIVE" TO "RO_HBG_INTEGRATION";
