--------------------------------------------------------
--  DDL for Table HBG_PIM_PEM_STG
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PIM_PEM_STG" 
   (	"ISBN13" VARCHAR2(13 BYTE), 
	"SEQUENCE" NUMBER, 
	"EDITION_CODE" VARCHAR2(4 BYTE), 
	"EDITION_ONIX_NAME" VARCHAR2(50 BYTE), 
	"EDITION_DESC" VARCHAR2(250 BYTE), 
	"DBCS_CREATE_TIMESTAMP" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(240 BYTE), 
	"DBCS_UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(240 BYTE), 
	"HBG_PROCESS_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_PIM_PEM_STG" TO "RO_HBG_INTEGRATION";
