--------------------------------------------------------
--  DDL for Table HBG_ITEM_HOT_TITLES_EXT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_ITEM_HOT_TITLES_EXT" 
   (	"INVENTORY_ITEM_ID" NUMBER, 
	"CUSTOMER_ACCOUNT" VARCHAR2(200 BYTE), 
	"THRESHOLD_QUANTITY" NUMBER, 
	"OVERRIDE_INDICATOR" VARCHAR2(200 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"HOT_TITLE_ROWNUM" NUMBER, 
	"ORGANIZATION_CODE" VARCHAR2(200 BYTE), 
	"HOT_TITLE_INDICATOR" VARCHAR2(5 BYTE), 
	"ITEM_NUMBER" VARCHAR2(200 BYTE), 
	"OIC_RUN_ID" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"STATUS_MESSAGE" CLOB, 
	"ORGANIZATION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("STATUS_MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_ITEM_HOT_TITLES_EXT" TO "RO_HBG_INTEGRATION";
