--------------------------------------------------------
--  Constraints for Table INV_ORG_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."INV_ORG_PARAMETERS" ADD CONSTRAINT "INV_ORG_PARAMETERS_PK1" PRIMARY KEY ("ORGANIZATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
