--------------------------------------------------------
--  DDL for Index INV_ONHAND_QUANTITIES_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBG_INTEGRATION"."INV_ONHAND_QUANTITIES_DETAIL_PK" ON "HBG_INTEGRATION"."XXHBG_INV_ONHAND_QUANTITIES_DETAIL_SYNC" ("ONHAND_QUANTITIES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
