--------------------------------------------------------
--  DDL for Table QP_PRICE_LIST_ITEMS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."QP_PRICE_LIST_ITEMS" 
   (	"PRICE_LIST_ITEM_ID" NUMBER, 
	"STRUCTURE_DATE" TIMESTAMP (6), 
	"SERVICE_DURATION" NUMBER, 
	"SERVICE_DURATION_PERIOD_CODE" VARCHAR2(40 BYTE), 
	"PRICE_LIST_ID" NUMBER, 
	"LINE_TYPE_CODE" VARCHAR2(120 BYTE), 
	"ITEM_LEVEL_CODE" VARCHAR2(120 BYTE), 
	"ITEM_ID" NUMBER, 
	"PRICING_UOM_CODE" VARCHAR2(12 BYTE), 
	"PRIMARY_PRICING_UOM_FLAG" VARCHAR2(120 BYTE), 
	"CATALOG_ID" NUMBER, 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR1" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR2" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR3" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR4" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR5" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR6" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR7" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR8" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR9" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR10" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR11" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR12" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR13" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR14" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR15" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR16" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR17" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR18" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR19" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_CHAR20" VARCHAR2(600 BYTE), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_TIMESTAMP2" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP1" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP3" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP4" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP5" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."QP_PRICE_LIST_ITEMS" TO "RO_HBG_INTEGRATION";
