--------------------------------------------------------
--  Constraints for Table XXHBG_INV_ONHAND_QUANTITIES_DETAIL_SYNC
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_INV_ONHAND_QUANTITIES_DETAIL_SYNC" ADD CONSTRAINT "INV_ONHAND_QUANTITIES_DETAIL_PK" PRIMARY KEY ("ONHAND_QUANTITIES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
