--------------------------------------------------------
--  Constraints for Table XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL" MODIFY ("DIST_CHNL_ASSIGN_ID" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL" MODIFY ("ACCOUNT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL" MODIFY ("ACCOUNT_NAME" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL" MODIFY ("SALES_FORCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL" MODIFY ("SALES_FORCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL" ADD PRIMARY KEY ("DIST_CHNL_ASSIGN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
