--------------------------------------------------------
--  DDL for Table XXHBG_LOGS_CONFIG
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_LOGS_CONFIG" 
   (	"MODULE" VARCHAR2(1000 BYTE), 
	"LOG_LEVEL" VARCHAR2(50 BYTE), 
	"LOG_LEVEL_NUM" NUMBER, 
	"ENABLED" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_LOGS_CONFIG" TO "RO_HBG_INTEGRATION";
