--------------------------------------------------------
--  DDL for Table XXHBG_FAMILYCODE_FORMAT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_FAMILYCODE_FORMAT" 
   (	"FORMAT_ID" NUMBER, 
	"FORMAT_CODE" VARCHAR2(200 BYTE), 
	"FORMAT_NAME" VARCHAR2(200 BYTE), 
	"FORMAT_ABBR" VARCHAR2(200 BYTE), 
	"EBOOK_IND" VARCHAR2(200 BYTE), 
	"NONPUB_ITEM_IND" VARCHAR2(200 BYTE), 
	"AUDIO_IND" VARCHAR2(200 BYTE), 
	"INC_SALE_IND" VARCHAR2(200 BYTE), 
	"CAL_IND" VARCHAR2(200 BYTE), 
	"COMMODITY_CODE" VARCHAR2(200 BYTE), 
	"REQUIRE_SUB_FMT_IND" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_FAMILYCODE_FORMAT" TO "RO_HBG_INTEGRATION";
