--------------------------------------------------------
--  Ref Constraints for Table XXHBG_SF_ACCT_TYPE_TBL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" ADD FOREIGN KEY ("SF_SALES_REP_ID")
	  REFERENCES "HBG_INTEGRATION"."XXHBG_SALES_FORCE_SALES_REP_TBL" ("SF_SALES_REP_ID") ENABLE;
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" ADD FOREIGN KEY ("SALES_FORCE_ID")
	  REFERENCES "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAINTENANCE_TBL" ("SALES_FORCE_ID") ENABLE;
