--------------------------------------------------------
--  DDL for Table XXHBG_EGP_ITEM_CATEGORIES_INTERFACE
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_EGP_ITEM_CATEGORIES_INTERFACE" 
   (	"INTERFACE_STAGE_ID" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(200 BYTE), 
	"BATCH_ID" VARCHAR2(200 BYTE), 
	"BATCH_NUMBER" VARCHAR2(200 BYTE), 
	"ITEM_NUMBER" VARCHAR2(200 BYTE), 
	"ORGANIZATION_CODE" VARCHAR2(200 BYTE), 
	"CATALOG_CATEGORY_NAME" VARCHAR2(200 BYTE), 
	"CATEGORY_CODE" VARCHAR2(200 BYTE), 
	"OLD_CATEGORY_NAME" VARCHAR2(200 BYTE), 
	"OLD_CATEGORY_CODE" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_CODE" VARCHAR2(200 BYTE), 
	"SOURCE_SYSTEM_REFERENCE" VARCHAR2(200 BYTE), 
	"START_DATE" VARCHAR2(200 BYTE), 
	"END_DATE" VARCHAR2(200 BYTE), 
	"OIC_RUN_ID" NUMBER, 
	"STAGE_ID" NUMBER, 
	"STATUS" VARCHAR2(200 BYTE), 
	"STATUS_MESSAGE" CLOB, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"IMPORT_REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("STATUS_MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_EGP_ITEM_CATEGORIES_INTERFACE" TO "RO_HBG_INTEGRATION";
