--------------------------------------------------------
--  DDL for Sequence XXHBG_DISTRUBUTION_CHANNEL_TBL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_DISTRUBUTION_CHANNEL_TBL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1028 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
