--------------------------------------------------------
--  DDL for Table XXHBG_RES_PRE_RESERVATION_LOT_NUM_CREATE
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_LOT_NUM_CREATE" 
   (	"ITEM_CODE" NUMBER, 
	"ISBN_ON_BOOK" NUMBER, 
	"SHORT_TITLE" VARCHAR2(200 BYTE), 
	"SHORT_AUTHOR" VARCHAR2(200 BYTE), 
	"PUBLICATION_STATUS" VARCHAR2(20 BYTE), 
	"RETURN_RANKING" NUMBER, 
	"RETURN_DISPOSITION_CODE" NUMBER, 
	"OWNER_CODE" NUMBER, 
	"OWNER_NAME" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP" NUMBER, 
	"REPORTING_GROUP_NAME" VARCHAR2(200 BYTE), 
	"CATEGORY_1" NUMBER, 
	"CATEGORY_1_NAME" VARCHAR2(200 BYTE), 
	"CATEGORY_2" NUMBER, 
	"CATEGORY_2_NAME" VARCHAR2(200 BYTE), 
	"INVENTORY_ORGANIZATION" VARCHAR2(200 BYTE), 
	"LOT" NUMBER, 
	"SUBINVENTORY" VARCHAR2(200 BYTE), 
	"PRICE_STATUS" VARCHAR2(20 BYTE), 
	"END_BALANCE" NUMBER, 
	"PRE_RESERVED_QUANTITY" NUMBER, 
	"RESERVED_QUANTITY" NUMBER, 
	"USABLE_BALANCE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_LOT_NUM_CREATE" TO "RO_HBG_INTEGRATION";
