--------------------------------------------------------
--  DDL for Table AR_RECEIVABLES_ACTIVITY
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."AR_RECEIVABLES_ACTIVITY" 
   (	"RECEIVABLES_TRX_ID" NUMBER, 
	"TYPE" VARCHAR2(50 BYTE), 
	"CODE_COMBINATION_ID" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"NAME" VARCHAR2(100 BYTE), 
	"SEG_NAME" VARCHAR2(50 BYTE), 
	"SEG_DESC" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
