--------------------------------------------------------
--  Constraints for Table DOO_LINES_ALL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."DOO_LINES_ALL" ADD CONSTRAINT "DOO_LINES_ALL_PK" PRIMARY KEY ("LINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
