--------------------------------------------------------
--  DDL for Table FND_DOC_CATEGORIES_TO_ENTITIES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."FND_DOC_CATEGORIES_TO_ENTITIES" 
   (	"CATEGORY_ID" NUMBER, 
	"DOCUMENT_ENTITY_ID" NUMBER, 
	"ENTERPRISE_ID" NUMBER, 
	"MODULE_ID" VARCHAR2(128 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"SEED_DATA_SOURCE" VARCHAR2(2048 BYTE), 
	"ORA_SEED_SET1" VARCHAR2(4 BYTE), 
	"ORA_SEED_SET2" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
