--------------------------------------------------------
--  DDL for Table HBG_EGO_ITEM_ASSOCIATIONS_INTF
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_EGO_ITEM_ASSOCIATIONS_INTF" 
   (	"TRANSACTION_TYPE" VARCHAR2(10 BYTE), 
	"BATCH_ID" NUMBER(18,0), 
	"BATCH_NUMBER" VARCHAR2(40 BYTE), 
	"ITEM_NUMBER" VARCHAR2(700 BYTE), 
	"ORGANIZATION_CODE" VARCHAR2(18 BYTE), 
	"SOURCE_SYSTEM_CODE" VARCHAR2(30 BYTE), 
	"SOURCE_SYSTEM_REFERENCE" VARCHAR2(255 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(1 BYTE), 
	"STATUS_CODE" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"SUPPLIER_NUMBER" VARCHAR2(30 BYTE), 
	"SUPPLIER_SITE_NAME" VARCHAR2(240 BYTE), 
	"VERSION_START_DATE" DATE, 
	"VERSION_REVISION_CODE" VARCHAR2(18 BYTE), 
	"STYLE_ITEM_FLAG" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"ERROR_TEXT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_EGO_ITEM_ASSOCIATIONS_INTF" TO "RO_HBG_INTEGRATION";
