--------------------------------------------------------
--  DDL for Table HBG_PIM_CONVERSION
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PIM_CONVERSION" 
   (	"ISBN" VARCHAR2(25 BYTE), 
	"ITEM_DESCRIPTION" NVARCHAR2(200), 
	"AUTHOR_NAME" VARCHAR2(255 BYTE), 
	"PUBLICATION_DATE" DATE, 
	"OWNER" VARCHAR2(100 BYTE), 
	"REPORTING_GROUP" VARCHAR2(2 BYTE), 
	"CATEGORY_1" VARCHAR2(2 BYTE), 
	"CATEGORY_2" VARCHAR2(2 BYTE), 
	"EXTERNAL_PUBLISHER" VARCHAR2(2 BYTE), 
	"EXTERNAL_IMPRINT" VARCHAR2(2 BYTE), 
	"FORMAT" VARCHAR2(2 BYTE), 
	"SUBFORMAT" VARCHAR2(2 BYTE), 
	"ASSOCIATED_FORMAT" VARCHAR2(2 BYTE), 
	"ASSOCIATED_SUBFORMAT" VARCHAR2(2 BYTE), 
	"DISCOUNT_GROUP" VARCHAR2(3 BYTE), 
	"SHORT_TITLE" NVARCHAR2(50), 
	"DIGITAL_CONTENT" VARCHAR2(2 BYTE), 
	"BISAC1" NVARCHAR2(64), 
	"BISAC2" NVARCHAR2(64), 
	"BISAC3" NVARCHAR2(64)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_PIM_CONVERSION" TO "RO_HBG_INTEGRATION";
