--------------------------------------------------------
--  DDL for Table HBG_AR_PAYMENTS_ARCHIVE
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AR_PAYMENTS_ARCHIVE" 
   (	"BATCH_ID" NUMBER, 
	"OIC_INSTANCE_ID" VARCHAR2(1024 BYTE), 
	"BUSINESS_UNIT" VARCHAR2(100 BYTE), 
	"PAYMENT_TYPE" VARCHAR2(100 BYTE), 
	"PAYMENT_DATE" DATE, 
	"ACCOUNT_NUMBER" VARCHAR2(255 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(524 BYTE), 
	"RECEIPT_NUMBER" VARCHAR2(255 BYTE), 
	"AMOUNT" NUMBER, 
	"PAYMENT_METHOD" VARCHAR2(255 BYTE), 
	"CURRENCY" VARCHAR2(32 BYTE), 
	"GL_ACCOUNT" VARCHAR2(255 BYTE), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
