--------------------------------------------------------
--  DDL for Table HBG_EXPECTED_RECEIPTS_INT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_EXPECTED_RECEIPTS_INT" 
   (	"EXP_RCPT_HDR_UID" NUMBER, 
	"RECEIPT_TYPE" VARCHAR2(5 BYTE), 
	"REFERENCE_NBR" VARCHAR2(20 BYTE), 
	"ORIGIN_CODE" VARCHAR2(20 BYTE), 
	"WORK_ORDER_UID" NUMBER, 
	"DATE_SHIPPED" TIMESTAMP (6), 
	"DATE_EXPECTED" TIMESTAMP (6), 
	"RECEIPT_LINE" NUMBER, 
	"OTC_RECEIPT_NBR" VARCHAR2(24 BYTE), 
	"ITEM_ID" VARCHAR2(100 BYTE), 
	"PUB_ITEM_ID" VARCHAR2(30 BYTE), 
	"INV_TYPE" VARCHAR2(20 BYTE), 
	"PRINTING_NBR" NUMBER, 
	"PRINT_VERSION_NBR" NUMBER, 
	"CFG_CODE" VARCHAR2(50 BYTE), 
	"HOLD_CODE" VARCHAR2(50 BYTE), 
	"PIECES_EXPECTED" NUMBER, 
	"LINE_CLOSED_FLAG" VARCHAR2(1 BYTE), 
	"EXPECTED_RECEIPT_TYPE" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
