--------------------------------------------------------
--  DDL for Table HBG_CX_ORDERS_JOB_TRACKER
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CX_ORDERS_JOB_TRACKER" 
   (	"INSTANCEID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"ERRBUF" VARCHAR2(2000 BYTE), 
	"RETCODE" NUMBER, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
