--------------------------------------------------------
--  DDL for Table HBG_INTEGRATION_CONTROL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_INTEGRATION_CONTROL" 
   (	"CONTROL_ID" NUMBER DEFAULT "HBG_INTEGRATION"."HBG_INTEGRATION_CONTROL_SEQ"."NEXTVAL", 
	"HBG_PROCESS_ID" NUMBER, 
	"OIC_INSTANCE_ID" NUMBER, 
	"INTERFACE_NAME" VARCHAR2(250 BYTE), 
	"STEP_NAME" VARCHAR2(250 BYTE), 
	"STEP_NUMBER" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE), 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_TS_DEBUG" ;
