--------------------------------------------------------
--  DDL for Table HBG_STERLING_SHIPTO_SAN
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_STERLING_SHIPTO_SAN" 
   (	"CUSTOMER_NUMBER" NUMBER, 
	"CUSTOMER_NAME" VARCHAR2(200 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(200 BYTE), 
	"BILLTO_SAN" VARCHAR2(10 BYTE), 
	"SITE_NUMBER" VARCHAR2(30 BYTE), 
	"SHIPTO_SAN" VARCHAR2(10 BYTE), 
	"ORACLE_ACCT_NO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_STERLING_SHIPTO_SAN" TO "RO_HBG_INTEGRATION";
