--------------------------------------------------------
--  DDL for Table HBG_CX_ITEMS_INTEGRATION_TRACKER
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CX_ITEMS_INTEGRATION_TRACKER" 
   (	"INSTANCEID" NUMBER, 
	"JOB_STATUS" VARCHAR2(100 BYTE), 
	"ERRBUF" VARCHAR2(4000 BYTE), 
	"RETCODE" NUMBER, 
	"REPORT_FILE" VARCHAR2(20 BYTE), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_CX_ITEMS_INTEGRATION_TRACKER" TO "RO_HBG_INTEGRATION";
