--------------------------------------------------------
--  DDL for Table HBG_AR_TRXMAINT_TRXCODES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AR_TRXMAINT_TRXCODES" 
   (	"TRANSACTION_CODE" VARCHAR2(50 BYTE), 
	"TYPE_DESC" VARCHAR2(50 BYTE), 
	"TRAN_TYPE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"TRAN_RECORD_TYPE" VARCHAR2(50 BYTE), 
	"BATCH_USER" VARCHAR2(50 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_AR_TRXMAINT_TRXCODES" TO "RO_HBG_INTEGRATION";
