--------------------------------------------------------
--  DDL for Index IDX1_HBG_EGP_TRADING_PARTNER_ITEMS_INTF
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."IDX1_HBG_EGP_TRADING_PARTNER_ITEMS_INTF" ON "HBG_INTEGRATION"."HBG_EGP_TRADING_PARTNER_ITEMS_INTF" ("BATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
