--------------------------------------------------------
--  DDL for Table TASK_TEST
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."TASK_TEST" 
   (	"TASKID" VARCHAR2(100 BYTE), 
	"TSUBJECT" VARCHAR2(100 BYTE), 
	"TREQUESTER" VARCHAR2(100 BYTE), 
	"TASSIGNEDTO" VARCHAR2(100 BYTE), 
	"TDUEDATE" VARCHAR2(100 BYTE), 
	"TSTATUS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."TASK_TEST" TO "RO_HBG_INTEGRATION";
