--------------------------------------------------------
--  DDL for Table TEST2
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."TEST2" 
   (	"SNAME" VARCHAR2(200 BYTE), 
	"SNUMBER" VARCHAR2(200 BYTE), 
	"SNBU" VARCHAR2(200 BYTE), 
	"SNS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."TEST2" TO "RO_HBG_INTEGRATION";
