--------------------------------------------------------
--  DDL for Index XXDOO_ORDER_BILLING_PLANS_INT_N1
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."XXDOO_ORDER_BILLING_PLANS_INT_N1" ON "HBG_INTEGRATION"."XXDOO_ORDER_BILLING_PLANS_INT" ("SOURCE_TRANSACTION_ID", "SOURCE_TRANSACTION_SYSTEM", "LOAD_REQUEST_ID", "SOURCE_TRANSACTION_LINE_ID", "SOURCE_TRANSACTION_SCHEDULE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
