--------------------------------------------------------
--  DDL for Trigger XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_TRG" BEFORE
    INSERT ON "XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT"
    FOR EACH ROW
BEGIN
    IF :new.IMPR_ID IS NULL THEN
        SELECT
            XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_SEQ.NEXTVAL
        INTO :new.IMPR_ID
        FROM
            sys.dual;

    END IF;
END;
/
ALTER TRIGGER "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_TRG" ENABLE;
