--------------------------------------------------------
--  DDL for Table XXHBG_SAAS_DATA_SYNC_RUN
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_SAAS_DATA_SYNC_RUN" 
   (	"RUN_ID" NUMBER, 
	"OBJECT_ID" NUMBER, 
	"XML_RESPONSE" "SYS"."XMLTYPE" , 
	"CREATION_DATE" TIMESTAMP (6), 
	"RUN_STATUS_CODE" VARCHAR2(1 BYTE), 
	"RUN_STATUS_MESSAGE" VARCHAR2(4000 BYTE), 
	"BATCH_NUMBER" NUMBER, 
	"ROWS_MERGED" NUMBER, 
	"SYNC_MODE" VARCHAR2(20 BYTE), 
	"BATCH_SIZE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_TS_DEBUG" 
 XMLTYPE COLUMN "XML_RESPONSE" STORE AS SECUREFILE BINARY XML (
  TABLESPACE "HBG_TS_DEBUG" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_SAAS_DATA_SYNC_RUN" TO "RO_HBG_INTEGRATION";
