--------------------------------------------------------
--  DDL for Index XXHBG_SALES_FORCE_SALES_REP_TBL_IDX
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."XXHBG_SALES_FORCE_SALES_REP_TBL_IDX" ON "HBG_INTEGRATION"."XXHBG_SALES_FORCE_SALES_REP_TBL" ("SF_SALES_REP_ID", "SALES_REP_NUMBER", "SALES_REP_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
