--------------------------------------------------------
--  DDL for Table XXHBG_RES_PRE_RESERVATION_LINES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_LINES" 
   (	"ITEM_CODE" VARCHAR2(200 BYTE), 
	"ISBN_ON_BOOK" VARCHAR2(200 BYTE), 
	"SHORT_TITLE" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"RESERVATION_TYPE" VARCHAR2(20 BYTE), 
	"PRINT_NUMBER" VARCHAR2(200 BYTE), 
	"INVENTORY_ORGANIZATION" VARCHAR2(200 BYTE), 
	"LOT_NUMBER" VARCHAR2(200 BYTE), 
	"SUBINVENTORY" VARCHAR2(200 BYTE), 
	"REQUESTED_QUANTITY" NUMBER, 
	"RESERVED_QUANTITY" NUMBER, 
	"RELEASED_VIA_CUID" NUMBER, 
	"AVAILABLE_RESERVED" NUMBER, 
	"IP_ONLY" VARCHAR2(20 BYTE), 
	"PRE_RESERVED_BALANCE" NUMBER, 
	"USABLE_BALANCE" NUMBER, 
	"END_BALANCE" NUMBER, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"RESERVATION_NUMBER" NUMBER, 
	"RECORD_ID" NUMBER, 
	"PO_NUMBER" VARCHAR2(200 BYTE), 
	"WO_NUMBER" VARCHAR2(200 BYTE), 
	"ERP_RESERVATION_ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_LINES" TO "RO_HBG_INTEGRATION";
