--------------------------------------------------------
--  Constraints for Table XXHBG_FAMILY_CODE_REPORTING_CATEGORY2
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_CATEGORY2" ADD CONSTRAINT "PK_CAT2" PRIMARY KEY ("CATEGORY2_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
