--------------------------------------------------------
--  DDL for Sequence XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999999999 INCREMENT BY 1 START WITH 441 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
