--------------------------------------------------------
--  DDL for Table XXHBG_SS_SHIPPING_SCHEDULE_TYPE_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_SS_SHIPPING_SCHEDULE_TYPE_TEMPLATE" 
   (	"ADD_ITEMS_AUTOMATICALLY" VARCHAR2(20 BYTE), 
	"REMOVE_ITEMS_AUTOMATICALLY" VARCHAR2(20 BYTE), 
	"ON_SALE_DATE_EDITABLE" VARCHAR2(20 BYTE), 
	"ON_SALE_DATE_REQUIRED" VARCHAR2(20 BYTE), 
	"RELEASE_DATE_EDITABLE" VARCHAR2(20 BYTE), 
	"RELEASE_DATE_REQUIRED" VARCHAR2(20 BYTE), 
	"RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER, 
	"CUTOFF_DATE_EDITABLE" VARCHAR2(20 BYTE), 
	"CUTOFF_DATE_REQUIRED" VARCHAR2(20 BYTE), 
	"CUTOFF_DATE_SUBTRACT_FROM_RELEASE_DATE" NUMBER, 
	"CLEANUP_RELEASE_DATE_EDITABLE" VARCHAR2(20 BYTE), 
	"CLEANUP_RELEASE_DATE_REQUIRED" VARCHAR2(20 BYTE), 
	"CLEANUP_RELEASE_DATE_SUBTRACT_FROM_OSD" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
