--------------------------------------------------------
--  DDL for Table DOO_ORDER_ADDRESSES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."DOO_ORDER_ADDRESSES" 
   (	"ADDRESS_ID" NUMBER, 
	"HEADER_ID" NUMBER, 
	"PARTY_ID" NUMBER, 
	"FULFILL_LINE_ID" NUMBER, 
	"CUST_ACCT_ID" NUMBER, 
	"PARTY_SITE_ID" NUMBER, 
	"CUST_ACCT_SITE_USE_ID" NUMBER, 
	"ADDRESS_USE_TYPE" VARCHAR2(120 BYTE), 
	"CONTACT_ID" NUMBER, 
	"CUST_ACCOUNT_CONTACT_ID" NUMBER, 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"PREF_CONTACT_POINT_ID" NUMBER, 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"REFERENCE_ADDRESS_ID" NUMBER, 
	"DELTA_TYPE" NUMBER, 
	"MODIFIED_FLAG" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."DOO_ORDER_ADDRESSES" TO "RO_HBG_INTEGRATION";
