--------------------------------------------------------
--  DDL for Type DOO_SO_MAAS_BILLING_PLANS_RT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."DOO_SO_MAAS_BILLING_PLANS_RT" FORCE AS OBJECT
(
    SOURCE_TRANSACTION_ID            VARCHAR2 (200),
    SOURCE_TRANSACTION_SYSTEM        VARCHAR2 (120),
    SOURCE_TRANSACTION_LINE_ID       VARCHAR2 (200),
    SOURCE_TRANSACTION_SCHEDULE_ID   VARCHAR2 (200),
    BILLING_PLAN_TYPE_CODE           VARCHAR2 (120),
    PERIODICITY_CODE                 VARCHAR2 (120),
    NUMBER_OF_BILLING_PERIODS        NUMBER,
    BILLING_PERIOD_START_DATE        DATE,
    BILLING_PERIOD_END_DATE          DATE,
    BILLING_TRANSACTION_DATE         DATE,
    BILLING_PERIOD_NUMBER            NUMBER,
    OVERRIDE_PERIOD                  NUMBER,
    OVERRIDE_PERIOD_QUANTITY         NUMBER,
    OVERRIDE_PERIOD_AMOUNT           NUMBER,
    CANCELLATION_EFFECTIVE_DATE      DATE,
    SOURCE_BILLING_PLAN_ID           VARCHAR2 (200),
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_BILLING_PLANS_RT" RETURN SELF AS RESULT
);
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "HBG_INTEGRATION"."DOO_SO_MAAS_BILLING_PLANS_RT" 
AS
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_BILLING_PLANS_RT"
        RETURN SELF AS RESULT
    AS
    BEGIN
        RETURN;
    END;
END;

/
