--------------------------------------------------------
--  DDL for Type DOO_SO_MAAS_CHARGE_COMPS_RT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."DOO_SO_MAAS_CHARGE_COMPS_RT" FORCE AS OBJECT
(
    SOURCE_TRANSACTION_ID            VARCHAR2 (200),
    SOURCE_MPA_ID                    VARCHAR2 (200),
    SOURCE_TRANSACTION_SYSTEM        VARCHAR2 (120),
    SOURCE_TRANSACTION_LINE_ID       VARCHAR2 (200),
    SOURCE_TRANSACTION_SCHEDULE_ID   VARCHAR2 (200),
    SOURCE_CHARGE_ID                 VARCHAR2 (200),
    SOURCE_CHARGE_COMPONENT_ID       VARCHAR2 (200),
    SEQUENCE_NUMBER                  NUMBER,
    SOURCE_PARENT_CHARGE_COMP_ID     VARCHAR2 (200),
    CHARGE_CURRENCY_CODE             VARCHAR2 (4000),
    CHARGE_CURRENCY_NAME             VARCHAR2 (4000),
    CHARGE_CURRENCY_EXT_AMOUNT       NUMBER,
    CHARGE_CURRENCY_UNIT_PRICE       NUMBER,
    HEADER_CURRENCY_CODE             VARCHAR2 (4000),
    HEADER_CURRENCY_NAME             VARCHAR2 (4000),
    HEADER_CURRENCY_EXT_AMOUNT       NUMBER,
    HEADER_CURRENCY_UNIT_PRICE       NUMBER,
    PRICE_ELEMENT_CODE               VARCHAR2 (120),
    PRICE_ELEMENT                    VARCHAR2 (960),
    PRICE_ELEMENT_USAGE_CODE         VARCHAR2 (120),
    PRICE_ELEMENT_USAGE              VARCHAR2 (960),
    ROLLUP_FLAG                      VARCHAR2 (4),
    TRANSACTIONAL_CURRENCY_CODE      VARCHAR2 (4000),
    EXPLANATION                      VARCHAR2 (4000),
    CHARGE_CURR_DURATION_EXT_AMT     NUMBER,
    HEADER_CURR_DURATION_EXT_AMT     NUMBER,
    BATCH_ID                         NUMBER,
    VALIDATION_BITSET                NUMBER,
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_CHARGE_COMPS_RT" RETURN SELF AS RESULT
);
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "HBG_INTEGRATION"."DOO_SO_MAAS_CHARGE_COMPS_RT" 
AS
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_CHARGE_COMPS_RT"
        RETURN SELF AS RESULT
    AS
    BEGIN
        RETURN;
    END;
END;

/
