--------------------------------------------------------
--  DDL for Type DOO_SO_MAAS_HDRS_ALL_EFF_B_RT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "HBG_INTEGRATION"."DOO_SO_MAAS_HDRS_ALL_EFF_B_RT" FORCE AS OBJECT
(
    SOURCE_TRANSACTION_ID       VARCHAR2 (200),
    SOURCE_TRANSACTION_SYSTEM   VARCHAR2 (120),
    CONTEXT_CODE                VARCHAR2 (320),
    ATTRIBUTE_CHAR1             VARCHAR2 (600),
    ATTRIBUTE_CHAR2             VARCHAR2 (600),
    ATTRIBUTE_CHAR3             VARCHAR2 (600),
    ATTRIBUTE_CHAR4             VARCHAR2 (600),
    ATTRIBUTE_CHAR5             VARCHAR2 (600),
    ATTRIBUTE_CHAR6             VARCHAR2 (600),
    ATTRIBUTE_CHAR7             VARCHAR2 (600),
    ATTRIBUTE_CHAR8             VARCHAR2 (600),
    ATTRIBUTE_CHAR9             VARCHAR2 (600),
    ATTRIBUTE_CHAR10            VARCHAR2 (600),
    ATTRIBUTE_CHAR11            VARCHAR2 (600),
    ATTRIBUTE_CHAR12            VARCHAR2 (600),
    ATTRIBUTE_CHAR13            VARCHAR2 (600),
    ATTRIBUTE_CHAR14            VARCHAR2 (600),
    ATTRIBUTE_CHAR15            VARCHAR2 (600),
    ATTRIBUTE_CHAR16            VARCHAR2 (600),
    ATTRIBUTE_CHAR17            VARCHAR2 (600),
    ATTRIBUTE_CHAR18            VARCHAR2 (600),
    ATTRIBUTE_CHAR19            VARCHAR2 (600),
    ATTRIBUTE_CHAR20            VARCHAR2 (600),
    ATTRIBUTE_NUMBER1           NUMBER,
    ATTRIBUTE_NUMBER2           NUMBER,
    ATTRIBUTE_NUMBER3           NUMBER,
    ATTRIBUTE_NUMBER4           NUMBER,
    ATTRIBUTE_NUMBER5           NUMBER,
    ATTRIBUTE_NUMBER6           NUMBER,
    ATTRIBUTE_NUMBER7           NUMBER,
    ATTRIBUTE_NUMBER8           NUMBER,
    ATTRIBUTE_NUMBER9           NUMBER,
    ATTRIBUTE_NUMBER10          NUMBER,
    ATTRIBUTE_DATE1             DATE,
    ATTRIBUTE_DATE2             DATE,
    ATTRIBUTE_DATE3             DATE,
    ATTRIBUTE_DATE4             DATE,
    ATTRIBUTE_DATE5             DATE,
    ATTRIBUTE_TIMESTAMP1        TIMESTAMP (6),
    ATTRIBUTE_TIMESTAMP2        TIMESTAMP (6),
    ATTRIBUTE_TIMESTAMP3        TIMESTAMP (6),
    ATTRIBUTE_TIMESTAMP4        TIMESTAMP (6),
    ATTRIBUTE_TIMESTAMP5        TIMESTAMP (6),
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_HDRS_ALL_EFF_B_RT" RETURN SELF AS RESULT
);
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "HBG_INTEGRATION"."DOO_SO_MAAS_HDRS_ALL_EFF_B_RT" 
AS
    CONSTRUCTOR FUNCTION "DOO_SO_MAAS_HDRS_ALL_EFF_B_RT"
        RETURN SELF AS RESULT
    AS
    BEGIN
        RETURN;
    END;
END;

/
