--------------------------------------------------------
--  DDL for Table DOO_HOLD_CODES_TL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."DOO_HOLD_CODES_TL" 
   (	"HOLD_CODE_ID" NUMBER, 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"HOLD_NAME" VARCHAR2(960 BYTE), 
	"HOLD_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"LANGUAGE" VARCHAR2(16 BYTE), 
	"SOURCE_LANG" VARCHAR2(16 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"ORCHESTRATION_APPLICATION_ID" NUMBER, 
	"SEED_DATA_SOURCE" VARCHAR2(2048 BYTE), 
	"ORA_SEED_SET1" VARCHAR2(4 BYTE), 
	"ORA_SEED_SET2" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."DOO_HOLD_CODES_TL" TO "RO_HBG_INTEGRATION";
