--------------------------------------------------------
--  DDL for Table FND_DOCUMENT_ENTITIES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."FND_DOCUMENT_ENTITIES" 
   (	"ENTERPRISE_ID" NUMBER, 
	"DOCUMENT_ENTITY_ID" NUMBER, 
	"DATA_OBJECT_CODE" VARCHAR2(120 BYTE), 
	"MODULE_ID" VARCHAR2(128 BYTE), 
	"APPLICATION_ID" NUMBER, 
	"TABLE_NAME" VARCHAR2(120 BYTE), 
	"ENTITY_NAME" VARCHAR2(160 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"PK1_COLUMN" VARCHAR2(600 BYTE), 
	"PK2_COLUMN" VARCHAR2(600 BYTE), 
	"PK3_COLUMN" VARCHAR2(600 BYTE), 
	"PK4_COLUMN" VARCHAR2(600 BYTE), 
	"PK5_COLUMN" VARCHAR2(600 BYTE), 
	"DM_REPOSITORY" VARCHAR2(320 BYTE), 
	"DEFAULT_FOLDER" VARCHAR2(4000 BYTE), 
	"CATEGORY_SECURITY_ENABLED" VARCHAR2(4 BYTE), 
	"EXPIRATION_ENABLED" VARCHAR2(4 BYTE), 
	"SEED_DATA_SOURCE" VARCHAR2(2048 BYTE), 
	"ORA_SEED_SET1" VARCHAR2(4 BYTE), 
	"ORA_SEED_SET2" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
