--------------------------------------------------------
--  DDL for Table HBG_PIM_PCA
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PIM_PCA" 
   (	"ISBN13" VARCHAR2(13 BYTE), 
	"CONTACT_KEY" NUMBER(19,0), 
	"GLOBAL_CONTACT_KEY" NUMBER(19,0), 
	"ROLE_CODE" NVARCHAR2(40), 
	"ROLE_DESC" NVARCHAR2(500), 
	"CNTB_SEQUENCE" NUMBER(19,0), 
	"PREFIX" NVARCHAR2(75), 
	"SUFFIX" NVARCHAR2(75), 
	"DEGREE" NVARCHAR2(100), 
	"FIRST_NAME" NVARCHAR2(75), 
	"MIDDLE_NAME" NVARCHAR2(75), 
	"LAST_NAME" NVARCHAR2(75), 
	"DISPLAY_NAME" NVARCHAR2(255), 
	"GROUP_NAME" NVARCHAR2(75), 
	"CONTACT_TYPE" NVARCHAR2(120), 
	"IS_ACTIVE" NUMBER(*,0), 
	"DBCS_CREATE_TIMESTAMP" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(240 BYTE), 
	"DBCS_UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(240 BYTE), 
	"HBG_PROCESS_ID" NUMBER(20,0), 
	"OIC_INSTANCE_ID" NUMBER(20,0), 
	"STATUS" VARCHAR2(240 BYTE), 
	"ERROR_TEXT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_PIM_PCA" TO "RO_HBG_INTEGRATION";
