--------------------------------------------------------
--  DDL for Trigger HBG_DISTRIBUTION_MAINTENANCE_TBL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HBG_INTEGRATION"."HBG_DISTRIBUTION_MAINTENANCE_TBL_TRG" BEFORE
    INSERT ON "HBG_DISTRIBUTION_MAINTENANCE_TBL"
    FOR EACH ROW
BEGIN
    IF :new.DIST_MAINTEN_STG_ID IS NULL THEN
        SELECT
            HBG_DISTRIBUTION_MAINTENANCE_TBL_SEQ.NEXTVAL
        INTO :new.DIST_MAINTEN_STG_ID
        FROM
            sys.dual;

    END IF;
END;
/
ALTER TRIGGER "HBG_INTEGRATION"."HBG_DISTRIBUTION_MAINTENANCE_TBL_TRG" ENABLE;
