--------------------------------------------------------
--  DDL for Table HBG_TITLE_RIGHT_DETAILS_STG
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_TITLE_RIGHT_DETAILS_STG" 
   (	"TM_SR_UID" NUMBER, 
	"ISBN" VARCHAR2(255 BYTE), 
	"COUNTRY_CODE" VARCHAR2(5 BYTE), 
	"CATEGORY" VARCHAR2(25 BYTE), 
	"ACTIVE_INDICATOR" VARCHAR2(2 BYTE), 
	"TRANSACTION_USER" VARCHAR2(255 BYTE), 
	"TRANSACTION_DATE" DATE, 
	"LAST_UPD_USER" VARCHAR2(255 BYTE), 
	"LAST_UPD_DATE" DATE, 
	"STATUS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
