--------------------------------------------------------
--  DDL for Sequence HBG_ADIST_RIGHTS_COUNTRYGROUP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."HBG_ADIST_RIGHTS_COUNTRYGROUP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1039 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
