--------------------------------------------------------
--  Constraints for Table HBG_INTEGRATION_CONTROL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."HBG_INTEGRATION_CONTROL" MODIFY ("CONTROL_ID" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."HBG_INTEGRATION_CONTROL" ADD CONSTRAINT "HBG_INTEGRATION_CONTROL_PK" PRIMARY KEY ("CONTROL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_TS_DEBUG"  ENABLE;
