--------------------------------------------------------
--  DDL for Table HBG_DISTRIBUTION_MAINTENANCE_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_DISTRIBUTION_MAINTENANCE_TBL" 
   (	"DIST_MAINTEN_STG_ID" NUMBER, 
	"OWNER" VARCHAR2(200 BYTE), 
	"OWNER_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"REPORTING_GROUP" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"DIST_CHANNEL_ID" NUMBER, 
	"REPORTING_GROUP_DESCRIPTION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_DISTRIBUTION_MAINTENANCE_TBL" TO "RO_HBG_INTEGRATION";
