--------------------------------------------------------
--  DDL for Table HBG_STERLING_CONTROL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_STERLING_CONTROL" 
   (	"CTRL_UID" NUMBER, 
	"GIS_ID" NUMBER, 
	"SBI_UUID" VARCHAR2(50 BYTE), 
	"SOURCE_FLAG" VARCHAR2(20 BYTE), 
	"PROCESS_NAME" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"INS_TIMESTAMP" DATE, 
	"UPD_DATE_TIMESTAMP" DATE, 
	"LAST_UPD_USER" VARCHAR2(20 BYTE), 
	"INS_USER" VARCHAR2(20 BYTE), 
	"IMPORT_STATUS" VARCHAR2(100 BYTE), 
	"IMPORT_COMMENTS" VARCHAR2(4000 BYTE), 
	"IMPORT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_STERLING_CONTROL" TO "RO_HBG_INTEGRATION";
