--------------------------------------------------------
--  DDL for Table HBG_CO_RULES_HEADERS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CO_RULES_HEADERS" 
   (	"RULE_ID" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"CUST_ACCOUNT_ID" NUMBER, 
	"DESTINATION_ACCOUNT" VARCHAR2(255 BYTE), 
	"DEPARTMENT_ID" NUMBER, 
	"SALES_CHANNEL" VARCHAR2(255 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ORGANIZATION_NAME" VARCHAR2(200 BYTE), 
	"ORGANIZATION_NUMBER" VARCHAR2(200 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(200 BYTE), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(200 BYTE), 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
