--------------------------------------------------------
--  Constraints for Table HBG_INV_ONHAND_QUANTITIES_DETAIL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."HBG_INV_ONHAND_QUANTITIES_DETAIL" ADD CONSTRAINT "HBG_INV_ONHAND_QUANTITIES_DETAIL_PK" PRIMARY KEY ("ONHAND_QUANTITIES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
