--------------------------------------------------------
--  DDL for Table HBG_STERLING_SHIP
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_STERLING_SHIP" 
   (	"STAGE_ACCOUNT_NO" VARCHAR2(8 BYTE), 
	"PRESTAGE_STATUS" VARCHAR2(1 BYTE), 
	"PURCHASE_ORDER_NO" VARCHAR2(50 BYTE), 
	"SHIPTO_NO" VARCHAR2(5 BYTE), 
	"SHIPTO_SAN" VARCHAR2(8 BYTE), 
	"EDI_SHIP_ID" VARCHAR2(30 BYTE), 
	"EDI_DC_ID" VARCHAR2(30 BYTE), 
	"SHIPTO_NAME" VARCHAR2(100 BYTE), 
	"SHIPTO_ADDR1" VARCHAR2(100 BYTE), 
	"SHIPTO_ADDR2" VARCHAR2(100 BYTE), 
	"SHIPTO_ADDR3" VARCHAR2(100 BYTE), 
	"SHIPTO_ADDR4" VARCHAR2(100 BYTE), 
	"SHIPTO_CITY" VARCHAR2(100 BYTE), 
	"SHIPTO_STATE" VARCHAR2(20 BYTE), 
	"SHIPTO_POSTAL_CODE" VARCHAR2(9 BYTE), 
	"SHIPTO_COUNTRY" VARCHAR2(3 BYTE), 
	"SHIPTO_ATTENTION" VARCHAR2(100 BYTE), 
	"ORDER_SOURCE_DESC" VARCHAR2(240 BYTE), 
	"SBI_UUID" VARCHAR2(50 BYTE), 
	"GIS_HEADER_UID" NUMBER(10,0), 
	"GIS_ID" NUMBER, 
	"HEADER_UID" NUMBER, 
	"INS_TIMESTAMP" DATE, 
	"INS_USER" VARCHAR2(30 BYTE), 
	"LAST_UPD_TIMESTAMP" DATE, 
	"LAST_UPD_USER" VARCHAR2(30 BYTE), 
	"SHP_UID" NUMBER, 
	"IMPORT_STATUS" VARCHAR2(100 BYTE), 
	"IMPORT_COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_STERLING_SHIP" TO "RO_HBG_INTEGRATION";
