--------------------------------------------------------
--  DDL for Table HBG_ARTRX_WRITEOFF_RECORDS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_ARTRX_WRITEOFF_RECORDS" 
   (	"PROCESS_ID" NUMBER, 
	"CUST_ACCOUNT_ID" NUMBER, 
	"ACCOUNT_NUMBER" VARCHAR2(250 BYTE), 
	"PARTY_ID" NUMBER, 
	"ORG_NBR" VARCHAR2(250 BYTE), 
	"AMOUNT" NUMBER, 
	"GL_ACC_NUMBER" VARCHAR2(50 BYTE), 
	"GL_ACC_NAME" VARCHAR2(100 BYTE), 
	"JE_REASON" VARCHAR2(300 BYTE), 
	"JE_BATCH_NAME" VARCHAR2(200 BYTE), 
	"JE_HEADER_NAME" VARCHAR2(200 BYTE), 
	"TRX_DATE" DATE, 
	"ACTION" VARCHAR2(20 BYTE), 
	"SUBMITTED_BY" VARCHAR2(50 BYTE), 
	"SUBMISSION_DATE" DATE, 
	"SESSION_ID" NUMBER, 
	"ORCL_STATUS" VARCHAR2(50 BYTE), 
	"ORCL_ERR_MESSAGE" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
