--------------------------------------------------------
--  DDL for Table HBG_STERLING_DETAIL_DIST_STG
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_STERLING_DETAIL_DIST_STG" 
   (	"STAGE_ACCOUNT_NO" VARCHAR2(8 BYTE), 
	"PRESTAGE_STATUS" VARCHAR2(1 BYTE), 
	"PURCHASE_ORDER_NO" VARCHAR2(50 BYTE), 
	"LINE_SEQUENCE" VARCHAR2(10 BYTE), 
	"DIST_ORDER_QTY" NUMBER(7,0), 
	"EAN" VARCHAR2(13 BYTE), 
	"ISBN" VARCHAR2(20 BYTE), 
	"SKU" VARCHAR2(18 BYTE), 
	"UPC" VARCHAR2(12 BYTE), 
	"SHIPTO_NO" VARCHAR2(5 BYTE), 
	"SHIPTO_SAN" VARCHAR2(8 BYTE), 
	"EDI_SHIP_ID" VARCHAR2(30 BYTE), 
	"EDI_DC_ID" VARCHAR2(30 BYTE), 
	"DETAIL_UID" NUMBER, 
	"GIS_HEADER_UID" NUMBER(10,0), 
	"SBI_UUID" NUMBER, 
	"GIS_ID" NUMBER, 
	"HEADER_UID" NUMBER, 
	"INS_TIMESTAMP" DATE, 
	"INS_USER" VARCHAR2(30 BYTE), 
	"LAST_UPD_TIMESTAMP" DATE, 
	"LAST_UPD_USER" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_STERLING_DETAIL_DIST_STG" TO "RO_HBG_INTEGRATION";
