--------------------------------------------------------
--  DDL for Table HBG_CX_ORDER_HEADER
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CX_ORDER_HEADER" 
   (	"SYSTEM_ORDER_ID" VARCHAR2(200 BYTE), 
	"SUBMITTED_DATE" VARCHAR2(50 BYTE), 
	"SOURCE_SYSTEM" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"BILLING_ADDRESS1" VARCHAR2(200 BYTE), 
	"BILLING_ADDRESS2" VARCHAR2(200 BYTE), 
	"BILLING_ADDRESS3" VARCHAR2(200 BYTE), 
	"BILLING_ADDRESS4" VARCHAR2(200 BYTE), 
	"BILLING_CITY" VARCHAR2(200 BYTE), 
	"BILLING_STATE" VARCHAR2(200 BYTE), 
	"BILLING_POSTAL_CODE" VARCHAR2(200 BYTE), 
	"BILLING_COUNTRY" VARCHAR2(200 BYTE), 
	"SHIPPING_COUNTRY" VARCHAR2(200 BYTE), 
	"SHIPPING_POSTAL_CODE" VARCHAR2(200 BYTE), 
	"SHIPPING_STATE" VARCHAR2(200 BYTE), 
	"SHIPPING_CITY" VARCHAR2(200 BYTE), 
	"SHIPPING_ADDRESS1" VARCHAR2(200 BYTE), 
	"SHIPPING_ADDRESS2" VARCHAR2(200 BYTE), 
	"SHIPPING_ADDRESS3" VARCHAR2(200 BYTE), 
	"SHIPPING_ADDRESS4" VARCHAR2(200 BYTE), 
	"X_PO_NUMBER" VARCHAR2(200 BYTE), 
	"ACCOUNT_ID" VARCHAR2(200 BYTE), 
	"ATTN" VARCHAR2(200 BYTE), 
	"ORDER_TYPE" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"ARRIVE_BY" VARCHAR2(200 BYTE), 
	"ADDITIONAL_COMMENT" VARCHAR2(200 BYTE), 
	"CREDIT_CARD_TOKEN" VARCHAR2(200 BYTE), 
	"SHIP_TO_NOTIFICATION_EMAIL" VARCHAR2(200 BYTE), 
	"FREIGHT_TYPE" VARCHAR2(200 BYTE), 
	"SALES_CHANNEL" VARCHAR2(200 BYTE), 
	"TAX_AMOUNT" VARCHAR2(50 BYTE), 
	"PARENT_ID" VARCHAR2(20 BYTE), 
	"CX_ORDER_TYPE" VARCHAR2(200 BYTE), 
	"INTEGRATION_STATUS" VARCHAR2(15 BYTE), 
	"INTEGRATION_STATUS_ERP" VARCHAR2(200 BYTE), 
	"ORDER_USE_TYPE" VARCHAR2(100 BYTE), 
	"PHONE_NBR" VARCHAR2(100 BYTE), 
	"DEST_ATTN" VARCHAR2(100 BYTE), 
	"CANCELLATION_DATE" VARCHAR2(50 BYTE), 
	"SHIPPING_INSTRUCTIONS" VARCHAR2(4000 BYTE), 
	"GRAND_TOTAL_AMOUNT" VARCHAR2(50 BYTE), 
	"FREIGHT_COST" NUMBER, 
	"CREATION_DATE" DATE, 
	"OVERRIDE_NYP" VARCHAR2(5 BYTE), 
	"CUSTOMER_EMAIL" VARCHAR2(200 BYTE), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"IMPORT_COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_CX_ORDER_HEADER" TO "RO_HBG_INTEGRATION";
