--------------------------------------------------------
--  DDL for Table HBG_PROCESS_ORDERS_SUBMIT_BATCHES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_SUBMIT_BATCHES" 
   (	"BATCH_NAME" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
