--------------------------------------------------------
--  DDL for Table HBG_AR_PAYMENTS_SCHEDULE
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AR_PAYMENTS_SCHEDULE" 
   (	"BATCH_ID" NUMBER, 
	"OIC_INTEGRATION_ID" VARCHAR2(1024 BYTE), 
	"PROCESS_TYPE" VARCHAR2(1024 BYTE), 
	"PAYMENT_TYPE" VARCHAR2(1024 BYTE), 
	"SEQUENCE" NUMBER, 
	"LINE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
