--------------------------------------------------------
--  DDL for Table HBG_STERLING_GS1_DATA_TAGS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_STERLING_GS1_DATA_TAGS" 
   (	"SEQUENCE_ID" NUMBER, 
	"CODE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"ACTIVE" VARCHAR2(1 BYTE), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
