--------------------------------------------------------
--  DDL for Index HBG_CX_ITEMS_COL_FAILED_REC_IDX1
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."HBG_CX_ITEMS_COL_FAILED_REC_IDX1" ON "HBG_INTEGRATION"."HBG_CX_ITEMS_COL_FAILED_REC" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
