--------------------------------------------------------
--  DDL for Table HZ_GEOGRAPHY_IDENTIFIERS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HZ_GEOGRAPHY_IDENTIFIERS" 
   (	"GEOGRAPHY_IDENTIFIER_ID" NUMBER, 
	"GEOGRAPHY_ID" NUMBER, 
	"GEO_DATA_PROVIDER" VARCHAR2(120 BYTE), 
	"IDENTIFIER_SUBTYPE" VARCHAR2(120 BYTE), 
	"IDENTIFIER_VALUE" VARCHAR2(1440 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"IDENTIFIER_TYPE" VARCHAR2(120 BYTE), 
	"PRIMARY_FLAG" VARCHAR2(4 BYTE), 
	"LANGUAGE_CODE" VARCHAR2(16 BYTE), 
	"GEOGRAPHY_USE" VARCHAR2(120 BYTE), 
	"GEOGRAPHY_TYPE" VARCHAR2(120 BYTE), 
	"COUNTRY_CODE" VARCHAR2(8 BYTE), 
	"CREATED_BY_MODULE" VARCHAR2(120 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"REQUEST_ID" NUMBER, 
	"JOB_DEFINITION_NAME" VARCHAR2(400 BYTE), 
	"JOB_DEFINITION_PACKAGE" VARCHAR2(3600 BYTE), 
	"SEED_DATA_SOURCE" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HZ_GEOGRAPHY_IDENTIFIERS" TO "RO_HBG_INTEGRATION";
