--------------------------------------------------------
--  DDL for Table XXDOO_ORDER_DOC_REFERENCES_INT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXDOO_ORDER_DOC_REFERENCES_INT" 
   (	"SOURCE_TRANSACTION_LINE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_SCHEDULE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(120 BYTE), 
	"DOCUMENT_REFERENCE_TYPE" VARCHAR2(120 BYTE), 
	"DOCUMENT_ID" VARCHAR2(200 BYTE), 
	"DOCUMENT_ADDITIONAL_ID" VARCHAR2(200 BYTE), 
	"DOCUMENT_NUMBER" VARCHAR2(600 BYTE), 
	"DOCUMENT_ADDITIONAL_NUMBER" VARCHAR2(600 BYTE), 
	"DOCUMENT_LINE_ID" VARCHAR2(200 BYTE), 
	"DOCUMENT_ADDITIONAL_LINE_ID" VARCHAR2(200 BYTE), 
	"DOCUMENT_LINE_NUMBER" VARCHAR2(600 BYTE), 
	"DOCUMENT_ADDITIONAL_LINE_NO" VARCHAR2(600 BYTE), 
	"DOCUMENT_SUBLINE_ID" VARCHAR2(200 BYTE), 
	"DOCUMENT_ADDITIONAL_SUBLINE_ID" VARCHAR2(200 BYTE), 
	"DOCUMENT_SUBLINE_NUMBER" VARCHAR2(600 BYTE), 
	"DOCUMENT_ADDITIONAL_SUBLINE_NO" VARCHAR2(600 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"LOAD_REQUEST_ID" NUMBER, 
	"INTERFACE_RUN_ID" NUMBER, 
	"ICS_RUN_ID" NUMBER, 
	"SAAS_PROCESS_ID" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(4000 BYTE), 
	"FILE_NAME" VARCHAR2(240 BYTE), 
	"ICS_BATCH_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXDOO_ORDER_DOC_REFERENCES_INT" TO "RO_HBG_INTEGRATION";
