--------------------------------------------------------
--  DDL for Sequence XXHBG_XFACE_RUN_STATUS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_XFACE_RUN_STATUS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
