--------------------------------------------------------
--  DDL for Sequence XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_EXTERNAL_IMPRINT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
