--------------------------------------------------------
--  DDL for Table XXHBG_LIFE_PLANNER_ITEM_CATE_STG
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_LIFE_PLANNER_ITEM_CATE_STG" 
   (	"STAGE_ID" NUMBER, 
	"INVENTORY_ITEM_ID" NUMBER, 
	"ITEM_NUMBER" VARCHAR2(300 BYTE), 
	"ORGANIZATION_CODE" VARCHAR2(100 BYTE), 
	"CATEGORY_SET_NAME" VARCHAR2(200 BYTE), 
	"CATEGORY_CODE" VARCHAR2(200 BYTE), 
	"ENABLED_FLAG" VARCHAR2(10 BYTE), 
	"ATTRIBUTE_DATE1" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" VARCHAR2(200 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATION_DATE" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"OIC_RUN_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"STATUS_MESSAGE" CLOB, 
	"NEW_CATEGORY_CODE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("STATUS_MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_LIFE_PLANNER_ITEM_CATE_STG" TO "RO_HBG_INTEGRATION";
