--------------------------------------------------------
--  Constraints for Table XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TBL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TBL" MODIFY ("SF_ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TBL" ADD CONSTRAINT "XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TBL_PK" PRIMARY KEY ("SF_ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
