--------------------------------------------------------
--  DDL for Table XXHBG_LOGS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_LOGS" 
   (	"LOG_ID" NUMBER, 
	"MODULE" VARCHAR2(1000 BYTE), 
	"LOG_LEVEL" VARCHAR2(50 BYTE), 
	"MESSAGE_TEXT" VARCHAR2(4000 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"PROCESS_ID" NUMBER, 
	"MESSAGE_CLOB" CLOB, 
	"PACKAGE" VARCHAR2(200 BYTE), 
	"PROCEDURE" VARCHAR2(200 BYTE), 
	"CREATED_BY" VARCHAR2(150 BYTE), 
	"LOG_KEY_VALUE" VARCHAR2(150 BYTE), 
	"LOG_KEY_TYPE" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" 
 LOB ("MESSAGE_CLOB") STORE AS SECUREFILE (
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_LOGS" TO "RO_HBG_INTEGRATION";
