--------------------------------------------------------
--  DDL for Sequence XXHBG_FAMILY_CODE_REPORTING_GROUP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_GROUP_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
