--------------------------------------------------------
--  DDL for Table XXHBG_FAMILY_CODE_REPORTING_GROUP
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_GROUP" 
   (	"REPORTING_GROUP_ID" NUMBER, 
	"REPORTING_GRP_CODE" VARCHAR2(200 BYTE), 
	"REPORTING_GRP_NAME" VARCHAR2(200 BYTE), 
	"REPORTING_GRP_ABBR" VARCHAR2(200 BYTE), 
	"DISTRIBUTION_SERVICE" VARCHAR2(200 BYTE), 
	"IN_PUBTRACKER_IND" VARCHAR2(200 BYTE), 
	"DSO_REPORT_IND" VARCHAR2(200 BYTE), 
	"WMS_FEED_IND" VARCHAR2(200 BYTE), 
	"EDI_FEED_IND" VARCHAR2(200 BYTE), 
	"RETURNABLE_GRACE_DAYS" NUMBER, 
	"MANAGED_BY" VARCHAR2(200 BYTE), 
	"ACTIVE_IND" VARCHAR2(200 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"OWNER_ID" NUMBER, 
	"AUTO_CLOSE_PB_PC" NUMBER, 
	"ALL_WMS_IND" VARCHAR2(10 BYTE), 
	"NOP_WMS_IND" VARCHAR2(10 BYTE), 
	"RETURNS_NOP" VARCHAR2(20 BYTE), 
	"ACTIVE" VARCHAR2(20 BYTE), 
	"ISBN_PREFIX" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"RPG_UID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_GROUP" TO "RO_HBG_INTEGRATION";
