--------------------------------------------------------
--  DDL for Table XXHBG_RES_PRE_RESERVATION_HISTORY
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_HISTORY" 
   (	"PRE_RESERVATION_NUMBER" NUMBER, 
	"ITEM_CODE" VARCHAR2(200 BYTE), 
	"CRITERIA_UID" NUMBER, 
	"FIELD_NAME" VARCHAR2(200 BYTE), 
	"USER_NAME" VARCHAR2(200 BYTE), 
	"CHANGED_DATE" DATE, 
	"CHANGED_FROM" VARCHAR2(200 BYTE), 
	"CHANGED_TO" VARCHAR2(200 BYTE), 
	"ORDER_TYPE" VARCHAR2(200 BYTE), 
	"ORDER_REFERENCE_NUMBER" VARCHAR2(200 BYTE), 
	"PURCHASE_ORDER_NUMBER" VARCHAR2(200 BYTE), 
	"WORK_ORDER_NUMBER" VARCHAR2(200 BYTE), 
	"ORGANIZATION_NUMBER" VARCHAR2(200 BYTE), 
	"ORGANIZATION_NAME" VARCHAR2(200 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(200 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(200 BYTE), 
	"RELEASED_FROM_PRE_RESERVATION_QUANTITY" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
