--------------------------------------------------------
--  DDL for Table AS_SFTP_KNOWN_HOSTS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."AS_SFTP_KNOWN_HOSTS" 
   (	"HOST" VARCHAR2(1000 CHAR), 
	"FINGERPRINT" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."AS_SFTP_KNOWN_HOSTS" TO "RO_HBG_INTEGRATION";
