--------------------------------------------------------
--  DDL for Index FND_PROFILE_OPTION_VALUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBG_INTEGRATION"."FND_PROFILE_OPTION_VALUES_PK" ON "HBG_INTEGRATION"."FND_PROFILE_OPTION_VALUES" ("APPLICATION_ID", "PROFILE_OPTION_ID", "LEVEL_NAME", "LEVEL_VALUE", "ENTERPRISE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 159 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
