--------------------------------------------------------
--  DDL for Table HBG_INV_LOT_INT_PARAMETERS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_INV_LOT_INT_PARAMETERS" 
   (	"ID" NUMBER(4,0), 
	"PARAMETER_NAME" VARCHAR2(50 BYTE), 
	"PARAM_NUMBER1" NUMBER, 
	"PARAM_CHAR1" VARCHAR2(250 BYTE), 
	"PARAM_DATE1" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_INV_LOT_INT_PARAMETERS" TO "RO_HBG_INTEGRATION";
