--------------------------------------------------------
--  DDL for Table HBG_AUTO_HOLD_CUSTOM_RULES_EXT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AUTO_HOLD_CUSTOM_RULES_EXT" 
   (	"OWNER_NAME" VARCHAR2(255 BYTE), 
	"REPORTING_GROUP" VARCHAR2(255 BYTE), 
	"CATEGORY_1" VARCHAR2(255 BYTE), 
	"CATEGORY_2" VARCHAR2(255 BYTE), 
	"ITEM_NUMBER" VARCHAR2(255 BYTE), 
	"ORGANIZATION" VARCHAR2(255 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(255 BYTE), 
	"SHIP_TO_SITE" VARCHAR2(255 BYTE), 
	"COUNTRY" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"HOLD_NAME" VARCHAR2(255 BYTE), 
	"HOLD_COMMENTS" VARCHAR2(2000 BYTE), 
	"START_DATE" DATE, 
	"AUTO_RELEASE_FLAG" VARCHAR2(20 BYTE), 
	"RULE_ID" NUMBER, 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"END_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"DEPARTMENT" VARCHAR2(255 BYTE), 
	"ZIP_CODE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_AUTO_HOLD_CUSTOM_RULES_EXT" TO "RO_HBG_INTEGRATION";
