--------------------------------------------------------
--  DDL for Index HBG_PROCESS_ORDERS_CHARGES_FBDI_IDX_1
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_CHARGES_FBDI_IDX_1" ON "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_CHARGES_FBDI" ("SBI_UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
