--------------------------------------------------------
--  DDL for View HBG_AR_PAYMENTS_HEADER_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "HBG_INTEGRATION"."HBG_AR_PAYMENTS_HEADER_V" ("BATCH_ID", "BATCH_AMOUNT", "BATCH_COUNT", "BATCH_COUNT_PROCESSED", "BATCH_COUNT_ERROR", "BATCH_COUNT_DRAFT", "STATUS", "CREATION_DATE", "CREATED_BY", "LAST_UPDATE_DATE", "LAST_UPDATED_BY") AS 
  WITH BATCH_INFO AS 
(
SELECT HAPH.BATCH_ID
     , NVL((SELECT SUM(AMOUNT)
              FROM HBG_AR_PAYMENTS_LINES
             WHERE BATCH_ID = HAPH.BATCH_ID), 0) BATCH_AMOUNT
     , NVL((SELECT COUNT(LINE_ID)
              FROM HBG_AR_PAYMENTS_LINES
             WHERE BATCH_ID = HAPH.BATCH_ID), 0) BATCH_COUNT
     , NVL((SELECT COUNT(LINE_ID)
              FROM HBG_AR_PAYMENTS_LINES
             WHERE RETURN_STATUS = 'PROCESSED'
               AND BATCH_ID = HAPH.BATCH_ID), 0) BATCH_COUNT_PROCESSED
     , NVL((SELECT COUNT(LINE_ID)
              FROM HBG_AR_PAYMENTS_LINES
             WHERE RETURN_STATUS = 'ERROR'
               AND BATCH_ID = HAPH.BATCH_ID), 0) BATCH_COUNT_ERROR
     , NVL((SELECT COUNT(LINE_ID)
              FROM HBG_AR_PAYMENTS_LINES
             WHERE RETURN_STATUS = 'DRAFT'
               AND BATCH_ID = HAPH.BATCH_ID), 0) BATCH_COUNT_DRAFT
     , HAPH.CREATION_DATE
     , HAPH.CREATED_BY
     , HAPH.LAST_UPDATE_DATE
     , HAPH.LAST_UPDATED_BY
  FROM HBG_AR_PAYMENTS_HEADER HAPH
  )
  
SELECT BATCH_ID
     , BATCH_AMOUNT
     , BATCH_COUNT
     , BATCH_COUNT_PROCESSED
     , BATCH_COUNT_ERROR
     , BATCH_COUNT_DRAFT
     , CASE WHEN BATCH_COUNT = BATCH_COUNT_DRAFT
            THEN 'DRAFT'
            WHEN BATCH_COUNT_PROCESSED + BATCH_COUNT_ERROR < BATCH_COUNT
            THEN 'PROCESSING'
            WHEN BATCH_COUNT_ERROR > 0 
            THEN 'ERROR'
            WHEN BATCH_COUNT_PROCESSED > 0
             AND BATCH_COUNT_ERROR = 0
            THEN 'PROCESSED' 
             END STATUS
     , CREATION_DATE
     , CREATED_BY
     , LAST_UPDATE_DATE
     , LAST_UPDATED_BY
  FROM BATCH_INFO BATCH_INFO
 ORDER BY CREATION_DATE DESC
;
