--------------------------------------------------------
--  DDL for Table HBG_DIST_RIGHTS_PREC_LEV_EXT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_DIST_RIGHTS_PREC_LEV_EXT" 
   (	"OWNER" NUMBER, 
	"REPORTING_GROUP" NUMBER, 
	"CATEGORY_1" NUMBER, 
	"CATEGORY_2" NUMBER, 
	"FORMAT" NUMBER, 
	"SUBFORMAT" NUMBER, 
	"FROM_PUB_DATE" NUMBER, 
	"TO_PUB_DATE" NUMBER, 
	"COUNTRY_GROUP" NUMBER, 
	"COUNTRY_CODE" NUMBER, 
	"ITEM_NUMBER" NUMBER, 
	"ACCOUNT_NUMBER" NUMBER, 
	"ACCOUNT_TYPE" NUMBER, 
	"DEFAULT_ACCT_TYPE" NUMBER, 
	"PRECEDENCE_LEVEL" NUMBER, 
	"EDITION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_DIST_RIGHTS_PREC_LEV_EXT" TO "RO_HBG_INTEGRATION";
