--------------------------------------------------------
--  DDL for Index HBG_PROCESS_ORDERS_PAYMENT_TKN_FBDI_IDX_2
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_PAYMENT_TKN_FBDI_IDX_2" ON "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_PAYMENT_TKN_FBDI" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
