--------------------------------------------------------
--  DDL for Table HBG_PIM_PRM_STG_BKP
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PIM_PRM_STG_BKP" 
   (	"ISBN13" VARCHAR2(13 BYTE), 
	"PARENT_PRODUCT" VARCHAR2(20 BYTE), 
	"PRIMARY_IND" NVARCHAR2(1), 
	"RELATION_TYPE" VARCHAR2(20 BYTE), 
	"RELATION_SEQ_NO" FLOAT(126), 
	"PIECES_IN_PACK" FLOAT(126), 
	"BOM_TYPE" NVARCHAR2(1), 
	"ZERO_IND" NVARCHAR2(1), 
	"IS_ACTIVE" NUMBER(5,0), 
	"DBCS_CREATE_TIMESTAMP" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(240 BYTE), 
	"DBCS_UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(240 BYTE), 
	"HBG_PROCESS_ID" NUMBER(20,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
