--------------------------------------------------------
--  DDL for Sequence HBG_AUTO_HOLD_SO_HOLDS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."HBG_AUTO_HOLD_SO_HOLDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1012 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
