--------------------------------------------------------
--  DDL for Table HBG_COUNTRY_GROUP_ASSOC_STG
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_COUNTRY_GROUP_ASSOC_STG" 
   (	"COUNTRY_GROUP_CODE" VARCHAR2(255 BYTE), 
	"CG_UID" NUMBER, 
	"CGD_UID" NUMBER, 
	"COUNTRY" VARCHAR2(25 BYTE), 
	"INS_USER" VARCHAR2(255 BYTE), 
	"INS_TIMESTAMP" TIMESTAMP (6), 
	"LAST_UPD_USER" VARCHAR2(255 BYTE), 
	"LAST_UPD_TIMESTAMP" TIMESTAMP (6), 
	"STATUS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
