--------------------------------------------------------
--  DDL for Table HBG_COUNTRY_GROUP_ASSOC_EXT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_COUNTRY_GROUP_ASSOC_EXT" 
   (	"COUNTRY_GROUP_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"COUNTRY_CODE" VARCHAR2(25 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_BY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_COUNTRY_GROUP_ASSOC_EXT" TO "RO_HBG_INTEGRATION";
