--------------------------------------------------------
--  DDL for Table HBG_AR_TRX_MAINT_SESSION
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_AR_TRX_MAINT_SESSION" 
   (	"RECORD_ID" NUMBER, 
	"SESSION_ID" NUMBER, 
	"LOGGED_IN_USER" VARCHAR2(200 BYTE), 
	"LOGGED_IN_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_AR_TRX_MAINT_SESSION" TO "RO_HBG_INTEGRATION";
