--------------------------------------------------------
--  DDL for Table HBG_CX_ITEMS_FAILED_REC
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CX_ITEMS_FAILED_REC" 
   (	"PRODUCT_ID" VARCHAR2(30 BYTE), 
	"LINE_NUMBER" NUMBER, 
	"INSTANCEID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_TS_DEBUG" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_CX_ITEMS_FAILED_REC" TO "RO_HBG_INTEGRATION";
