--------------------------------------------------------
--  DDL for Sequence HBG_CO_TEMPLATE_LINES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."HBG_CO_TEMPLATE_LINES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
