--------------------------------------------------------
--  DDL for Index IDX1_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_B
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."IDX1_HBG_EGO_ITEM_SUPPLIER_INTF_EFF_B" ON "HBG_INTEGRATION"."HBG_EGO_ITEM_SUPPLIER_INTF_EFF_B" ("ITEM_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
