--------------------------------------------------------
--  DDL for Index IND_HBG_INV_TRANS_ARCHIVE_003
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."IND_HBG_INV_TRANS_ARCHIVE_003" ON "HBG_INTEGRATION"."HBG_INV_TRANSACTIONS_ARCHIVE" ("SOURCE_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
