--------------------------------------------------------
--  DDL for Table QP_PRICE_LISTS_TL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."QP_PRICE_LISTS_TL" 
   (	"PRICE_LIST_ID" NUMBER, 
	"LANGUAGE" VARCHAR2(16 BYTE), 
	"SOURCE_LANG" VARCHAR2(16 BYTE), 
	"NAME" VARCHAR2(320 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"OBJECT_VERSION_NUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."QP_PRICE_LISTS_TL" TO "RO_HBG_INTEGRATION";
