--------------------------------------------------------
--  DDL for Table XX_HBG_ACCT_TYPE_HDR_EXT_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XX_HBG_ACCT_TYPE_HDR_EXT_TBL" 
   (	"STAGE_ID" NUMBER, 
	"PARTY_ID" NUMBER, 
	"PARTY_NAME" VARCHAR2(500 BYTE), 
	"PARTY_NUMBER" VARCHAR2(100 BYTE), 
	"CUST_ACCOUNT_ID" NUMBER, 
	"ACCOUNT_NUMBER" VARCHAR2(200 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(200 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ACCOUNT_TYPE_CODE" VARCHAR2(200 BYTE), 
	"ACCOUNT_TYPE_DESC" VARCHAR2(500 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"OIC_RUN_ID" NUMBER, 
	"LAST_RUN_DATE" DATE, 
	"LAST_RUN_SYNC_DATE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XX_HBG_ACCT_TYPE_HDR_EXT_TBL" TO "RO_HBG_INTEGRATION";
