--------------------------------------------------------
--  DDL for Index XXDOO_ORDER_LINES_ALL_INT_N1
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."XXDOO_ORDER_LINES_ALL_INT_N1" ON "HBG_INTEGRATION"."XXDOO_ORDER_LINES_ALL_INT" ("INTERFACE_RUN_ID", "SOURCE_TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
