--------------------------------------------------------
--  DDL for Table XXHBG_SAAS_DATA_SYNC_FILTERS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_SAAS_DATA_SYNC_FILTERS" 
   (	"FILTER_ID" NUMBER, 
	"OBJECT_ID" NUMBER, 
	"FILTER_TYPE" VARCHAR2(50 BYTE) DEFAULT 'INCLUDE', 
	"FILTER_VALUE" VARCHAR2(400 BYTE), 
	"COLUMN_NAME" VARCHAR2(200 BYTE), 
	"ENABLED" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_SAAS_DATA_SYNC_FILTERS" TO "RO_HBG_INTEGRATION";
