--------------------------------------------------------
--  DDL for Table XXHBG_SF_ACCT_TYPE_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" 
   (	"SF_ACCT_TYPE_ID" NUMBER, 
	"SALES_FORCE_NUMBER" NUMBER, 
	"SALES_FORCE_NAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"OWNER_NAME" VARCHAR2(200 BYTE), 
	"ACCOUNT_TYPE" VARCHAR2(200 BYTE), 
	"ACCOUNT_TYPE_NAME" VARCHAR2(200 BYTE), 
	"NOTES" VARCHAR2(200 BYTE), 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(200 BYTE), 
	"SF_SALES_REP_ID" NUMBER, 
	"SALES_FORCE_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" TO "RO_HBG_INTEGRATION";
