--------------------------------------------------------
--  DDL for Trigger XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL_TRG" BEFORE
    INSERT ON "XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL"
    FOR EACH ROW
BEGIN
    IF :new.DIST_CHNL_ASSIGN_ID IS NULL THEN
        SELECT
            XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_SEQ.NEXTVAL
        INTO :new.DIST_CHNL_ASSIGN_ID
        FROM
            sys.dual;

    END IF;
END;
/
ALTER TRIGGER "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_TBL_TRG" ENABLE;
