--------------------------------------------------------
--  DDL for Table XXHBG_SALES_FORCE_MAPPING_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" 
   (	"SF_MAPPING_ID" NUMBER, 
	"ISBN" VARCHAR2(200 BYTE), 
	"SALES_FORCE" VARCHAR2(200 BYTE), 
	"SALES_FORCE_NAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"OWNER_DESCRIPTION" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP_DESCRIPTION" VARCHAR2(200 BYTE), 
	"CATEGORY_1" VARCHAR2(200 BYTE), 
	"CATEGORY_1_DESCRIPTION" VARCHAR2(200 BYTE), 
	"CATEGORY_2" VARCHAR2(200 BYTE), 
	"CATEGORY_2_DESCRIPTION" VARCHAR2(200 BYTE), 
	"FORMAT" VARCHAR2(200 BYTE), 
	"FORMAT_DESCRIPTION" VARCHAR2(200 BYTE), 
	"SUB_FORMAT" VARCHAR2(200 BYTE), 
	"SUB_FORMAT_DESCRIPTION" VARCHAR2(200 BYTE), 
	"BISAC" VARCHAR2(200 BYTE), 
	"BISAC_DESCRIPTION" VARCHAR2(200 BYTE), 
	"ACCOUNT_TYPE" VARCHAR2(200 BYTE), 
	"ACCOUNT_TYPE_DESCRIPTION" VARCHAR2(200 BYTE), 
	"PRIORITY" NUMBER, 
	"NOTES" VARCHAR2(200 BYTE), 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(200 BYTE), 
	"SALES_FORCE_ID" NUMBER, 
	"SF_ACCT_TYPE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" TO "RO_HBG_INTEGRATION";
