--------------------------------------------------------
--  DDL for Trigger XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER_TRG" BEFORE
    INSERT ON "XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER"
    FOR EACH ROW
BEGIN
    IF :new.PUB_ID IS NULL THEN
        SELECT
            XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER_SEQ.NEXTVAL
        INTO :new.PUB_ID
        FROM
            sys.dual;

    END IF;
END;
/
ALTER TRIGGER "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER_TRG" ENABLE;
