--------------------------------------------------------
--  DDL for Table XXHBG_DIST_CHANNEL_PREC_LEV_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_DIST_CHANNEL_PREC_LEV_TBL" 
   (	"OWNER" NUMBER, 
	"REPORTING_GROUP" NUMBER, 
	"CATEGORY_1" NUMBER, 
	"CATEGORY_2" NUMBER, 
	"BISAC" NUMBER, 
	"PRECEDENCE_LEVEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
