--------------------------------------------------------
--  DDL for Table XXHBG_UNASSIGNED_SALES_FORCE_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_UNASSIGNED_SALES_FORCE_TBL" 
   (	"SF_UNASSIGNED_ID" NUMBER, 
	"TYPE" VARCHAR2(200 BYTE), 
	"ORGANIZATION_NUMBER" NUMBER, 
	"ACCOUNT_TYPE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"ACCOUNT_PREFIX" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"OWNER_DESCRIPTION" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP_DESCRIPTION" VARCHAR2(200 BYTE), 
	"BILL_TO_COUNTRY" VARCHAR2(200 BYTE), 
	"BILL_TO_STATE" VARCHAR2(200 BYTE), 
	"SHIP_TO_COUNTRY" VARCHAR2(200 BYTE), 
	"SHIP_TO_STATE" VARCHAR2(200 BYTE), 
	"FINAL_DESTINATION_COUNTRY" VARCHAR2(200 BYTE), 
	"SALES_FORCE_NUMBER" VARCHAR2(200 BYTE), 
	"SALES_FORCE_NAME" VARCHAR2(200 BYTE), 
	"DIVISION" VARCHAR2(200 BYTE), 
	"DIVISION_NAME" VARCHAR2(200 BYTE), 
	"TERRITORY" VARCHAR2(20 BYTE), 
	"TERRITORY_NAME" VARCHAR2(200 BYTE), 
	"SALES_REP" VARCHAR2(200 BYTE), 
	"SALES_REP_NAME" VARCHAR2(200 BYTE), 
	"NOTES" VARCHAR2(200 BYTE), 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(200 BYTE), 
	"SF_ASSIGN_ID" NUMBER, 
	"SALES_FORCE_ID" NUMBER, 
	"ACCOUNT_NUMBER" VARCHAR2(100 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(100 BYTE), 
	"ORGANIZATION_NAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_UNASSIGNED_SALES_FORCE_TBL" TO "RO_HBG_INTEGRATION";
