--------------------------------------------------------
--  DDL for Table XXHBG_RES_PRE_RESERVATION_HEADER
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_HEADER" 
   (	"PRE_RESERVATION_NUMBER" VARCHAR2(200 BYTE), 
	"INVENTORY_ORGANIZATION" VARCHAR2(200 BYTE), 
	"REQUESTER" VARCHAR2(200 BYTE), 
	"APPROVER" VARCHAR2(200 BYTE), 
	"REASON_CODE" VARCHAR2(200 BYTE), 
	"RESERVATION_TYPE" VARCHAR2(200 BYTE), 
	"PRINT_NUMBER" VARCHAR2(200 BYTE), 
	"EXPIRATION_DATE" DATE, 
	"COMMENTS" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(200 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"AUTO_CLEAR_ON_EXPIRY_DATE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_RES_PRE_RESERVATION_HEADER" TO "RO_HBG_INTEGRATION";
