--------------------------------------------------------
--  DDL for Table FND_DOCUMENT_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."FND_DOCUMENT_CATEGORIES" 
   (	"ROW_ID" ROWID, 
	"CATEGORY_NAME" VARCHAR2(120 BYTE), 
	"CATEGORY_ID" NUMBER, 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"USER_NAME" VARCHAR2(1020 BYTE), 
	"APPLICATION_ID" NUMBER, 
	"MODULE_ID" VARCHAR2(128 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
