--------------------------------------------------------
--  DDL for Table FND_TERRITORIES_B
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."FND_TERRITORIES_B" 
   (	"ENTERPRISE_ID" NUMBER, 
	"TERRITORY_CODE" VARCHAR2(8 BYTE), 
	"ALTERNATE_TERRITORY_CODE" VARCHAR2(120 BYTE), 
	"NLS_TERRITORY" VARCHAR2(120 BYTE), 
	"ISO_NUMERIC_CODE" VARCHAR2(12 BYTE), 
	"ISO_TERRITORY_CODE" VARCHAR2(12 BYTE), 
	"OBSOLETE_FLAG" VARCHAR2(4 BYTE), 
	"ENABLED_FLAG" VARCHAR2(4 BYTE), 
	"ADDRESS_STYLE" VARCHAR2(120 BYTE), 
	"ADDRESS_VALIDATION" VARCHAR2(120 BYTE), 
	"BANK_INFO_STYLE" VARCHAR2(120 BYTE), 
	"BANK_INFO_VALIDATION" VARCHAR2(120 BYTE), 
	"EU_CODE" VARCHAR2(12 BYTE), 
	"CURRENCY_CODE" VARCHAR2(60 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"SEED_DATA_SOURCE" VARCHAR2(2048 BYTE), 
	"ORA_SEED_SET1" VARCHAR2(4 BYTE), 
	"ORA_SEED_SET2" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
