--------------------------------------------------------
--  DDL for Sequence HBG_AUTO_HOLD_CUSTOM_RULES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."HBG_AUTO_HOLD_CUSTOM_RULES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1229 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
