--------------------------------------------------------
--  Constraints for Table HBG_ITEMS
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."HBG_ITEMS" MODIFY ("ITEM_OWNER" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."HBG_ITEMS" MODIFY ("CUST_ACCT_ID" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."HBG_ITEMS" ADD CONSTRAINT "HBG_ITEMS_PK" PRIMARY KEY ("ITEM_OWNER", "CUST_ACCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
