--------------------------------------------------------
--  DDL for Table HBG_PROCESS_ORDER_SUBMIT_BATCHES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_PROCESS_ORDER_SUBMIT_BATCHES" 
   (	"BATCH_NAME" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
