--------------------------------------------------------
--  Constraints for Table HBG_PROCESS_ORDERS_SUBMIT_BATCHES
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_SUBMIT_BATCHES" MODIFY ("BATCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."HBG_PROCESS_ORDERS_SUBMIT_BATCHES" ADD CONSTRAINT "HBG_PROCESS_ORDERS_SUBMIT_BATCHES_PK" PRIMARY KEY ("BATCH_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
