--------------------------------------------------------
--  DDL for Sequence HBG_AR_TRXMAINT_TRX_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."HBG_AR_TRXMAINT_TRX_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 273248 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
