--------------------------------------------------------
--  DDL for Table HBG_CO_TEMPLATE_LINES
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CO_TEMPLATE_LINES" 
   (	"TEMPLATE_ID" NUMBER, 
	"LINE_ID" NUMBER(*,0) DEFAULT "HBG_INTEGRATION"."LINE_ID_SEQ"."NEXTVAL", 
	"SEQUENCE" NUMBER, 
	"CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"CATEGORY_NAME" VARCHAR2(255 BYTE), 
	"INSTRUCTIONS_TEXT" VARCHAR2(2000 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_BY" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
