--------------------------------------------------------
--  DDL for Index HBG_AUTO_HOLD_CUSTOMER_EXT_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBG_INTEGRATION"."HBG_AUTO_HOLD_CUSTOMER_EXT_PK1" ON "HBG_INTEGRATION"."HBG_AUTO_HOLD_CUSTOMER_EXT" ("CUST_ACCOUNT_ID", "CUST_ACCT_SITE_ID", "ORGANIZATION_ID", "SITE_USE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
