--------------------------------------------------------
--  DDL for Table HBG_WMS_INV_TRX_HEADER
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_WMS_INV_TRX_HEADER" 
   (	"SOURCE_HEADER_ID" VARCHAR2(200 BYTE), 
	"TRANSACTION_TYPE" VARCHAR2(50 BYTE), 
	"SOURCE_LINE_ID" VARCHAR2(200 BYTE), 
	"ISBN" VARCHAR2(200 BYTE), 
	"TRANSACTION_QUANTITY" VARCHAR2(200 BYTE), 
	"TRANSACTION_DATE" VARCHAR2(200 BYTE), 
	"TRANSACTION_UOM" VARCHAR2(200 BYTE), 
	"TRANSACTION_REFERENCE" VARCHAR2(200 BYTE), 
	"SUBINVENTORY" VARCHAR2(200 BYTE), 
	"TRANSFER_SUBINVENTORY" VARCHAR2(200 BYTE), 
	"REASON_NAME" VARCHAR2(200 BYTE), 
	"ORGANIZATION_NAME" VARCHAR2(200 BYTE), 
	"SOURCE_CODE" VARCHAR2(200 BYTE), 
	"TRANSACTION_MODE" VARCHAR2(200 BYTE), 
	"ERROR_CODE" VARCHAR2(200 BYTE), 
	"ERROR_TXT" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"INV_TRX_HEADER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_WMS_INV_TRX_HEADER" TO "RO_HBG_INTEGRATION";
