--------------------------------------------------------
--  DDL for Table HBG_CX_ITEMS_COLLECTIONS
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."HBG_CX_ITEMS_COLLECTIONS" 
   (	"COLLECTION_ID" VARCHAR2(50 BYTE), 
	"DISPLAY_NAME" VARCHAR2(200 BYTE), 
	"IS_ACTIVE" VARCHAR2(5 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."HBG_CX_ITEMS_COLLECTIONS" TO "RO_HBG_INTEGRATION";
