--------------------------------------------------------
--  DDL for Index IDX2_HBG_EGO_ITEM_INTF_EFF_B
--------------------------------------------------------

  CREATE INDEX "HBG_INTEGRATION"."IDX2_HBG_EGO_ITEM_INTF_EFF_B" ON "HBG_INTEGRATION"."HBG_EGO_ITEM_INTF_EFF_B" ("ORGANIZATION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
