--------------------------------------------------------
--  DDL for Index INV_LOT_NUMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HBG_INTEGRATION"."INV_LOT_NUMBERS_PK" ON "HBG_INTEGRATION"."XXHBG_INV_LOT_NUMBERS_SYNC" ("INVENTORY_ITEM_ID", "ORGANIZATION_ID", "LOT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
