--------------------------------------------------------
--  DDL for Table XXDOO_ORDER_PAYMENTS_INT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXDOO_ORDER_PAYMENTS_INT" 
   (	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(120 BYTE), 
	"SOURCE_TRANSACTION_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_LINE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_SCHEDULE_ID" VARCHAR2(200 BYTE), 
	"PAYMENT_METHOD_CODE" VARCHAR2(4000 BYTE), 
	"PAYMENT_METHOD" VARCHAR2(4000 BYTE), 
	"PAYMENT_TRANSACTION_ID" NUMBER, 
	"PAYMENT_SET_ID" NUMBER, 
	"SOURCE_TRANSACTION_PAYMENT_ID" VARCHAR2(200 BYTE), 
	"PAYMENT_TYPE" VARCHAR2(320 BYTE), 
	"PAYMENT_TYPE_CODE" VARCHAR2(120 BYTE), 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"LOAD_REQUEST_ID" NUMBER, 
	"INTERFACE_RUN_ID" NUMBER, 
	"ICS_RUN_ID" NUMBER, 
	"SAAS_PROCESS_ID" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(4000 BYTE), 
	"FILE_NAME" VARCHAR2(240 BYTE), 
	"ICS_BATCH_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXDOO_ORDER_PAYMENTS_INT" TO "RO_HBG_INTEGRATION";
