--------------------------------------------------------
--  DDL for Table XXDOO_ORDER_TXN_ATTRIBUTES_INT
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXDOO_ORDER_TXN_ATTRIBUTES_INT" 
   (	"SOURCE_TXN_LINE_ATTRIBUTE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_SYSTEM" VARCHAR2(120 BYTE), 
	"SOURCE_TRANSACTION_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_LINE_ID" VARCHAR2(200 BYTE), 
	"SOURCE_TRANSACTION_SCHEDULE_ID" VARCHAR2(200 BYTE), 
	"TRANSACTION_ATTRIBUTE_CODE" VARCHAR2(400 BYTE), 
	"TRANSACTION_ATTRIBUTE_NAME" VARCHAR2(400 BYTE), 
	"TRANSACTION_ATTRIBUTE_ID" NUMBER, 
	"CHARACTER_VALUE" VARCHAR2(4000 BYTE), 
	"NUMBER_VALUE" NUMBER, 
	"DATE_VALUE" DATE, 
	"TIMESTAMP_VALUE" TIMESTAMP (6), 
	"LOAD_REQUEST_ID" NUMBER, 
	"CREATION_DATE" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(256 BYTE), 
	"LAST_UPDATE_LOGIN" VARCHAR2(128 BYTE), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"INTERFACE_RUN_ID" NUMBER, 
	"ICS_RUN_ID" NUMBER, 
	"SAAS_PROCESS_ID" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(4000 BYTE), 
	"FILE_NAME" VARCHAR2(240 BYTE), 
	"ICS_BATCH_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXDOO_ORDER_TXN_ATTRIBUTES_INT" TO "RO_HBG_INTEGRATION";
