--------------------------------------------------------
--  DDL for Trigger XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_TRG" BEFORE
    INSERT ON "XXHBG_FAMILY_CODE_REPORTING_CATEGORY1"
    FOR EACH ROW
BEGIN
    IF :new.CATEGORY1_ID IS NULL THEN
        SELECT
            XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_SEQ.NEXTVAL
        INTO :new.CATEGORY1_ID
        FROM
            sys.dual;

    END IF;
END;
/
ALTER TRIGGER "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_REPORTING_CATEGORY1_TRG" ENABLE;
