--------------------------------------------------------
--  DDL for Sequence XXHBG_DEFAULT_DISTRIBUTION_CHANNEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_DEFAULT_DISTRIBUTION_CHANNEL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999 INCREMENT BY 1 START WITH 381 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
