--------------------------------------------------------
--  DDL for Trigger XXHBG_UNASSIGNED_SALES_FORCE_TBL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HBG_INTEGRATION"."XXHBG_UNASSIGNED_SALES_FORCE_TBL_TRG" BEFORE
    INSERT ON "XXHBG_UNASSIGNED_SALES_FORCE_TBL"
    FOR EACH ROW
BEGIN
    IF :new.SF_UNASSIGNED_ID IS NULL THEN
        SELECT
            XXHBG_UNASSIGNED_SALES_FORCE_TBL_SEQ.NEXTVAL
        INTO :new.SF_UNASSIGNED_ID
        FROM
            sys.dual;

    END IF;
END;
/
ALTER TRIGGER "HBG_INTEGRATION"."XXHBG_UNASSIGNED_SALES_FORCE_TBL_TRG" ENABLE;
