--------------------------------------------------------
--  DDL for Sequence XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_ASSIGN_DISTRUBUTION_CHANNEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10143 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
