--------------------------------------------------------
--  DDL for Trigger XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HBG_INTEGRATION"."XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TRG" BEFORE
    INSERT ON "XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TBL"
    FOR EACH ROW
BEGIN
    IF :new.SF_ACCOUNT_ID IS NULL THEN
        SELECT
           XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_SEQ.NEXTVAL
        INTO :new.SF_ACCOUNT_ID
        FROM
            sys.dual;

    END IF;
END;
/
ALTER TRIGGER "HBG_INTEGRATION"."XXHBG_ASSIGN_ACCOUNT_TYPE_TO_SALES_FORCE_TRG" ENABLE;
