--------------------------------------------------------
--  DDL for Sequence XXHBG_RES_PRE_RES_RECORD_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_RES_PRE_RES_RECORD_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 236 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
