--------------------------------------------------------
--  Constraints for Table XXHBG_SALES_FORCE_MAPPING_TBL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("SF_MAPPING_ID" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("SALES_FORCE" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("SALES_FORCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("OWNER" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("REPORTING_GROUP" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("ENTERED_BY" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("ENTERED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_MAPPING_TBL" MODIFY ("STATUS" NOT NULL ENABLE);
