--------------------------------------------------------
--  DDL for Sequence XXHBG_SAAS_DATA_SYNC_RUNID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HBG_INTEGRATION"."XXHBG_SAAS_DATA_SYNC_RUNID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1937104 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
