--------------------------------------------------------
--  Constraints for Table XXHBG_SALES_FORCE_ASSIGN_TBL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_ASSIGN_TBL" MODIFY ("SF_ASSIGN_ID" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_ASSIGN_TBL" MODIFY ("ENTERED_BY" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_ASSIGN_TBL" MODIFY ("ENTERED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_ASSIGN_TBL" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SALES_FORCE_ASSIGN_TBL" MODIFY ("STATUS" NOT NULL ENABLE);
