--------------------------------------------------------
--  DDL for Table XXHBG_DISTRUBUTION_CHANNEL_TBL
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_DISTRUBUTION_CHANNEL_TBL" 
   (	"DIST_CHANNEL_ID" NUMBER, 
	"DISTRIBUTION_CHANNEL" VARCHAR2(200 BYTE), 
	"DIST_CHANNEL_DESCRIPTION" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"OWNER_DESCRIPTION" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP" VARCHAR2(200 BYTE), 
	"REPORTING_GROUP_DESCRIPTION" VARCHAR2(200 BYTE), 
	"ENTERED_BY" VARCHAR2(200 BYTE), 
	"ENTERED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_DATE" DATE, 
	"START_DATE" DATE, 
	"END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_DISTRUBUTION_CHANNEL_TBL" TO "RO_HBG_INTEGRATION";
