--------------------------------------------------------
--  Constraints for Table XXHBG_SF_ACCT_TYPE_TBL
--------------------------------------------------------

  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" ADD PRIMARY KEY ("SF_ACCT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "HBG_INTEGRATION_TS_DATA"  ENABLE;
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" MODIFY ("SF_ACCT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" MODIFY ("ENTERED_BY" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" MODIFY ("ENTERED_DATE" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HBG_INTEGRATION"."XXHBG_SF_ACCT_TYPE_TBL" MODIFY ("STATUS" NOT NULL ENABLE);
