--------------------------------------------------------
--  DDL for Table XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER
--------------------------------------------------------

  CREATE TABLE "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER" 
   (	"PUB_ID" NUMBER, 
	"EXTERNAL_PUB_CODE" VARCHAR2(20 BYTE), 
	"EXTERNAL_PUB_NAME" VARCHAR2(200 BYTE), 
	"EXTERNAL_PUB_ABBR" VARCHAR2(200 BYTE), 
	"CREATED_DATE" DATE, 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(200 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(200 BYTE), 
	"CATEGORY1_ID" NUMBER, 
	"REPORTING_GROUP_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HBG_INTEGRATION_TS_DATA" ;
  GRANT SELECT ON "HBG_INTEGRATION"."XXHBG_FAMILY_CODE_EXTERNAL_PUBLISHER" TO "RO_HBG_INTEGRATION";
